In [1]:
import pandas as pd
print(pd.__version__)

3.0.5

In [4]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,78876.0,78876.000000,78876.000000,78876.000000,78876.000000,78168.000000,78876.000000,78876.000000,78876.000000,78876.000000,...,68676.000000,68676.000000,68676.00000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000
mean,2026.0,0.192454,1.784573,16.070928,29.583333,0.500000,1894.630002,0.500000,5.494396,5.505198,...,301.960510,0.000000,0.00000,0.000000,3.638505,7.049595,3.646135,3.638505,7.049595,3.646135
std,0.0,0.394230,0.926562,0.036494,57.650833,0.500003,327.814511,0.500003,6.559048,6.276914,...,281.502973,3362.222105,3517.12681,38.615409,4.537478,8.657831,4.367311,4.537478,8.657831,4.367311
min,2026.0,0.000000,1.000000,16.010000,1.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,...,7.000000,-21038.000000,-22919.00000,-301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.0,0.000000,1.000000,16.040000,3.750000,0.000000,1658.000000,0.000000,1.000000,2.000000,...,178.000000,-1378.000000,-1501.00000,-19.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2026.0,0.000000,2.000000,16.080000,6.500000,0.500000,1867.000000,0.500000,3.000000,4.000000,...,221.000000,0.000000,0.00000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2026.0,0.000000,2.000000,16.100000,9.250000,1.000000,2090.000000,1.000000,7.000000,6.000000,...,258.000000,1378.000000,1501.00000,19.000000,5.000000,8.000000,4.000000,5.000000,8.000000,4.000000
max,2026.0,1.000000,5.000000,16.140000,200.000000,1.000000,3430.000000,1.000000,54.000000,54.000000,...,1132.000000,21038.000000,22919.00000,301.000000,44.000000,88.000000,44.000000,44.000000,88.000000,44.000000

In [5]:
df.shape

(78876, 165)

In [6]:
df.columns.tolist()
df.head()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,LOLTMNT05_171038,complete,NaN,LIT,2026,Winter,0,2026-01-08 17:08:27,1,16.01,...,192.0,-1103.0,-560.0,-28.0,6.0,1.0,4.0,7.0,4.0,4.0
1,LOLTMNT05_171038,complete,NaN,LIT,2026,Winter,0,2026-01-08 17:08:27,1,16.01,...,194.0,-586.0,-1672.0,-34.0,4.0,2.0,5.0,4.0,2.0,3.0
2,LOLTMNT05_171038,complete,NaN,LIT,2026,Winter,0,2026-01-08 17:08:27,1,16.01,...,221.0,-333.0,-807.0,-8.0,1.0,4.0,4.0,5.0,3.0,5.0
3,LOLTMNT05_171038,complete,NaN,LIT,2026,Winter,0,2026-01-08 17:08:27,1,16.01,...,194.0,2641.0,1926.0,38.0,8.0,3.0,4.0,4.0,6.0,4.0
4,LOLTMNT05_171038,complete,NaN,LIT,2026,Winter,0,2026-01-08 17:08:27,1,16.01,...,23.0,1136.0,100.0,3.0,1.0,12.0,3.0,0.0,11.0,4.0

In [7]:
df.sample(10)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
51334,LOLTMNT04_161332,complete,NaN,LIT,2026,Spring,1,2026-05-08 16:07:47,1,16.09,...,870.0,-6245.0,-8415.0,13.0,4.0,4.0,12.0,12.0,25.0,4.0
13382,LOLTMNT05_175360,complete,NaN,AL,2026,Winter,0,2026-02-11 17:07:48,2,16.03,...,243.0,-108.0,1601.0,16.0,2.0,3.0,1.0,2.0,1.0,3.0
71022,LOLTMNT01_407126,complete,NaN,Asia Master,2026,NaN,0,2026-06-19 12:34:32,5,16.11,...,199.0,-1746.0,-842.0,-10.0,1.0,6.0,1.0,1.0,4.0,5.0
18886,LOLTMNT06_167162,complete,NaN,PRM,2026,Winter,0,2026-02-25 18:58:12,1,16.04,...,1033.0,-2022.0,-1762.0,-41.0,8.0,13.0,9.0,9.0,18.0,8.0
29468,LOLTMNT02_375754,complete,NaN,NACL,2026,Spring,0,2026-04-01 22:43:37,2,16.06,...,217.0,115.0,256.0,6.0,2.0,5.0,1.0,0.0,7.0,4.0
4667,LOLTMNT02_343180,complete,NaN,LCP,2026,Split 1,0,2026-01-24 11:15:43,3,16.01,...,965.0,774.0,1591.0,-24.0,8.0,23.0,4.0,4.0,13.0,8.0
20000,LOLTMNT03_350273,complete,NaN,LCS,2026,Lock-In,0,2026-02-27 22:07:00,2,16.04,...,244.0,2502.0,2448.0,19.0,5.0,3.0,0.0,0.0,2.0,3.0
28776,LOLTMNT05_184236,complete,NaN,AL,2026,Spring,0,2026-03-31 16:12:18,1,16.06,...,259.0,-4226.0,-4994.0,-123.0,2.0,2.0,6.0,6.0,1.0,0.0
13752,LOLTMNT02_352407,complete,NaN,LCK,2026,Cup,0,2026-02-12 10:48:56,4,16.03,...,254.0,-3412.0,-829.0,-45.0,0.0,2.0,1.0,3.0,0.0,0.0
68141,LOLTMNT01_399599,complete,NaN,EWC,2026,NaN,0,2026-06-08 20:13:41,2,16.11,...,187.0,2928.0,1797.0,48.0,5.0,2.0,3.0,1.0,3.0,2.0

In [8]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'url',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'playerid',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'dragons (type unknown)',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'atakhans',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [9]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,78876.0,78876.000000,78876.000000,78876.000000,78876.000000,78168.000000,78876.000000,78876.000000,78876.000000,78876.000000,...,68676.000000,68676.000000,68676.00000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000
mean,2026.0,0.192454,1.784573,16.070928,29.583333,0.500000,1894.630002,0.500000,5.494396,5.505198,...,301.960510,0.000000,0.00000,0.000000,3.638505,7.049595,3.646135,3.638505,7.049595,3.646135
std,0.0,0.394230,0.926562,0.036494,57.650833,0.500003,327.814511,0.500003,6.559048,6.276914,...,281.502973,3362.222105,3517.12681,38.615409,4.537478,8.657831,4.367311,4.537478,8.657831,4.367311
min,2026.0,0.000000,1.000000,16.010000,1.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,...,7.000000,-21038.000000,-22919.00000,-301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.0,0.000000,1.000000,16.040000,3.750000,0.000000,1658.000000,0.000000,1.000000,2.000000,...,178.000000,-1378.000000,-1501.00000,-19.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2026.0,0.000000,2.000000,16.080000,6.500000,0.500000,1867.000000,0.500000,3.000000,4.000000,...,221.000000,0.000000,0.00000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2026.0,0.000000,2.000000,16.100000,9.250000,1.000000,2090.000000,1.000000,7.000000,6.000000,...,258.000000,1378.000000,1501.00000,19.000000,5.000000,8.000000,4.000000,5.000000,8.000000,4.000000
max,2026.0,1.000000,5.000000,16.140000,200.000000,1.000000,3430.000000,1.000000,54.000000,54.000000,...,1132.000000,21038.000000,22919.00000,301.000000,44.000000,88.000000,44.000000,44.000000,88.000000,44.000000

In [10]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 78876 entries, 0 to 78875
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(122), int64(20), str(23)
memory usage: 99.3 MB

In [11]:
df['league'].unique()

<StringArray>
[        'LIT',        'LCKC',          'AL',         'ROL',         'LCK',
         'LPL',         'HLL',         'NLC',         'LCP',         'LEC',
       'CBLOL',         'TCL',        'CCWS',         'LFL',          'HW',
         'LCS',         'EBL',         'LJL',         'PRM',       'LPLOL',
         'LES',          'RL',          'CD',         'VCS',         'LRN',
         'LRS',          'AC',          'EM',         'FST',         'LAS',
        'NACL',          'NL',         'EWC',          'HM',          'HC',
         'PCS', 'Asia Master',         'MSI',   'KeSPA Cup']
Length: 39, dtype: str

In [15]:
df['gameid'].nunique()

6573

In [16]:
df.describe()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 78876 entries, 0 to 78875
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(122), int64(20), str(23)
memory usage: 99.3 MB

In [17]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,78876.0,78876.000000,78876.000000,78876.000000,78876.000000,78168.000000,78876.000000,78876.000000,78876.000000,78876.000000,...,68676.000000,68676.000000,68676.00000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000,68676.000000
mean,2026.0,0.192454,1.784573,16.070928,29.583333,0.500000,1894.630002,0.500000,5.494396,5.505198,...,301.960510,0.000000,0.00000,0.000000,3.638505,7.049595,3.646135,3.638505,7.049595,3.646135
std,0.0,0.394230,0.926562,0.036494,57.650833,0.500003,327.814511,0.500003,6.559048,6.276914,...,281.502973,3362.222105,3517.12681,38.615409,4.537478,8.657831,4.367311,4.537478,8.657831,4.367311
min,2026.0,0.000000,1.000000,16.010000,1.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,...,7.000000,-21038.000000,-22919.00000,-301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.0,0.000000,1.000000,16.040000,3.750000,0.000000,1658.000000,0.000000,1.000000,2.000000,...,178.000000,-1378.000000,-1501.00000,-19.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2026.0,0.000000,2.000000,16.080000,6.500000,0.500000,1867.000000,0.500000,3.000000,4.000000,...,221.000000,0.000000,0.00000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2026.0,0.000000,2.000000,16.100000,9.250000,1.000000,2090.000000,1.000000,7.000000,6.000000,...,258.000000,1378.000000,1501.00000,19.000000,5.000000,8.000000,4.000000,5.000000,8.000000,4.000000
max,2026.0,1.000000,5.000000,16.140000,200.000000,1.000000,3430.000000,1.000000,54.000000,54.000000,...,1132.000000,21038.000000,22919.00000,301.000000,44.000000,88.000000,44.000000,44.000000,88.000000,44.000000

In [18]:
fst_df = df[df['league'] == 'FST']
fst_df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25524,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25525,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25526,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25527,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25528,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26455,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,...,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26456,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,...,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26457,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,...,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26458,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,...,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26459,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,...,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [19]:
fst_df.shape

(540, 165)

In [20]:
fst_df['gameid'].unique()

<StringArray>
['LOLTMNT01_349243', 'LOLTMNT01_350155', 'LOLTMNT01_349264',
 'LOLTMNT01_349281', 'LOLTMNT01_349288', 'LOLTMNT01_349312',
 'LOLTMNT01_349329', 'LOLTMNT01_350246', 'LOLTMNT01_349522',
 'LOLTMNT01_350440', 'LOLTMNT01_349529', 'LOLTMNT01_350457',
 'LOLTMNT01_349555', 'LOLTMNT01_350472', 'LOLTMNT01_349576',
 'LOLTMNT01_350498', 'LOLTMNT01_349770', 'LOLTMNT01_350687',
 'LOLTMNT01_349782', 'LOLTMNT01_350703', 'LOLTMNT01_350716',
 'LOLTMNT01_349807', 'LOLTMNT01_351028', 'LOLTMNT01_350979',
 'LOLTMNT01_350983', 'LOLTMNT01_351065', 'LOLTMNT01_352009',
 'LOLTMNT01_352019', 'LOLTMNT01_351208', 'LOLTMNT01_351218',
 'LOLTMNT01_351223', 'LOLTMNT01_351241', 'LOLTMNT01_351251',
 'LOLTMNT01_352208', 'LOLTMNT01_351262', 'LOLTMNT01_351445',
 'LOLTMNT01_352417', 'LOLTMNT01_352425', 'LOLTMNT01_352447',
 'LOLTMNT01_351479', 'LOLTMNT01_352471', 'LOLTMNT01_351652',
 'LOLTMNT01_352609', 'LOLTMNT01_351658', 'LOLTMNT01_352610']
Length: 45, dtype: str

In [21]:
fst_df['gameid'].nunique()

45

In [22]:
fst_df.head(25)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,...,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25524,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25525,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25526,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25527,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25528,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
25529,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,195.0,4179.0,3362.0,50.0,6.0,2.0,1.0,1.0,1.0,5.0
25530,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,173.0,1447.0,2937.0,16.0,4.0,15.0,1.0,3.0,2.0,6.0
25531,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,236.0,1441.0,2153.0,-1.0,4.0,10.0,2.0,1.0,4.0,4.0
25532,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,282.0,900.0,980.0,-25.0,5.0,4.0,0.0,2.0,1.0,2.0
25533,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,28.0,1202.0,1970.0,-10.0,3.0,14.0,3.0,0.0,5.0,5.0
25534,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,944.0,-9169.0,-11402.0,-30.0,7.0,13.0,22.0,22.0,45.0,7.0
25535,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,...,914.0,9169.0,11402.0,30.0,22.0,45.0,7.0,7.0,13.0,22.0
25536,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,269.0,-756.0,1002.0,0.0,0.0,3.0,1.0,2.0,2.0,1.0
25537,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,175.0,206.0,345.0,-14.0,4.0,3.0,2.0,2.0,3.0,2.0
25538,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,208.0,2970.0,1322.0,43.0,5.0,2.0,1.0,0.0,4.0,4.0
25539,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,271.0,-691.0,1204.0,-15.0,2.0,5.0,1.0,3.0,4.0,3.0
25540,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,32.0,-317.0,417.0,-11.0,0.0,9.0,3.0,1.0,6.0,1.0
25541,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,269.0,756.0,-1002.0,0.0,2.0,2.0,1.0,0.0,3.0,1.0
25542,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,161.0,-206.0,-345.0,14.0,2.0,3.0,2.0,4.0,3.0,2.0
25543,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,251.0,-2970.0,-1322.0,-43.0,0.0,4.0,4.0,5.0,2.0,1.0
25544,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,256.0,691.0,-1204.0,15.0,3.0,4.0,3.0,2.0,5.0,1.0
25545,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,21.0,317.0,-417.0,11.0,1.0,6.0,1.0,0.0,9.0,3.0
25546,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,955.0,1412.0,4290.0,3.0,11.0,22.0,8.0,8.0,19.0,11.0
25547,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,...,958.0,-1412.0,-4290.0,-3.0,8.0,19.0,11.0,11.0,22.0,8.0
25548,LOLTMNT01_349264,complete,NaN,FST,2026,NaN,0,2026-03-16 14:46:52,3,16.05,...,253.0,-130.0,-1098.0,-33.0,0.0,2.0,1.0,1.0,4.0,4.0

In [24]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
fst_df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25524,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,oe:player:d87853a5c1c5463889d70a62cdbcffc,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0,28,0.9444,10807,6902,232.7825,0.196186,9150,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25525,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,oe:player:637ed20b1e41be1c51bd1a4cb211357,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11,55,1.8550,12060,8155,275.0422,0.231800,11925,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25526,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,oe:player:d709285b163a94af9d819e568c592ba,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3,22,0.7420,10726,6821,230.0506,0.193883,10500,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25527,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,oe:player:178ec186b0d43d2669342596c2808cd,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4,38,1.2816,13565,9660,325.8010,0.274577,14010,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25528,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,oe:player:b0ec3df39d61f953e7af0afd8eb8c4a,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11,127,4.2833,7548,3643,122.8668,0.103554,7675,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26455,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,8,Red,mid,Caps,oe:player:55dd587cdc4a278be6a5c37f9e539de,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Viktor,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,3,1,7,12,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21737,817.6928,0.370717,466.1944,503.7743,4885.0,10,0.3762,8,0.3009,4,34,1.2790,9911,6382,240.0752,0.207640,8950,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8025,3663.0,5182.0,88.0,3998.0,4788.0,88.0,-335.0,394.0,0.0,0.0,3.0,1.0,2.0,0.0,1.0,5931.0,8528.0,136.0,5265.0,6822.0,123.0,666.0,1706.0,13.0,2.0,6.0,1.0,2.0,0.0,3.0,7919.0,11264.0,194.0,7403.0,10065.0,181.0,516.0,1199.0,13.0,2.0,6.0,1.0,2.0,2.0,3.0,9607.0,13354.0,230.0,8976.0,14082.0,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26456,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,oe:player:c62a5235ad6bc113a1e64eb0e9aa8c8,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3,40,1.5047,12236,8707,327.5361,0.283289,11925,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26457,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,10,Red,sup,Labrov,oe:player:bb6ac5763c6576e104a7a2f59eb4ddf,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Rakan,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,0,2,9,12,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4537,170.6708,0.077377,507.0470,463.9749,0.0,47,1.7680,12,0.4514,11,105,3.9498,6496,2967,111.6113,0.096525,5920,NaN,NaN,24.0,24.0,0,NaN,NaN,0.9028,2504.0,1757.0,9.0,2550.0,2304.0,9.0,-46.0,-547.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0,3829.0,3936.0,15.0,3732.0,3230.0,19.0,97.0,706.0,-4.0,0.0,7.0,0.0,0.0,1.0,2.0,4971.0,4573.0,21.0,4980.0,4639.0,21.0,-9.0,-66.0,0.0,0.0,7.0,1.0,0.0,3.0,2.0,6161.0,6314.0,24.0,6268.0,7303.0,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26458,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,100,Blue,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Rumble,Maokai,Akali,Vi,Xayah,Alistar,Camille,Cassiopeia,1595,1,8,12,19,8,12,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3009,0.7524,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,7.0,1.0,1.0,1.0,25.0,12.0,1.0,0.0,57024,2145.1034,NaN,3055.0345,2666.2947,32895.0,102,3.8370,36,1.3542,28,254,9.5549,51682,34035,1280.3135,NaN,45223,-0.025218,-0.18,NaN,813.0,185,NaN,NaN,37.5423,17356.0,20681.0,372.0,17656.0,19713.0,330.0,-300.0,968.0,42.0,2.0,2.0,4.0,4.0,9.0,2.0,25357.0,31403.0,558.0,28580.0,34561.0,520.0,-3223.0,-3158.0,38.0,2.0,2.0,10.0,10.0,20.0,2.0,36649.0,45707.0,786.0,37537.0,46378.0,745.0,-888.0,-671.0,41.0,4.0,7.0,10.0,10.0,20.0,4.0,46187.0,62098.0,979.0,46122.0,57751.0,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26459,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26,252,9.4796,48381,30734,1156.1379,NaN,46378,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [25]:
df.isnull().sum().sort_values(ascending=False).head(20)

dragons (type unknown)     77970
monsterkillsownjungle      73440
monsterkillsenemyjungle    73440
url                        73440
elementaldrakes            66636
mountains                  66636
firstbaron                 66636
atakhans                   66636
clouds                     66636
hextechs                   66636
elders                     66636
opp_elders                 66636
firstherald                66636
opp_elementaldrakes        66636
infernals                  66636
opp_atakhans               66636
turretplates               66636
opp_turretplates           66636
gpr                        66636
firsttothreetowers         66636
dtype: int64

In [26]:
df['dragons (type unknown)'].isnull().sum()

np.int64(77970)

In [27]:
df = df.drop(columns=['dragons (type unknown)'])

In [28]:
df = df.drop(columns=['url'])

In [29]:
df.isnull().sum().sort_values(ascending=False).head(20)

monsterkillsenemyjungle    73440
monsterkillsownjungle      73440
infernals                  66636
atakhans                   66636
firstbaron                 66636
firsttothreetowers         66636
clouds                     66636
mountains                  66636
elders                     66636
opp_elders                 66636
firstherald                66636
hextechs                   66636
opp_elementaldrakes        66636
oceans                     66636
turretplates               66636
opp_atakhans               66636
gpr                        66636
opp_turretplates           66636
firstmidtower              66636
elementaldrakes            66636
dtype: int64

In [30]:
df = df.drop(columns=['atakhans'])

In [31]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'playerid',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [34]:
df['playerid'].sample()

54894    oe:player:7bcd2e0ffb1e417c2aa64d08675ed2b
Name: playerid, dtype: str

In [35]:
df['playerid'].sample(5)

60040    oe:player:99e732def3601275db892c84fb85a0c
40114                                          NaN
61498                                          NaN
52458    oe:player:9c51ed760409db6fa2a02fe8046f110
63900    oe:player:aad3806ef26a116c73b11efa07e9bd8
Name: playerid, dtype: str

In [37]:
df = df.drop(columns=['playerid'])

In [40]:
df['datacompleteness'].sample(100)

78269    complete
72958    complete
70755    complete
11397    complete
48966    complete
7540     complete
77264    complete
53397    complete
69795    complete
49023    complete
76188    complete
15372    complete
38887     partial
66232    complete
10143    complete
54691    complete
62619    complete
41406    complete
21756    complete
73039    complete
4194     complete
10463    complete
75811    complete
36985    complete
65469    complete
71691    complete
46072     partial
52146    complete
10722    complete
23909    complete
1876     complete
19316    complete
57247    complete
51429    complete
30967    complete
4670     complete
36638    complete
75283    complete
38265    complete
30030    complete
66412    complete
69325    complete
68725    complete
59694    complete
8632     complete
33016    complete
58585    complete
45402    complete
578       partial
40142    complete
32428    complete
12000    complete
54685    complete
70204    complete
58392    complete
22125    complete
24426    complete
5822     complete
34274    complete
36845    complete
6377     complete
65278    complete
59042    complete
5644      partial
69343    complete
56291    complete
77448    complete
23771    complete
40008    complete
59426    complete
9108     complete
9735     complete
38665    complete
40782    complete
25012    complete
11362    complete
50209    complete
56369    complete
75823    complete
59972    complete
8227     complete
695      complete
20863    complete
73633    complete
54541    complete
75756    complete
16402    complete
15529    complete
13327    complete
3295     complete
13029    complete
26705    complete
25561    complete
1376     complete
48099    complete
40645     partial
60983    complete
47183    complete
33520    complete
15491    complete
Name: datacompleteness, dtype: str

In [43]:
df['datacompleteness'].unique()

<StringArray>
['complete', 'partial']
Length: 2, dtype: str

In [44]:
df['datacompleteness'].value_counts()

datacompleteness
complete    73440
partial      5436
Name: count, dtype: int64

In [45]:
df = df[df['datacompleteness'] == 'complete']

In [46]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [47]:
df.info()

<class 'pandas.DataFrame'>
Index: 73440 entries, 0 to 78875
Columns: 161 entries, gameid to opp_deathsat25
dtypes: float64(120), int64(20), str(21)
memory usage: 90.8 MB

In [48]:
fst_df.info()

<class 'pandas.DataFrame'>
Index: 540 entries, 25524 to 26459
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(122), int64(20), str(23)
memory usage: 700.3 KB

In [49]:
fst._df.sample(15)

NameError: name 'fst' is not defined

In [50]:
fst_df.sample(15)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25868,LOLTMNT01_351208,complete,NaN,FST,2026,NaN,0,2026-03-20 13:10:12,1,16.05,9,Red,bot,Hans Sama,oe:player:c62a5235ad6bc113a1e64eb0e9aa8c8,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Ashe,Karma,Rumble,Ambessa,Kai'Sa,Ezreal,NaN,NaN,NaN,NaN,NaN,1908,1,9,2,8,22,6,2.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,0.6918,0.8805,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,23542,740.3145,0.270738,510.5975,329.8428,16938.0,14,0.4403,18,0.5660,4,60,1.8868,19200,15032,472.7044,0.312002,14600,NaN,NaN,335.0,309.0,26,NaN,NaN,10.5346,4024.0,3725.0,95.0,3137.0,3490.0,77.0,887.0,235.0,18.0,1.0,1.0,0.0,0.0,0.0,0.0,6601.0,5750.0,147.0,5329.0,6202.0,140.0,1272.0,-452.0,7.0,1.0,2.0,0.0,0.0,0.0,0.0,9044.0,7891.0,205.0,7826.0,9282.0,205.0,1218.0,-1391.0,0.0,2.0,3.0,1.0,0.0,1.0,0.0,13032.0,11611.0,259.0,10424.0,12364.0,272.0,2608.0,-753.0,-13.0,5.0,7.0,1.0,1.0,2.0,0.0
25698,LOLTMNT01_349576,complete,NaN,FST,2026,NaN,0,2026-03-17 18:11:55,4,16.05,7,Red,jng,YoungJae,oe:player:e5feef89d633a666eeaaf6392ca2fa9,LOUD,oe:team:658a021a796aa5501503220adb38cf4,1.0,Nocturne,Varus,Nami,Azir,Galio,Karma,NaN,NaN,NaN,NaN,NaN,1876,1,4,4,10,16,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5117,0.7996,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,15809,505.6183,0.193849,1299.4989,870.9915,4601.0,14,0.4478,11,0.3518,11,65,2.0789,14388,10285,328.9446,0.237736,13325,NaN,NaN,241.0,29.0,212,NaN,NaN,7.7079,3521.0,4145.0,81.0,3635.0,4806.0,90.0,-114.0,-661.0,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,5757.0,6463.0,114.0,5855.0,7644.0,131.0,-98.0,-1181.0,-17.0,1.0,2.0,2.0,1.0,3.0,1.0,7574.0,8703.0,140.0,7611.0,10384.0,172.0,-37.0,-1681.0,-32.0,2.0,3.0,3.0,1.0,4.0,1.0,10300.0,11857.0,186.0,9644.0,12696.0,208.0,656.0,-839.0,-22.0,3.0,5.0,4.0,2.0,5.0,1.0
26446,LOLTMNT01_351658,complete,NaN,FST,2026,NaN,0,2026-03-22 15:15:55,3,16.05,100,Blue,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Vi,Nocturne,Azir,Ashe,Xin Zhao,Seraphine,Mel,Jax,1695,1,17,5,44,17,5,2.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,0.6018,0.7788,0.0,3.0,1.0,3.0,1.0,2.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,9.0,1.0,1.0,1.0,35.0,12.0,2.0,0.0,117051,4143.3982,NaN,3837.0973,3236.3186,36768.0,95,3.3628,49,1.7345,32,299,10.5841,59911,41244,1459.9646,NaN,53853,0.208040,3.06,NaN,809.0,217,NaN,NaN,36.3186,16211.0,20696.0,379.0,15410.0,20881.0,353.0,801.0,-185.0,26.0,0.0,0.0,0.0,0.0,0.0,0.0,26877.0,33541.0,584.0,23678.0,32792.0,551.0,3199.0,749.0,33.0,3.0,6.0,0.0,0.0,0.0,3.0,38466.0,47611.0,794.0,32801.0,43602.0,722.0,5665.0,4009.0,72.0,6.0,16.0,1.0,1.0,3.0,6.0,49682.0,60929.0,911.0,42174.0,55919.0,851.0,7508.0,5010.0,60.0,12.0,31.0,5.0,5.0,14.0,12.0
25848,LOLTMNT01_352019,complete,NaN,FST,2026,NaN,0,2026-03-19 17:11:10,3,16.05,1,Blue,top,Xiaoxu,oe:player:8007ba25dee37ac1e4445a6e9f8d252,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,0.0,Jax,Orianna,Ryze,Qiyana,Galio,Trundle,NaN,NaN,NaN,NaN,NaN,1258,1,4,5,2,19,7,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9062,1.2401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,8513,406.0254,0.132993,918.6963,833.9905,2440.0,9,0.4293,0,0.0000,1,19,0.9062,8259,5417,258.3625,0.169642,7458,NaN,NaN,166.0,158.0,8,NaN,NaN,7.9173,3494.0,5060.0,83.0,3399.0,4971.0,84.0,95.0,89.0,-1.0,0.0,1.0,1.0,0.0,1.0,1.0,5372.0,8320.0,119.0,5987.0,8781.0,134.0,-615.0,-461.0,-15.0,1.0,2.0,3.0,2.0,1.0,2.0,7901.0,11128.0,159.0,7192.0,10945.0,166.0,709.0,183.0,-7.0,4.0,2.0,4.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25559,LOLTMNT01_349264,complete,NaN,FST,2026,NaN,0,2026-03-16 14:46:52,3,16.05,200,Red,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,NaN,Yunara,Twisted Fate,Gwen,Galio,Akali,Rumble,Wukong,Ahri,Zeri,Yuumi,1986,0,17,23,34,17,23,2.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,0.5136,1.2085,1.0,1.0,3.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,3.0,9.0,0.0,0.0,15.0,37.0,0.0,1.0,92208,2785.7402,NaN,3547.9758,3202.5982,8433.0,109,3.2931,58,1.7523,47,307,9.2749,65912,44277,1337.6737,NaN,64603,0.040154,0.49,NaN,970.0,207,NaN,NaN,35.5589,18178.0,21545.0,379.0,17274.0,21478.0,387.0,904.0,67.0,-8.0,4.0,5.0,2.0,2.0,2.0,4.0,26841.0,34156.0,597.0,27222.0,35260.0,616.0,-381.0,-1104.0,-19.0,4.0,5.0,3.0,3.0,4.0,4.0,37171.0,46488.0,786.0,38252.0,49361.0,818.0,-1081.0,-2873.0,-32.0,7.0,11.0,7.0,7.0,8.0,7.0,47228.0,57990.0,983.0,46197.0,61765.0,962.0,1031.0,-3775.0,21.0,9.0,16.0,8.0,8.0,10.0,9.0
25876,LOLTMNT01_351218,complete,NaN,FST,2026,NaN,0,2026-03-20 14:01:48,2,16.05,5,Blue,sup,Labrov,oe:player:bb6ac5763c6576e104a7a2f59eb4ddf,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Nami,Orianna,Ryze,Karma,Ezreal,Lucian,NaN,NaN,NaN,NaN,NaN,2187,1,4,7,22,28,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7682,1.3992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15751,432.1262,0.124712,671.5226,269.9588,1287.0,57,1.5638,21,0.5761,10,142,3.8957,11793,7056,193.5802,0.138864,10105,NaN,NaN,27.0,27.0,0,NaN,NaN,0.7407,2521.0,2498.0,8.0,2424.0,2546.0,11.0,97.0,-48.0,-3.0,0.0,1.0,0.0,0.0,1.0,0.0,4069.0,3650.0,10.0,4032.0,3561.0,17.0,37.0,89.0,-7.0,1.0,2.0,2.0,0.0,6.0,1.0,5179.0,4935.0,12.0,5594.0,4968.0,20.0,-415.0,-33.0,-8.0,1.0,3.0,4.0,1.0,8.0,1.0,6597.0,7559.0,18.0,7063.0,6908.0,22.0,-466.0,651.0,-4.0,1.0,7.0,4.0,1.0,10.0,2.0
25580,LOLTMNT01_349288,complete,NaN,FST,2026,NaN,0,2026-03-16 16:26:01,5,16.05,9,Red,bot,Diable,oe:player:178ec186b0d43d2669342596c2808cd,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,1.0,Jhin,Akali,Xin Zhao,Syndra,Elise,Bard,NaN,NaN,NaN,NaN,NaN,2055,0,2,2,4,16,25,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.4672,1.1971,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,18812,549.2555,0.247921,633.9562,510.1022,4475.0,20,0.5839,5,0.1460,8,34,0.9927,14880,10412,304.0000,0.284673,14750,NaN,NaN,369.0,357.0,12,NaN,NaN,10.7737,4036.0,4343.0,91.0,3541.0,4374.0,97.0,495.0,-31.0,-6.0,1.0,1.0,0.0,0.0,0.0,1.0,6243.0,6748.0,149.0,7816.0,7125.0,154.0,-1573.0,-377.0,-5.0,1.0,1.0,0.0,2.0,2.0,1.0,8569.0,9525.0,194.0,11537.0,9943.0,199.0,-2968.0,-418.0,-5.0,2.0,4.0,1.0,6.0,3.0,3.0,10728.0,12406.0,262.0,15416.0,12284.0,239.0,-4688.0,122.0,23.0,2.0,4.0,1.0,10.0,3.0,3.0
25535,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,200,Red,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,NaN,Azir,Karma,Rumble,Ezreal,Yunara,Ryze,Jarvan IV,Varus,Alistar,Jax,1779,1,29,9,62,29,9,5.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.9781,1.2816,1.0,2.0,2.0,2.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,9.0,1.0,1.0,1.0,39.0,11.0,1.0,0.0,83755,2824.7892,NaN,3330.3204,3667.1838,38211.0,130,4.3845,37,1.2479,42,307,10.3541,66623,47099,1588.4992,NaN,59028,0.102736,3.26,NaN,862.0,215,NaN,NaN,36.3238,18262.0,19893.0,334.0,17727.0,20028.0,336.0,535.0,-135.0,-2.0,7.0,8.0,4.0,4.0,5.0,7.0,28745.0,33045.0,548.0,26686.0,31546.0,540.0,2059.0,1499.0,8.0,10.0,14.0,5.0,5.0,7.0,10.0,42180.0,46792.0,755.0,36580.0,43656.0,731.0,5600.0,3136.0,24.0,16.0,33.0,7.0,7.0,13.0,16.0,54121.0,65225.0,944.0,44952.0,53823.0,914.0,9169.0,11402.0,30.0,22.0,45.0,7.0,7.0,13.0,22.0
25823,LOLTMNT01_350983,complete,NaN,FST,2026,NaN,0,2026-03-19 14:45:26,3,16.05,200,Red,team,NaN,NaN,LYON,oe:team:da1143bf9a245b78a8dc86417de85b3,0.0,NaN,Ryze,Rumble,Bard,Twisted Fate,Viktor,Nami,Wukong,Lucian,LeBlanc,Irelia,1507,0,8,30,13,8,30,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3185,1.5129,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,10.0,0.0,0.0,8.0,43.0,0.0,2.0,52029,2071.4930,NaN,4310.8029,2871.2409,4534.0,72,2.8666,25,0.9954,14,185,7.3656,43216,26467,1053.7624,NaN,41318,-0.284635,-5.21,NaN,656.0,161,NaN,NaN,32.5282,15363.0,19350.0,339.0,18794.0,21941.0,377.0,-3431.0,-2591.0,-38.0,0.0,0.0,5.0,5.0,2.0,0.0,24949.0,32869.0,540.0,31612.0,35395.0,568.0,-6663.0,-2526.0,-28.0,2.0,4.0,12.0,12.0,10.0,2.0,36005.0,46112.0,700.0,45291.0,49644.0,757.0,-9286.0,-3532.0,-57.0,7.0,11.0,20.0,20.0,21.0,7.0,43150.0,56666.0,817.0,58670.0,66757.0,879.0,-15520.0,-10091.0,-62.0,8.0,13.0,30.0,30.0,48.0,10.0
26175,LOLTMNT01_352425,complete,NaN,FST,2026,NaN,0,2026-03-21 14:58:22,3,16.05,4,Blue,bot,Hans Sama,oe:player:c62a5235ad6bc113a1e64eb0e9aa8c8,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Kog'Maw,Orianna,Ryze,Rumble,Nocturne,Wukong,NaN,NaN,NaN,NaN,NaN,1815,1,3,2,2,16,3,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5289,0.6281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,15074,498.3140,0.213341,426.3471,288.2314,7302.0,18,0.5950,12,0.3967,7,46,1.5207,14296,10318,341.0909,0.237431,13025,NaN,NaN,324.0,314.0,10,NaN,NaN,10.7107,3351.0,3408.0,95.0,3349.0,3239.0,91.0,2.0,169.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,5851.0,5756.0,150.0,6227.0,5659.0,151.0,-376.0,97.0,-1.0,1.0,0.0,0.0,0.0,1.0,0.0,8482.0,8625.0,214.0,8328.0,8170.0,208.0,154.0,455.0,6.0,1.0,0.0,0.0,0.0,1.0,0.0,10624.0,11025.0,272.0,10563.0,10693.0,266.0,61.0,332.0,6.0,1.0,1.0,1.0,0.0,2.0,1.0
25885,LOLTMNT01_351223,complete,NaN,FST,2026,NaN,0,2026-03-20 14:57:42,3,16.05,2,Blue,jng,SkewMond,oe:player:ab15060e5225b51592cd04b3aed1e09,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Pantheon,Orianna,Ryze,Karma,Gwen,Braum,NaN,NaN,NaN,NaN,NaN,1830,1,7,0,6,24,7,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7869,1.0164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15783,517.4754,0.188242,808.1639,1001.2459,2276.0,10,0.3279,9,0.2951,8,43,1.4098,13402,9393,307.9672,0.211330,11750,NaN,NaN,224.0,47.0,177,NaN,NaN,7.3443,3712.0,3752.0,68.0,3703.0,4166.0,81.0,9.0,-414.0,-13.0,1.0,0.0,0.0,0.0,2.0,1.0,5741.0,5656.0,98.0,5165.0,5982.0,115.0,576.0,-326.0,-17.0,3.0,2.0,0.0,0.0,2.0,3.0,8192.0,9065.0,142.0,6899.0,8943.0,152.0,1293.0,122.0,-10.0,5.0,2.0,0.0,0.0,3.0,3.0,10006.0,12184.0,167.0,8150.0,10505.0,174.0,1856.0,1679.0,-7.0,5.0,4.0,0.0,0.0,3.0,4.0
25710,LOLTMNT01_350498,complete,NaN,FST,2026,NaN,0,2026-03-17 19:04:16,5,16.05,7,Red,jng,YoungJae,oe:player:e5feef89d633a666eeaaf6392ca2fa9,LOUD,oe:team:658a021a796aa5501503220adb38cf4,0.0,Zaahen,Varus,Orianna,Azir,Annie,Kennen,NaN,NaN,NaN,NaN,NaN,2032,0,0,2,4,5,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1476,0.5906,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,10966,323.7992,0.172753,983.0906,729.6555,567.0,13,0.3839,26,0.7677,11,87,2.5689,11972,7551,222.9626,0.202869,10608,NaN,NaN,252.0,41.0,211,NaN,NaN,7.4409,3536.0,3999.0,82.0,3771.0,4580.0,86.0,-235.0,-581.0,-4.0,0.0,0.0,0.0,0.0,1.0,0.0,5435.0,6458.0,123.0,5814.0,7358.0,130.0,-379.0,-900.0,-7.0,0.0,1.0,0.0,1.0,1.0,0.0,7070.0,8717.0,159.0,7949.0,10331.0,179.0,-879.0,-1614.0,-20.0,0.0,1.0,0.0,1.0,1.0,0.0,8840.0,11224.0,194.0,10722.0,14317.0,233.0,-1882.0,-3093.0,-39.0,0.0,1.0,1.0,2.0,3.0,0.0
25540,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,5,Blue,sup,ON,oe:player:90651ebea9a35ec4e018c8157492e17,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Nami,Orianna,Rumble,Ashe,Trundle,Azir,NaN,NaN,NaN,NaN,NaN,1570,0,0,4,9,11,13,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4204,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,8634,329.9618,0.109821,591.0955,242.2166,276.0,45,1.7197,13,0.4968,12,102,3.8981,6699,3221,123.0955,0.098931,6715,NaN,NaN,21.0,21.0,0,NaN,NaN,0.8025,2397.0,2458.0,6.0,2304.0,2935.0,17.0,93.0,-477.0,-11.0,0.0,1.0,0.0,0.0,0.0,0.0,3878.0,3646.0,16.0,4089.0,4184.0,25.0,-211.0,-538.0,-9.0,0.0,4.0,2.0,1.0,2.0,0.0,5150.0,5470.0,19.0,5565.0,6059.0,28.0,-415.0,-589.0,-9.0,0.0,6.0,2.0,1.0,5.0,0.0,6495.0,7738.0,21.0,6812.0,7321.0,32.0,-317.0,417.0,-11.0,0.0,9.0,3.0,1.0,6.0,1.0
25774,LOLTMNT01_350716,complete,NaN,FST,2026,NaN,0,2026-03-18 16:36:59,2,16.05,100,Blue,team,NaN,NaN,Team Secret Whales,oe:team:740de582f50775c516c77ed7b923fd5,0.0,NaN,Ashe,Lulu,Rumble,Braum,Kai'Sa,Galio,Nautilus,Volibear,Corki,Naafiri,1622,0,12,22,25,12,22,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4439,1.2577,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,9.0,0.0,0.0,8.0,35.0,0.0,1.0,68724,2542.1948,NaN,4797.2256,5595.1665,6601.0,98,3.6252,34,1.2577,27,231,8.5450,45640,27718,1025.3268,NaN,43743,-0.167122,-1.78,NaN,704.0,159,NaN,NaN,31.9236,16781.0,20621.0,363.0,17177.0,21251.0,383.0,-396.0,-630.0,-20.0,2.0,1.0,2.0,2.0,0.0,2.0,26098.0,32477.0,523.0,26858.0,31736.0,544.0,-760.0,741.0,-21.0,7.0,11.0,6.0,6.0,11.0,7.0,35792.0,44515.0,709.0,38894.0,47038.0,751.0,-3102.0,-2523.0,-42.0,10.0,20.0,11.0,11.0,21.0,10.0,43211.0,52147.0,823.0,51979.0,63052.0,903.0,-8768.0,-10905.0,-80.0,12.0,25.0,19.0,19.0,41.0,13.0
25831,LOLTMNT01_351065,complete,NaN,FST,2026,NaN,0,2026-03-19 15:35:17,1,16.05,8,Red,mid,Envy,oe:player:a672b5bc1c212a6922418fad18734c1,LOUD,oe:team:658a021a796aa5501503220adb38cf4,0.0,Aurora,Orianna,Xin Zhao,Pantheon,Rek'Sai,Ahri,NaN,NaN,NaN,NaN,NaN,1756,0,4,1,0,6,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2050,0.5467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19933,681.0820,0.409723,649.0319,321.7654,6255.0,12,0.4100,2,0.0683,2,25,0.8542,10828,6970,238.1549,0.235043,10360,NaN,NaN,260.0,260.0,0,NaN,NaN,8.8838,3361.0,5145.0,93.0,4203.0,5351.0,102.0,-842.0,-206.0,-9.0,0.0,0.0,0.0,0.0,0.0,0.0,5165.0,8206.0,153.0,6507.0,8056.0,153.0,-1342.0,150.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,7996.0,11589.0,201.0,9586.0,11241.0,221.0,-1590.0,348.0,-20.0,3.0,0.0,0.0,0.0,0.0,0.0,9516.0,14633.0,249.0,12304.0,16023.0,294.0,-2788.0,-1390.0,-45.0,3.0,0.0,0.0,0.0,0.0,0.0

In [52]:
fst_df = df[df['league'] == 'FST']
fst_df

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25524,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0,28,0.9444,10807,6902,232.7825,0.196186,9150,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25525,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11,55,1.8550,12060,8155,275.0422,0.231800,11925,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25526,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3,22,0.7420,10726,6821,230.0506,0.193883,10500,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25527,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4,38,1.2816,13565,9660,325.8010,0.274577,14010,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25528,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11,127,4.2833,7548,3643,122.8668,0.103554,7675,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26455,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,8,Red,mid,Caps,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Viktor,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,3,1,7,12,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21737,817.6928,0.370717,466.1944,503.7743,4885.0,10,0.3762,8,0.3009,4,34,1.2790,9911,6382,240.0752,0.207640,8950,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8025,3663.0,5182.0,88.0,3998.0,4788.0,88.0,-335.0,394.0,0.0,0.0,3.0,1.0,2.0,0.0,1.0,5931.0,8528.0,136.0,5265.0,6822.0,123.0,666.0,1706.0,13.0,2.0,6.0,1.0,2.0,0.0,3.0,7919.0,11264.0,194.0,7403.0,10065.0,181.0,516.0,1199.0,13.0,2.0,6.0,1.0,2.0,2.0,3.0,9607.0,13354.0,230.0,8976.0,14082.0,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26456,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3,40,1.5047,12236,8707,327.5361,0.283289,11925,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26457,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,10,Red,sup,Labrov,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Rakan,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,0,2,9,12,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4537,170.6708,0.077377,507.0470,463.9749,0.0,47,1.7680,12,0.4514,11,105,3.9498,6496,2967,111.6113,0.096525,5920,NaN,NaN,24.0,24.0,0,NaN,NaN,0.9028,2504.0,1757.0,9.0,2550.0,2304.0,9.0,-46.0,-547.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0,3829.0,3936.0,15.0,3732.0,3230.0,19.0,97.0,706.0,-4.0,0.0,7.0,0.0,0.0,1.0,2.0,4971.0,4573.0,21.0,4980.0,4639.0,21.0,-9.0,-66.0,0.0,0.0,7.0,1.0,0.0,3.0,2.0,6161.0,6314.0,24.0,6268.0,7303.0,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26458,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,100,Blue,team,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Rumble,Maokai,Akali,Vi,Xayah,Alistar,Camille,Cassiopeia,1595,1,8,12,19,8,12,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3009,0.7524,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,7.0,1.0,1.0,1.0,25.0,12.0,1.0,0.0,57024,2145.1034,NaN,3055.0345,2666.2947,32895.0,102,3.8370,36,1.3542,28,254,9.5549,51682,34035,1280.3135,NaN,45223,-0.025218,-0.18,NaN,813.0,185,NaN,NaN,37.5423,17356.0,20681.0,372.0,17656.0,19713.0,330.0,-300.0,968.0,42.0,2.0,2.0,4.0,4.0,9.0,2.0,25357.0,31403.0,558.0,28580.0,34561.0,520.0,-3223.0,-3158.0,38.0,2.0,2.0,10.0,10.0,20.0,2.0,36649.0,45707.0,786.0,37537.0,46378.0,745.0,-888.0,-671.0,41.0,4.0,7.0,10.0,10.0,20.0,4.0,46187.0,62098.0,979.0,46122.0,57751.0,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26459,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26,252,9.4796,48381,30734,1156.1379,NaN,46378,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [53]:
fst_df.info()

<class 'pandas.DataFrame'>
Index: 540 entries, 25524 to 26459
Columns: 161 entries, gameid to opp_deathsat25
dtypes: float64(120), int64(20), str(21)
memory usage: 683.4 KB

In [54]:
fst_df.sample(540)

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25807,LOLTMNT01_350979,complete,FST,2026,NaN,0,2026-03-19 13:58:41,2,16.05,8,Red,mid,Saint,LYON,oe:team:da1143bf9a245b78a8dc86417de85b3,0.0,Ahri,Ryze,Rumble,Pantheon,Nami,Alistar,NaN,NaN,NaN,NaN,NaN,1554,0,1,2,2,9,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3475,1.0425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16852,650.6564,0.259469,666.3320,393.2819,4600.0,10,0.3861,6,0.2317,3,40,1.5444,10991,7545,291.3127,0.248647,11125,NaN,NaN,240.0,240.0,0,NaN,NaN,9.2664,3516.0,5326.0,91.0,3419.0,5286.0,96.0,97.0,40.0,-5.0,0.0,0.0,0.0,0.0,0.0,0.0,6573.0,8253.0,150.0,5276.0,7929.0,153.0,1297.0,324.0,-3.0,1.0,1.0,0.0,0.0,0.0,0.0,9211.0,11416.0,206.0,7342.0,10679.0,207.0,1869.0,737.0,-1.0,1.0,2.0,0.0,0.0,0.0,0.0,10879.0,13130.0,240.0,11035.0,15374.0,279.0,-156.0,-2244.0,-39.0,1.0,2.0,1.0,1.0,5.0,0.0
25914,LOLTMNT01_351251,complete,FST,2026,NaN,0,2026-03-20 16:45:05,2,16.05,7,Red,jng,Inspired,LYON,oe:team:da1143bf9a245b78a8dc86417de85b3,0.0,Malphite,Seraphine,Ryze,Vi,Nautilus,Rakan,NaN,NaN,NaN,NaN,NaN,2462,1,2,2,7,13,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3168,0.7555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12294,299.6101,0.119532,880.7474,1884.9066,1205.0,17,0.4143,19,0.4630,15,78,1.9009,15710,10412,253.7449,0.202045,13425,NaN,NaN,292.0,26.0,266,NaN,NaN,7.1162,3543.0,4277.0,83.0,3269.0,3871.0,72.0,274.0,406.0,11.0,0.0,0.0,0.0,0.0,0.0,0.0,5247.0,6905.0,125.0,5025.0,6160.0,115.0,222.0,745.0,10.0,0.0,0.0,0.0,0.0,0.0,0.0,7149.0,9733.0,173.0,8183.0,8941.0,156.0,-1034.0,792.0,17.0,0.0,0.0,0.0,3.0,0.0,0.0,8649.0,11880.0,204.0,11228.0,13183.0,203.0,-2579.0,-1303.0,1.0,0.0,0.0,1.0,5.0,3.0,0.0
25537,LOLTMNT01_350155,complete,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,2,Blue,jng,Xun,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Pantheon,Orianna,Rumble,Ashe,Trundle,Azir,NaN,NaN,NaN,NaN,NaN,1570,0,4,3,3,11,13,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4204,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,13947,533.0064,0.177400,984.5732,802.0127,0.0,5,0.1911,5,0.1911,3,25,0.9554,9792,6314,241.2994,0.193942,9225,NaN,NaN,161.0,8.0,153,NaN,NaN,6.1529,3391.0,3661.0,63.0,3181.0,3783.0,72.0,210.0,-122.0,-9.0,0.0,2.0,0.0,0.0,0.0,0.0,5619.0,6224.0,99.0,4753.0,6202.0,113.0,866.0,22.0,-14.0,2.0,2.0,0.0,0.0,0.0,1.0,8003.0,8583.0,132.0,7323.0,8354.0,139.0,680.0,229.0,-7.0,4.0,2.0,1.0,1.0,2.0,2.0,9650.0,11514.0,161.0,9444.0,11169.0,175.0,206.0,345.0,-14.0,4.0,3.0,2.0,2.0,3.0,2.0
25795,LOLTMNT01_351028,complete,FST,2026,NaN,0,2026-03-19 13:11:55,1,16.05,8,Red,mid,Chovy,Gen.G,oe:team:50f58982d91a36557ec8aec52ab014f,1.0,Orianna,Karma,Pantheon,Rumble,Akali,Gnar,NaN,NaN,NaN,NaN,NaN,1528,1,6,0,8,17,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6675,0.7853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,25222,990.3927,0.310104,252.0942,221.1518,7332.0,10,0.3927,3,0.1178,1,22,0.8639,11588,8195,321.7932,0.223314,10175,NaN,NaN,252.0,246.0,6,NaN,NaN,9.8953,3959.0,5440.0,104.0,3132.0,4996.0,75.0,827.0,444.0,29.0,1.0,0.0,0.0,0.0,0.0,0.0,5745.0,8113.0,158.0,4601.0,7490.0,114.0,1144.0,623.0,44.0,1.0,0.0,0.0,0.0,1.0,0.0,8633.0,10553.0,205.0,6148.0,9272.0,147.0,2485.0,1281.0,58.0,3.0,1.0,0.0,0.0,1.0,1.0,11294.0,14169.0,250.0,8338.0,11470.0,187.0,2956.0,2699.0,63.0,6.0,8.0,0.0,1.0,1.0,3.0
25892,LOLTMNT01_351223,complete,FST,2026,NaN,0,2026-03-20 14:57:42,3,16.05,9,Red,bot,Diable,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,1.0,Varus,Ambessa,Ziggs,Bard,Aurora,Annie,NaN,NaN,NaN,NaN,NaN,1830,0,4,5,0,7,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2295,1.0164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19040,624.2623,0.233328,551.5738,259.0492,1392.0,16,0.5246,7,0.2295,6,33,1.0820,12058,8049,263.9016,0.246787,11650,NaN,NaN,256.0,256.0,0,NaN,NaN,8.3934,3630.0,3852.0,87.0,3854.0,3886.0,96.0,-224.0,-34.0,-9.0,1.0,0.0,0.0,1.0,1.0,1.0,5669.0,6500.0,146.0,6832.0,6616.0,142.0,-1163.0,-116.0,4.0,1.0,0.0,1.0,2.0,6.0,1.0,7950.0,8671.0,194.0,9544.0,9656.0,207.0,-1594.0,-985.0,-13.0,2.0,0.0,2.0,2.0,8.0,1.0,10141.0,10545.0,236.0,13046.0,12555.0,262.0,-2905.0,-2010.0,-26.0,3.0,0.0,3.0,4.0,10.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25654,LOLTMNT01_349529,complete,FST,2026,NaN,0,2026-03-17 14:43:27,3,16.05,100,Blue,team,NaN,Gen.G,oe:team:50f58982d91a36557ec8aec52ab014f,0.0,NaN,Orianna,Karma,Ryze,Wukong,Jax,Ambessa,Hwei,Nocturne,Alistar,Jhin,1794,1,15,9,26,15,9,2.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,0.5017,0.8027,0.0,3.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,8.0,2.0,1.0,1.0,36.0,14.0,1.0,0.0,85895,2872.7425,NaN,3456.1538,3247.9933,35161.0,121,4.0468,36,1.2040,31,270,9.0301,61116,41439,1385.9197,NaN,53000,0.047795,0.35,NaN,876.0,236,NaN,NaN,37.1906,16814.0,20342.0,347.0,17545.0,21264.0,375.0,-731.0,-922.0,-28.0,2.0,3.0,3.0,3.0,2.0,2.0,26621.0,33813.0,583.0,25769.0,33441.0,573.0,852.0,372.0,10.0,3.0,4.0,3.0,3.0,2.0,3.0,35764.0,43677.0,751.0,36494.0,45393.0,743.0,-730.0,-1716.0,8.0,3.0,4.0,7.0,7.0,13.0,3.0,48095.0,61509.0,939.0,44669.0,55390.0,908.0,3426.0,6119.0,31.0,9.0,17.0,8.0,8.0,15.0,9.0
26219,LOLTMNT01_352471,complete,FST,2026,NaN,0,2026-03-21 17:36:53,3,16.05,200,Red,team,NaN,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,NaN,Gwen,Pantheon,Lulu,LeBlanc,Akali,Seraphine,Olaf,Senna,Tryndamere,Hwei,2217,0,9,22,22,9,22,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.2436,0.8390,1.0,2.0,4.0,2.0,4.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,1.0,9.0,0.0,0.0,8.0,39.0,0.0,1.0,103988,2814.2896,NaN,4141.9756,4105.0609,8583.0,136,3.6806,58,1.5697,35,353,9.5535,67697,43706,1182.8417,NaN,65055,-0.107532,-2.14,NaN,1088.0,226,NaN,NaN,35.5616,16101.0,20804.0,363.0,18173.0,21642.0,354.0,-2072.0,-838.0,9.0,0.0,0.0,5.0,5.0,7.0,0.0,25274.0,32380.0,562.0,27468.0,33687.0,555.0,-2194.0,-1307.0,7.0,1.0,2.0,6.0,6.0,9.0,1.0,34498.0,44788.0,778.0,37892.0,47404.0,785.0,-3394.0,-2616.0,-7.0,2.0,4.0,7.0,7.0,9.0,2.0,43871.0,56745.0,955.0,49934.0,63799.0,949.0,-6063.0,-7054.0,6.0,4.0,9.0,12.0,12.0,20.0,4.0
25568,LOLTMNT01_349281,complete,FST,2026,NaN,0,2026-03-16 15:40:05,4,16.05,9,Red,bot,Viper,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,Sivir,Twisted Fate,Lucian,Gwen,Dr. Mundo,Viktor,NaN,NaN,NaN,NaN,NaN,1524,1,9,1,6,20,4,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.7874,0.9449,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,33460,1317.3228,0.412755,492.2441,411.2992,10709.0,16,0.6299,11,0.4331,6,35,1.3780,14838,11453,450.9055,0.289483,10350,NaN,NaN,272.0,265.0,7,NaN,NaN,10.7087,3432.0,3655.0,93.0,3470.0,3883.0,93.0,-38.0,-228.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,6164.0,5982.0,146.0,6043.0,5868.0,134.0,121.0,114.0,12.0,1.0,2.0,1.0,1.0,1.0,2.0,9296.0,8962.0,216.0,8239.0,8208.0,194.0,1057.0,754.0,22.0,2.0,2.0,1.0,1.0,1.0,2.0,14107.0,12588.0,267.0,10837.0,10267.0,245.0,3270.0,2321.0,22.0,7.0,6.0,1.0,2.0,1.0,4.0
25898,LOLTMNT01_351241,complete,FST,2026,NaN,0,2026-03-20 15:53:55,1,16.05,3,Blue,mid,HongQ,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,Orianna,Pantheon,Rumble,Ryze,Bard,Rakan,NaN,NaN,NaN,NaN,NaN,1801,1,0,2,5,6,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1999,0.4664,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12386,412.6374,0.217512,403.2760,269.4170,8567.0,22,0.7329,6,0.1999,11,53,1.7657,11316,7366,245.3970,0.194940,9625,NaN,NaN,284.0,284.0,0,NaN,NaN,9.4614,3308.0,5043.0,92.0,3559.0,5359.0,82.0,-251.0,-316.0,10.0,0.0,0.0,1.0,0.0,2.0,0.0,5056.0,7386.0,143.0,5191.0,7820.0,135.0,-135.0,-434.0,8.0,0.0,0.0,1.0,0.0,2.0,0.0,7058.0,10022.0,203.0,7835.0,11383.0,202.0,-777.0,-1361.0,1.0,0.0,0.0,2.0,0.0,3.0,0.0,8714.0,12277.0,250.0,8995.0,12820.0,225.0,-281.0,-543.0,25.0,0.0,0.0,2.0,0.0,3.0,0.0
26176,LOLTMNT01_352425,complete,FST,2026,NaN,0,2026-03-21 14:58:22,3,16.05,5,Blue,sup,Labrov,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Lulu,Orianna,Ryze,Rumble,Nocturne,Wukong,NaN,NaN,NaN,NaN,NaN,1815,1,0,1,11,16,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5289,0.6281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5020,165.9504,0.071047,367.4050,205.6860,1197.0,59,1.9504,15,0.4959,14,122,4.0331,8554,4576,151.2727,0.105297,7595,NaN,NaN,23.0,23.0,0,NaN,NaN,0.7603,2248.0,2992.0,5.0,2322.0,3115.0,4.0,-74.0,-123.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3438.0,4131.0,9.0,3488.0,4173.0,9.0,-50.0,-42.0,0.0,0.0,1.0,1.0,0.0,1.0,1.0,4865.0,5566.0,14.0,4509.0,4961.0,13.0,356.0,605.0,1.0,0.0,2.0,1.0,0.0,1.0,2.0,6375.0,8217.0,18.0,5925.0,6039.0,25.0,450.0,2178.0,-7.0,0.0,6.0,1.0,0.0,2.0,3.0

In [55]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [56]:
df['result'].unique()

array([0, 1])

In [57]:
df['result'].count()

np.int64(73440)