In [203]:
import pandas as pd
print(pd.__version__)

3.0.5

In [204]:
df = pd.read_csv('../2026_LoL_esports_match_data_from_OraclesElixir.csv')
df.shape

C:\Users\ummmi\AppData\Local\Temp\ipykernel_27544\1497733276.py:1: DtypeWarning: Columns (0: url) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('../2026_LoL_esports_match_data_from_OraclesElixir.csv')

(111972, 165)

In [205]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111156.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,110364.000000,110364.000000,110316.000000,110316.000000,110616.000000,93230.000000,91930.000000,91930.000000,111972.000000,111972.000000,18642.000000,18662.000000,18662.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,276.000000,18394.000000,18394.000000,18378.000000,18662.000000,18662.000000,18662.000000,18662.000000,18252.000000,96532.000000,96532.000000,15574.0,15574.0,18644.000000,18662.000000,18662.000000,18384.000000,18404.000000,18394.000000,18394.000000,96532.000000,96532.000000,111972.000000,111972.000000,93310.000000,111972.000000,110364.000000,110364.000000,111972.000000,111972.000000,111972.000000,111972.000000,111900.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,93310.000000,111900.000000,18650.000000,18394.000000,93310.000000,110582.000000,111972.000000,1656.000000,1656.000000,110582.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.00000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000
mean,2026.010824,0.216911,1.833887,16.097154,29.583333,0.500000,1888.895402,0.500000,5.522523,5.533187,11.900868,16.567570,16.599561,0.580407,0.099507,0.015682,0.003263,0.271579,0.099989,0.125519,0.100000,0.534753,1.069506,0.499625,2.202497,2.202497,2.158856,2.158856,0.365119,0.354735,0.359683,0.360607,0.362781,0.355931,2.217391,0.043656,0.043656,0.490641,0.489872,0.489872,1.475619,1.475619,0.480934,0.241930,0.241930,0.0,0.0,0.500000,5.910781,5.910781,0.500000,0.499348,25.842666,25.842666,0.295208,0.295208,30597.951095,964.528301,0.200000,1246.383997,1201.843655,8695.381737,34.974887,1.098982,14.353642,0.445808,11.634602,94.621361,2.962315,20538.249455,13656.746740,434.122844,0.200000,18945.941966,0.000000,0.000000,216.163691,282.720244,69.566517,52.416063,5.844203,11.161138,5670.962542,6775.172054,117.874637,5670.962542,6775.172054,117.874637,0.000000,0.000000,0.000000,0.870284,1.219018,0.874365,0.870284,1.219018,0.874365,8887.911253,10905.720390,182.778104,8887.911253,10905.720390,182.778104,0.000000,0.000000,0.000000,1.672108,2.579660,1.677694,1.672108,2.579660,1.677694,12357.667321,15157.251109,246.922973,12357.667321,15157.251109,246.922973,0.000000,0.000000,0.000000,2.614031,4.562177,2.620647,2.614031,4.562177,2.620647,15724.795902,19490.706613,301.812668,15724.795902,19490.706613,301.812668,0.00000,0.000000,0.000000,3.627052,7.117207,3.634480,3.627052,7.117207,3.634480
std,0.106537,0.412144,0.954467,0.053786,57.650725,0.500002,330.836815,0.500002,6.587198,6.300329,13.949761,8.214425,8.214491,1.059289,0.347163,0.128194,0.058755,0.444776,0.299987,0.331309,0.300002,0.284398,0.330353,0.500013,1.395557,1.395557,1.352386,1.352386,0.659583,0.648799,0.648547,0.655168,0.656372,0.648647,1.260529,0.217480,0.217480,0.499926,0.500018,0.500018,1.339974,1.339974,0.499650,0.530375,0.530375,0.0,0.0,0.500013,3.675539,3.675539,0.500014,0.500013,12.784533,12.784533,0.640917,0.640917,31420.645337,945.376526,0.087911,1175.304107,1240.577940,10308.687176,38.228752,1.143552,15.519361,0.454390,13.349856,98.155472,2.912288,19290.350979,13118.730067,406.338544,0.061517,17801.349388,0.135028,2.394592,107.403089,284.296111,96.113297,72.399447,10.142424,10.425424,5115.009895,6137.072924,109.442461,5115.009895,6137.072924,109.442461,812.999226,636.417626,16.382822,1.394486,2.019687,1.357925,1.394486,2.019687,1.357925,8039.469095,9902.049726,169.756602,8039.469095,9902.049726,169.756602,1571.043562,1316.458569,25.334059,2.337384,3.605775,2.263780,2.337384,3.605775,2.263780,11203.390144,13759.594239,229.828998,11203.390144,13759.594239,229.828998,2451.969892,2076.536157,32.804459,3.424478,5.874698,3.306390,3.424478,5.874698,3.306390,14275.338053,17709.746946,281.335018,14275.338053,17709.746946,281.335018,3301.19197,3488.126589,37.736868,4.531256,8.726760,4.358712,4.531256,8.726760,4.358712
min,2025.000000,0.000000,1.000000,15.240000,1.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.247600,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,619.000000,23.807700,0.013642,29.518700,10.154300,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.045600,3698.000000,1299.000000,49.961500,0.051677,3150.000000,-0.486885,-9.340000,7.000000,0.000000,0.000000,0.000000,0.000000,0.257900,1909.000000,854.000000,1.000000,1909.000000,854.000000,1.000000,-8762.000000,-6305.000000,-155.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2979.000000,1998.000000,3.000000,2979.000000,1998.000000,3.000000,-14704.000000,-12451.000000,-233.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3842.000000,2495.000000,4.000000,3842.000000,2495.000000,4.000000,-20232.000000,-18841.000000,-266.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4604.000000,3090.000000,7.000000,4604.000000,3090.000000,7.000000,-22049.00000,-22919.000000,-301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.000000,0.000000,1.000000,16.060000,3.750000,0.000000,1649.000000,0.000000,1.000000,2.000000,4.000000,10.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.318100,0.834100,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,2.000000,2.000000,0.000000,0.000000,15.000000,15.000000,0.000000,0.000000,11785.000000,395.795750,0.133229,570.607500,384.328250,1402.000000,10.000000,0.335675,5.000000,0.159075,3.000000,33.000000,1.090900,10182.000000,6239.000000,210.814450,0.165224,9375.000000,-0.095788,-1.660000,175.000000,35.000000,0.000000,0.000000,0.000000,6.569100,3237.000000,3558.000000,71.000000,3237.000000,3558.000000,71.000000,-373.000000,-327.000000,-8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4957.000000,5823.000000,110.000000,4957.000000,5823.000000,110.000000,-652.000000,-607.000000,-12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6829.000000,8313.000000,147.000000,6829.000000,8313.000000,147.000000,-998.000000,-918.000000,-15.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,8592.000000,10664.000000,178.000000,8592.000000,10664.000000,178.000000,-1360.00000,-1488.000000,-18.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2026.000000,0.000000,2.000000,16.090000,6.500000,0.500000,1859.000000,0.500000,3.000000,4.000000,7.000000,16.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.497600,1.033600,0.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,0.500000,7.000000,7.000000,0.500000,0.000000,25.000000,25.000000,0.000000,0.000000,19492.500000,632.692150,0.202591,778.064450,706.920950,5260.000000,15.000000,0.458900,9.000000,0.282900,6.000000,50.000000,1.512700,12984.000000,8869.000000,281.701450,0.204273,11958.000000,0.000000,0.000000,238.000000,244.000000,4.000000,4.000000,0.000000,8.338700,3575.000000,4480.000000,85.000000,3575.000000,4480.000000,85.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5623.000000,7182.000000,133.000000,5623.000000,7182.000000,133.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7844.000000,9946.000000,181.000000,7844.000000,9946.000000,181.000000,0.000000,0.000000,0.000000,1.000000,3.000000,2.000000,1.000000,3.000000,2.000000,9985.000000,12696.000000,221.000000,9985.000000,12696.000000,221.000000,0.00000,0.000000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2026.000000,0.000000,2.000000,16.150000,9.250000,1.000000,2085.000000,1.000000,7.000000,6.000000,13.000000,22.000000,22.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.707600,1.256700,1.000000,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3.000000,3.000000,1.000000,0.000000,0.000000,0.0,0.0,1.000000,9.000000,9.000000,1.000000,1.000000,38.000000,38.000000,0.000000,0.000000,31826.000000,968.456350,0.262569,1131.274175,1368.522325,11374.000000,54.000000,1.778700,16.000000,0.496925,14.000000,120.000000,3.863175,16939.250000,12336.000000,379.988650,0.240507,15590.000000,0.095788,1.660000,287.000000,320.000000,171.000000,135.000000,8.000000,9.908300,4049.000000,5277.000000,99.000000,4049.000000,5277.000000,99.000000,373.000000,327.000000,8.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,6533.000000,8690.000000,153.000000,6533.000000,8690.000000,153.000000,652.000000,607.000000,12.000000,2.000000,3.000000,2.000000,2.000000,3.000000,2.000000,9227.000000,11890.250000,209.000000,9227.000000,11890.250000,209.000000,998.000000,918.000000,15.000000,3.000000,5.000000,3.000000,3.000000,5.000000,3.000000,11881.000000,15118.000000,258.000000,11881.000000,15118.000000,258.000000,1360.00000,1488.000000,18.000000,5.000000,8.000000,4.000000,5.000000,8.000000,4.000000
max,2027.000000,1.000000,5.000000,16.180000,200.000000,1.000000,3657.000000,1.000000,54.000000,54.000000,122.000000,54.000000,54.000000,18.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.095000,2.807300,1.000000,8.000000,8.000000,6.000000,6.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,1.000000,2.000000,2.000000,6.000000,6.000000,1.000000,4.000000,4.000000,0.0,0.0,1.000000,18.000000,18.000000,1.000000,1.000000,45.000000,45.000000,10.000000,10.000000,367979.000000,6291.486900,0.554940,7334.339600,11158.123600,53929.000000,260.000000,5.263600,131.000000,2.752000,110.000000,749.000000,14.276400,123556.000000,87467.000000,2009.340000,0.443045,128590.000000,0.486885,9.340000,636.000000,1635.000000,442.000000,240.000000,58.000000,45.199300,23163.000000,23646.000000,425.000000,23163.000000,23646.000000,425.000000,8762.000000,6305.000000,155.000000,16.000000,25.000000,16.000000,16.000000,25.000000,16.000000,37358.000000,38749.000000,665.000000,37358.000000,38749.000000,665.000000,14704.000000,12451.000000,233.000000,29.000000,41.000000,29.000000,29.000000,41.000000,29.000000,52772.000000,56167.000000,899.000000,52772.000000,56167.000000,899.000000,20232.000000,18841.000000,266.000000,41.000000,73.000000,41.000000,41.000000,73.000000,41.000000,64509.000000,76298.000000,1132.000000,64509.000000,76298.000000,1132.000000,22049.00000,22919.000000,301.000000,44.000000,88.000000,44.000000,44.000000,88.000000,44.000000

In [206]:
df.shape

(111972, 165)

In [207]:
df.columns.tolist()
df.head()

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,13057-13057_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=13057,DCup,2025,Season,0,2026-01-01 09:14:49,1,15.24,1,Blue,top,sheer,oe:player:3ce68cf813bc34243279fd7fe3cecbb,LNG Esports,oe:team:a9145b7711873f53e610fbba0493484,1.0,Sion,Qiyana,Neeko,Xin Zhao,Rek'Sai,Alistar,NaN,NaN,NaN,NaN,NaN,2278,0,2,4,7,13,22,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.3424,0.9219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25655,675.7243,0.290739,1385.4522,NaN,NaN,13,0.3424,8,0.2107,8.0,40,1.0536,14517,9594,252.6953,0.191120,14004.0,NaN,NaN,312.0,312.0,0,0.0,0.0,8.2177,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,13057-13057_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=13057,DCup,2025,Season,0,2026-01-01 09:14:49,1,15.24,2,Blue,jng,Croco,oe:player:5c6f901a83ec448d51703aebba0ca64,LNG Esports,oe:team:a9145b7711873f53e610fbba0493484,1.0,Wukong,Qiyana,Neeko,Xin Zhao,Rek'Sai,Alistar,NaN,NaN,NaN,NaN,NaN,2278,0,2,4,6,13,22,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.3424,0.9219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,9796,258.0158,0.111010,1094.0123,NaN,NaN,12,0.3161,16,0.4214,11.0,62,1.6330,14548,9625,253.5119,0.191737,13332.0,NaN,NaN,241.0,22.0,219,183.0,0.0,6.3477,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,13057-13057_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=13057,DCup,2025,Season,0,2026-01-01 09:14:49,1,15.24,3,Blue,mid,BuLLDoG,oe:player:317aeb74a6dd16bea711bbad361ca44,LNG Esports,oe:team:a9145b7711873f53e610fbba0493484,1.0,Ahri,Qiyana,Neeko,Xin Zhao,Rek'Sai,Alistar,NaN,NaN,NaN,NaN,NaN,2278,0,3,4,9,13,22,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.3424,0.9219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22689,597.6032,0.257121,525.8560,NaN,NaN,9,0.2371,18,0.4741,5.0,49,1.2906,17286,12363,325.6277,0.246279,15454.0,NaN,NaN,355.0,355.0,0,0.0,0.0,9.3503,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,13057-13057_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=13057,DCup,2025,Season,0,2026-01-01 09:14:49,1,15.24,4,Blue,bot,1xn,oe:player:d2b317a92a71a850ae3da1e0d83e883,LNG Esports,oe:team:a9145b7711873f53e610fbba0493484,1.0,Yunara,Qiyana,Neeko,Xin Zhao,Rek'Sai,Alistar,NaN,NaN,NaN,NaN,NaN,2278,0,5,5,6,13,22,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.3424,0.9219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22848,601.7910,0.258919,573.5558,NaN,NaN,12,0.3161,25,0.6585,4.0,53,1.3960,19143,14220,374.5391,0.283270,18574.0,NaN,NaN,353.0,349.0,4,4.0,0.0,9.2976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,13057-13057_game_1,partial,https://lpl.qq.com/es/stats.shtml?bmid=13057,DCup,2025,Season,0,2026-01-01 09:14:49,1,15.24,5,Blue,sup,MISSING,oe:player:10d1208b485425756fcc932229386b0,LNG Esports,oe:team:a9145b7711873f53e610fbba0493484,1.0,Braum,Qiyana,Neeko,Xin Zhao,Rek'Sai,Alistar,NaN,NaN,NaN,NaN,NaN,2278,0,1,5,9,13,22,NaN,NaN,NaN,NaN,NaN,0.0,NaN,NaN,0.3424,0.9219,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7254,191.0623,0.082211,761.0623,NaN,NaN,88,2.3178,8,0.2107,23.0,136,3.5821,9320,4397,115.8121,0.087595,9075.0,NaN,NaN,32.0,32.0,0,0.0,0.0,0.8428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [208]:
df.sample(10)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
60484,LOLTMNT05_196110,complete,NaN,LIT,2026,Spring,0,2026-05-23 18:14:58,2,16.10,5,Blue,sup,Pinguino,oe:player:2d3d09f928dbf1e6732b3b25e2f7969,P11 Esports,oe:team:51815048971b363597530c6d350a27f,1.0,Milio,Cho'Gath,Draven,Pyke,Jarvan IV,Gnar,NaN,NaN,NaN,NaN,NaN,2354,0,0,4,8,11,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2804,0.7647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7540,192.1835,0.090990,367.0603,213.3135,1809.0,52,1.3254,16,0.4078,13.0,132,3.3645,9445,4367,111.3084,0.103506,8575.0,NaN,NaN,41.0,41.0,0,NaN,NaN,1.0450,2581.0,3335.0,22.0,2456.0,2965.0,12.0,125.0,370.0,10.0,0.0,2.0,0.0,0.0,3.0,0.0,3693.0,4745.0,25.0,3805.0,4849.0,21.0,-112.0,-104.0,4.0,0.0,3.0,2.0,0.0,5.0,0.0,4930.0,6410.0,26.0,5130.0,6739.0,25.0,-200.0,-329.0,1.0,0.0,6.0,3.0,0.0,6.0,1.0,6142.0,8151.0,29.0,6078.0,8109.0,25.0,64.0,42.0,4.0,0.0,6.0,3.0,0.0,6.0,2.0
50558,LOLTMNT01_378170,complete,NaN,LCK,2026,Rounds 1-2,0,2026-05-07 11:22:31,2,16.09,3,Blue,mid,Roamer,oe:player:ea58943d300b14d684bb05b3975fe15,HANJIN BRION,oe:team:b77b3f6068e20a2b3edc0ecd3dc70d4,1.0,Aurora,Varus,Caitlyn,Lee Sin,Vayne,Akali,NaN,NaN,NaN,NaN,NaN,2071,1,3,4,8,19,15,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5505,0.9850,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,27293,790.7195,0.281418,795.7315,437.1222,6542.0,11,0.3187,11,0.3187,7.0,47,1.3617,12388,7888,228.5273,0.171675,11825.0,NaN,NaN,262.0,262.0,0,NaN,NaN,7.5905,3355.0,5118.0,97.0,3906.0,5154.0,88.0,-551.0,-36.0,9.0,0.0,0.0,0.0,2.0,0.0,0.0,5047.0,7500.0,145.0,5810.0,8373.0,151.0,-763.0,-873.0,-6.0,0.0,0.0,1.0,2.0,1.0,0.0,6110.0,9186.0,172.0,8365.0,11221.0,197.0,-2255.0,-2035.0,-25.0,0.0,0.0,3.0,4.0,5.0,0.0,7543.0,11436.0,214.0,10778.0,14159.0,254.0,-3235.0,-2723.0,-40.0,0.0,0.0,4.0,5.0,5.0,0.0
44490,LOLTMNT02_392124,complete,NaN,PCS,2026,Spring,0,2026-04-28 10:00:11,2,16.08,7,Red,jng,Cedric,oe:player:43f39bea1fd508368a1a6745c8fe646,Shadow Keepers Esports,oe:team:f35108ed5676ca98cb22aea66e5d7d7,0.0,Jarvan IV,Rumble,Karma,Vi,Wukong,Gnar,NaN,NaN,NaN,NaN,NaN,1822,0,5,4,13,22,27,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7245,1.6136,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16305,536.9374,0.152902,947.4533,1292.5686,520.0,9,0.2964,11,0.3622,9.0,50,1.6465,12158,8166,268.9133,0.207075,11350.0,NaN,NaN,212.0,30.0,182,NaN,NaN,6.9813,4466.0,3951.0,73.0,3995.0,3993.0,73.0,471.0,-42.0,0.0,3.0,2.0,1.0,2.0,1.0,2.0,6484.0,6692.0,105.0,6263.0,6399.0,105.0,221.0,293.0,0.0,3.0,9.0,2.0,4.0,3.0,3.0,9019.0,9600.0,144.0,7889.0,8604.0,142.0,1130.0,996.0,2.0,5.0,11.0,2.0,4.0,3.0,4.0,10543.0,12512.0,177.0,9476.0,10870.0,170.0,1067.0,1642.0,7.0,5.0,12.0,2.0,4.0,5.0,4.0
39690,LOLTMNT04_158016,complete,NaN,NL,2026,NaN,0,2026-04-19 10:18:09,1,16.07,7,Red,jng,Frost,oe:player:9f123d50225f8efc664774485f85941,Project Conquerors,oe:team:ad003d7f74930eeab29a6029c3b9f52,0.0,Zaahen,Karma,Ambessa,Orianna,Nautilus,Ezreal,NaN,NaN,NaN,NaN,NaN,1520,1,8,1,9,26,4,1.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0263,1.1842,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,22460,886.5789,0.241849,1593.0395,1125.3553,4561.0,7,0.2763,11,0.4342,4.0,49,1.9342,11859,8483,334.8553,0.211346,11483.0,NaN,NaN,201.0,24.0,177,NaN,NaN,7.9342,3929.0,4562.0,83.0,3287.0,3852.0,73.0,642.0,710.0,10.0,1.0,2.0,0.0,0.0,0.0,3.0,5989.0,7122.0,122.0,5779.0,6117.0,102.0,210.0,1005.0,20.0,2.0,4.0,0.0,1.0,1.0,4.0,8642.0,9468.0,157.0,7397.0,8552.0,142.0,1245.0,916.0,15.0,4.0,6.0,0.0,1.0,1.0,5.0,11718.0,13728.0,201.0,8529.0,9750.0,157.0,3189.0,3978.0,44.0,8.0,9.0,0.0,1.0,1.0,8.0
10384,LOLTMNT04_151724,complete,NaN,CCWS,2026,NaN,0,2026-02-05 17:00:44,2,16.02,5,Blue,sup,Kaiser,oe:player:ec0971fb900874b1c59179d9cd33687,Berlin International Gaming,oe:team:3de935df8f40fbb4d0e564d4a20e6cb,1.0,Alistar,Jarvan IV,Orianna,Yunara,Braum,Sivir,NaN,NaN,NaN,NaN,NaN,1721,0,0,6,4,9,22,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.3138,1.0808,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,2674,93.2249,0.043380,690.8193,697.8617,0.0,66,2.3010,5,0.1743,15.0,108,3.7653,6460,2674,93.2249,0.076732,6060.0,NaN,NaN,25.0,25.0,0,NaN,NaN,0.8716,2530.0,2697.0,16.0,2566.0,2799.0,12.0,-36.0,-102.0,4.0,0.0,2.0,2.0,0.0,2.0,2.0,3485.0,3549.0,22.0,3770.0,3711.0,17.0,-285.0,-162.0,5.0,0.0,2.0,2.0,0.0,3.0,2.0,4572.0,3962.0,24.0,5007.0,4999.0,22.0,-435.0,-1037.0,2.0,0.0,2.0,3.0,0.0,5.0,2.0,5724.0,5358.0,25.0,6391.0,7855.0,23.0,-667.0,-2497.0,2.0,0.0,4.0,4.0,0.0,12.0,3.0
36430,LOLTMNT01_365609,complete,NaN,LES,2026,Spring,0,2026-04-15 17:01:43,1,16.07,100,Blue,team,NaN,NaN,UCAM Esports,oe:team:746e6715fc4295c54954be5efc385af,0.0,NaN,Orianna,Rumble,Dr. Mundo,Leona,Braum,Anivia,Yunara,Nautilus,Xin Zhao,Zaahen,1891,0,7,30,18,7,30,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.2221,1.1740,0.0,0.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,NaN,0.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,1.0,1.0,8.0,1.0,0.0,13.0,36.0,0.0,1.0,76943,2441.3432,NaN,5018.9001,3720.1586,17071.0,106,3.3633,42,1.3326,35.0,268,8.5034,51613,30947,981.9249,NaN,50345.0,-0.186877,-2.21,NaN,831.0,192,NaN,NaN,32.4590,17075.0,21614.0,390.0,16667.0,21413.0,395.0,408.0,201.0,-5.0,1.0,2.0,1.0,1.0,3.0,1.0,25979.0,32163.0,571.0,26937.0,33956.0,590.0,-958.0,-1793.0,-19.0,3.0,8.0,5.0,5.0,12.0,3.0,34312.0,44400.0,749.0,39921.0,49023.0,793.0,-5609.0,-4623.0,-44.0,3.0,8.0,12.0,12.0,33.0,3.0,42517.0,53195.0,863.0,51258.0,65961.0,929.0,-8741.0,-12766.0,-66.0,6.0,18.0,19.0,19.0,58.0,6.0
66314,LOLTMNT01_397186,complete,NaN,CD,2026,NaN,0,2026-06-04 21:38:24,3,16.11,3,Blue,mid,DarkHarvest,oe:player:aad116cdf944eda1ab42155b3fd5f9c,Kuma e-Sports,oe:team:de89a20ecdb5c54f17223834eac8c5c,0.0,Viktor,Caitlyn,Pantheon,Karma,Alistar,Pyke,NaN,NaN,NaN,NaN,NaN,1825,0,5,2,5,14,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4603,1.2493,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,23297,765.9288,0.225355,375.4849,495.7808,3363.0,14,0.4603,3,0.0986,4.0,33,1.0849,11841,7842,257.8192,0.239697,12000.0,NaN,NaN,258.0,258.0,0,NaN,NaN,8.4822,3430.0,5023.0,92.0,3699.0,5360.0,102.0,-269.0,-337.0,-10.0,0.0,1.0,0.0,0.0,0.0,0.0,5480.0,7919.0,145.0,5872.0,8315.0,159.0,-392.0,-396.0,-14.0,1.0,2.0,0.0,1.0,0.0,0.0,8033.0,11065.0,201.0,8377.0,11416.0,217.0,-344.0,-351.0,-16.0,2.0,4.0,0.0,2.0,1.0,0.0,10163.0,13441.0,237.0,9613.0,13199.0,242.0,550.0,242.0,-5.0,4.0,5.0,1.0,2.0,2.0,1.0
4174,LOLTMNT03_341150,complete,NaN,LCK,2026,Cup,0,2026-01-23 09:00:11,2,16.01,100,Blue,team,NaN,NaN,T1,oe:team:ce499dea30cfce118f4fe85da0227e8,1.0,NaN,Malphite,Nocturne,Rumble,Jarvan IV,Pantheon,Azir,Aphelios,Lulu,Zaahen,Dr. Mundo,2796,1,9,18,21,9,18,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.1931,0.5794,0.0,2.0,5.0,1.0,4.0,0.0,0.0,0.0,1.0,0.0,0.0,NaN,1.0,1.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,3.0,NaN,NaN,1.0,7.0,10.0,0.0,0.0,15.0,15.0,1.0,4.0,150176,3222.6609,NaN,4051.6524,4678.7339,39494.0,164,3.5193,65,1.3948,41.0,410,8.7983,96187,66290,1422.5322,NaN,86523.0,-0.009055,-2.14,NaN,1522.0,253,NaN,NaN,38.0901,16783.0,20995.0,371.0,17500.0,21259.0,344.0,-717.0,-264.0,27.0,1.0,1.0,3.0,3.0,3.0,1.0,26729.0,33715.0,591.0,27047.0,33562.0,541.0,-318.0,153.0,50.0,1.0,1.0,5.0,5.0,7.0,1.0,35278.0,44745.0,787.0,39029.0,47007.0,751.0,-3751.0,-2262.0,36.0,1.0,1.0,10.0,10.0,20.0,1.0,42736.0,55914.0,951.0,51145.0,64916.0,963.0,-8409.0,-9002.0,-12.0,1.0,1.0,15.0,15.0,32.0,2.0
23239,13134-13134_game_1,complete,https://lpl.qq.com/es/stats.shtml?bmid=13134,LPL,2026,Split 1,1,2026-03-08 09:17:50,1,16.03,8,Red,mid,HongQ,oe:player:a179853ac2a0832657b9de8b9ba0020,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,0.0,Ahri,Orianna,Rumble,Jarvan IV,Galio,Ryze,NaN,NaN,NaN,NaN,NaN,2130,0,4,3,8,13,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3662,0.8169,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,25850,728.1690,0.326158,499.5493,277.8028,2547.0,17,0.4789,7,0.1972,15.0,59,1.6620,13701,9080,255.7746,0.202151,12739.0,NaN,NaN,311.0,311.0,0,NaN,NaN,8.7606,3391.0,5073.0,93.0,3873.0,5414.0,100.0,-482.0,-341.0,-7.0,0.0,0.0,1.0,0.0,1.0,0.0,5574.0,7740.0,140.0,5525.0,8189.0,148.0,49.0,-449.0,-8.0,1.0,4.0,1.0,0.0,1.0,0.0,7612.0,10337.0,190.0,8335.0,11279.0,208.0,-723.0,-942.0,-18.0,3.0,4.0,2.0,2.0,2.0,0.0,9814.0,13742.0,253.0,10562.0,14281.0,272.0,-748.0,-539.0,-19.0,3.0,5.0,2.0,2.0,2.0,0.0
20020,LOLTMNT03_350272,complete,NaN,CD,2026,NaN,0,2026-02-27 21:49:31,1,16.04,5,Blue,sup,Telas,oe:player:a5a630a5d4f0d3151f3c98d2d98834b,Estral Esports,oe:team:1c81857b6ce6a3c1cd9220fd97e077f,NaN,Lulu,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1413,1,0,1,22,26,4,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.1040,1.2739,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5325,226.1146,0.072207,325.6051,151.3800,6579.0,34,1.4437,9,0.3822,7.0,75,3.1847,7862,4704,199.7452,0.121747,6685.0,NaN,NaN,36.0,36.0,0,NaN,NaN,1.5287,2876.0,3495.0,21.0,2281.0,2578.0,10.0,595.0,917.0,11.0,0.0,6.0,0.0,0.0,1.0,2.0,4416.0,5078.0,28.0,3444.0,4120.0,17.0,972.0,958.0,11.0,0.0,8.0,1.0,0.0,2.0,3.0,6271.0,7423.0,33.0,4453.0,5318.0,22.0,1818.0,2105.0,11.0,0.0,15.0,1.0,0.0,2.0,5.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [209]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'url',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'playerid',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'dragons (type unknown)',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'atakhans',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [210]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111156.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,110364.000000,110364.000000,110316.000000,110316.000000,110616.000000,93230.000000,91930.000000,91930.000000,111972.000000,111972.000000,18642.000000,18662.000000,18662.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,276.000000,18394.000000,18394.000000,18378.000000,18662.000000,18662.000000,18662.000000,18662.000000,18252.000000,96532.000000,96532.000000,15574.0,15574.0,18644.000000,18662.000000,18662.000000,18384.000000,18404.000000,18394.000000,18394.000000,96532.000000,96532.000000,111972.000000,111972.000000,93310.000000,111972.000000,110364.000000,110364.000000,111972.000000,111972.000000,111972.000000,111972.000000,111900.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,93310.000000,111900.000000,18650.000000,18394.000000,93310.000000,110582.000000,111972.000000,1656.000000,1656.000000,110582.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.00000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000
mean,2026.010824,0.216911,1.833887,16.097154,29.583333,0.500000,1888.895402,0.500000,5.522523,5.533187,11.900868,16.567570,16.599561,0.580407,0.099507,0.015682,0.003263,0.271579,0.099989,0.125519,0.100000,0.534753,1.069506,0.499625,2.202497,2.202497,2.158856,2.158856,0.365119,0.354735,0.359683,0.360607,0.362781,0.355931,2.217391,0.043656,0.043656,0.490641,0.489872,0.489872,1.475619,1.475619,0.480934,0.241930,0.241930,0.0,0.0,0.500000,5.910781,5.910781,0.500000,0.499348,25.842666,25.842666,0.295208,0.295208,30597.951095,964.528301,0.200000,1246.383997,1201.843655,8695.381737,34.974887,1.098982,14.353642,0.445808,11.634602,94.621361,2.962315,20538.249455,13656.746740,434.122844,0.200000,18945.941966,0.000000,0.000000,216.163691,282.720244,69.566517,52.416063,5.844203,11.161138,5670.962542,6775.172054,117.874637,5670.962542,6775.172054,117.874637,0.000000,0.000000,0.000000,0.870284,1.219018,0.874365,0.870284,1.219018,0.874365,8887.911253,10905.720390,182.778104,8887.911253,10905.720390,182.778104,0.000000,0.000000,0.000000,1.672108,2.579660,1.677694,1.672108,2.579660,1.677694,12357.667321,15157.251109,246.922973,12357.667321,15157.251109,246.922973,0.000000,0.000000,0.000000,2.614031,4.562177,2.620647,2.614031,4.562177,2.620647,15724.795902,19490.706613,301.812668,15724.795902,19490.706613,301.812668,0.00000,0.000000,0.000000,3.627052,7.117207,3.634480,3.627052,7.117207,3.634480
std,0.106537,0.412144,0.954467,0.053786,57.650725,0.500002,330.836815,0.500002,6.587198,6.300329,13.949761,8.214425,8.214491,1.059289,0.347163,0.128194,0.058755,0.444776,0.299987,0.331309,0.300002,0.284398,0.330353,0.500013,1.395557,1.395557,1.352386,1.352386,0.659583,0.648799,0.648547,0.655168,0.656372,0.648647,1.260529,0.217480,0.217480,0.499926,0.500018,0.500018,1.339974,1.339974,0.499650,0.530375,0.530375,0.0,0.0,0.500013,3.675539,3.675539,0.500014,0.500013,12.784533,12.784533,0.640917,0.640917,31420.645337,945.376526,0.087911,1175.304107,1240.577940,10308.687176,38.228752,1.143552,15.519361,0.454390,13.349856,98.155472,2.912288,19290.350979,13118.730067,406.338544,0.061517,17801.349388,0.135028,2.394592,107.403089,284.296111,96.113297,72.399447,10.142424,10.425424,5115.009895,6137.072924,109.442461,5115.009895,6137.072924,109.442461,812.999226,636.417626,16.382822,1.394486,2.019687,1.357925,1.394486,2.019687,1.357925,8039.469095,9902.049726,169.756602,8039.469095,9902.049726,169.756602,1571.043562,1316.458569,25.334059,2.337384,3.605775,2.263780,2.337384,3.605775,2.263780,11203.390144,13759.594239,229.828998,11203.390144,13759.594239,229.828998,2451.969892,2076.536157,32.804459,3.424478,5.874698,3.306390,3.424478,5.874698,3.306390,14275.338053,17709.746946,281.335018,14275.338053,17709.746946,281.335018,3301.19197,3488.126589,37.736868,4.531256,8.726760,4.358712,4.531256,8.726760,4.358712
min,2025.000000,0.000000,1.000000,15.240000,1.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.247600,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,619.000000,23.807700,0.013642,29.518700,10.154300,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.045600,3698.000000,1299.000000,49.961500,0.051677,3150.000000,-0.486885,-9.340000,7.000000,0.000000,0.000000,0.000000,0.000000,0.257900,1909.000000,854.000000,1.000000,1909.000000,854.000000,1.000000,-8762.000000,-6305.000000,-155.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2979.000000,1998.000000,3.000000,2979.000000,1998.000000,3.000000,-14704.000000,-12451.000000,-233.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3842.000000,2495.000000,4.000000,3842.000000,2495.000000,4.000000,-20232.000000,-18841.000000,-266.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4604.000000,3090.000000,7.000000,4604.000000,3090.000000,7.000000,-22049.00000,-22919.000000,-301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.000000,0.000000,1.000000,16.060000,3.750000,0.000000,1649.000000,0.000000,1.000000,2.000000,4.000000,10.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.318100,0.834100,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,2.000000,2.000000,0.000000,0.000000,15.000000,15.000000,0.000000,0.000000,11785.000000,395.795750,0.133229,570.607500,384.328250,1402.000000,10.000000,0.335675,5.000000,0.159075,3.000000,33.000000,1.090900,10182.000000,6239.000000,210.814450,0.165224,9375.000000,-0.095788,-1.660000,175.000000,35.000000,0.000000,0.000000,0.000000,6.569100,3237.000000,3558.000000,71.000000,3237.000000,3558.000000,71.000000,-373.000000,-327.000000,-8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4957.000000,5823.000000,110.000000,4957.000000,5823.000000,110.000000,-652.000000,-607.000000,-12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6829.000000,8313.000000,147.000000,6829.000000,8313.000000,147.000000,-998.000000,-918.000000,-15.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,8592.000000,10664.000000,178.000000,8592.000000,10664.000000,178.000000,-1360.00000,-1488.000000,-18.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2026.000000,0.000000,2.000000,16.090000,6.500000,0.500000,1859.000000,0.500000,3.000000,4.000000,7.000000,16.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.497600,1.033600,0.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,0.500000,7.000000,7.000000,0.500000,0.000000,25.000000,25.000000,0.000000,0.000000,19492.500000,632.692150,0.202591,778.064450,706.920950,5260.000000,15.000000,0.458900,9.000000,0.282900,6.000000,50.000000,1.512700,12984.000000,8869.000000,281.701450,0.204273,11958.000000,0.000000,0.000000,238.000000,244.000000,4.000000,4.000000,0.000000,8.338700,3575.000000,4480.000000,85.000000,3575.000000,4480.000000,85.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5623.000000,7182.000000,133.000000,5623.000000,7182.000000,133.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7844.000000,9946.000000,181.000000,7844.000000,9946.000000,181.000000,0.000000,0.000000,0.000000,1.000000,3.000000,2.000000,1.000000,3.000000,2.000000,9985.000000,12696.000000,221.000000,9985.000000,12696.000000,221.000000,0.00000,0.000000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2026.000000,0.000000,2.000000,16.150000,9.250000,1.000000,2085.000000,1.000000,7.000000,6.000000,13.000000,22.000000,22.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.707600,1.256700,1.000000,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3.000000,3.000000,1.000000,0.000000,0.000000,0.0,0.0,1.000000,9.000000,9.000000,1.000000,1.000000,38.000000,38.000000,0.000000,0.000000,31826.000000,968.456350,0.262569,1131.274175,1368.522325,11374.000000,54.000000,1.778700,16.000000,0.496925,14.000000,120.000000,3.863175,16939.250000,12336.000000,379.988650,0.240507,15590.000000,0.095788,1.660000,287.000000,320.000000,171.000000,135.000000,8.000000,9.908300,4049.000000,5277.000000,99.000000,4049.000000,5277.000000,99.000000,373.000000,327.000000,8.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,6533.000000,8690.000000,153.000000,6533.000000,8690.000000,153.000000,652.000000,607.000000,12.000000,2.000000,3.000000,2.000000,2.000000,3.000000,2.000000,9227.000000,11890.250000,209.000000,9227.000000,11890.250000,209.000000,998.000000,918.000000,15.000000,3.000000,5.000000,3.000000,3.000000,5.000000,3.000000,11881.000000,15118.000000,258.000000,11881.000000,15118.000000,258.000000,1360.00000,1488.000000,18.000000,5.000000,8.000000,4.000000,5.000000,8.000000,4.000000
max,2027.000000,1.000000,5.000000,16.180000,200.000000,1.000000,3657.000000,1.000000,54.000000,54.000000,122.000000,54.000000,54.000000,18.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.095000,2.807300,1.000000,8.000000,8.000000,6.000000,6.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,1.000000,2.000000,2.000000,6.000000,6.000000,1.000000,4.000000,4.000000,0.0,0.0,1.000000,18.000000,18.000000,1.000000,1.000000,45.000000,45.000000,10.000000,10.000000,367979.000000,6291.486900,0.554940,7334.339600,11158.123600,53929.000000,260.000000,5.263600,131.000000,2.752000,110.000000,749.000000,14.276400,123556.000000,87467.000000,2009.340000,0.443045,128590.000000,0.486885,9.340000,636.000000,1635.000000,442.000000,240.000000,58.000000,45.199300,23163.000000,23646.000000,425.000000,23163.000000,23646.000000,425.000000,8762.000000,6305.000000,155.000000,16.000000,25.000000,16.000000,16.000000,25.000000,16.000000,37358.000000,38749.000000,665.000000,37358.000000,38749.000000,665.000000,14704.000000,12451.000000,233.000000,29.000000,41.000000,29.000000,29.000000,41.000000,29.000000,52772.000000,56167.000000,899.000000,52772.000000,56167.000000,899.000000,20232.000000,18841.000000,266.000000,41.000000,73.000000,41.000000,41.000000,73.000000,41.000000,64509.000000,76298.000000,1132.000000,64509.000000,76298.000000,1132.000000,22049.00000,22919.000000,301.000000,44.000000,88.000000,44.000000,44.000000,88.000000,44.000000

In [211]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111972 entries, 0 to 111971
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(124), int64(18), str(23)
memory usage: 141.0 MB

In [212]:
df['league'].unique()

<StringArray>
[     'DCup',       'LIT',      'LCKC',        'AL',       'ROL',       'LCK',
       'LPL',       'HLL',       'NLC',       'LCP',       'LEC',     'CBLOL',
       'TCL',      'CCWS',       'LFL',        'HW',       'LCS',       'EBL',
       'LJL',       'PRM',     'LPLOL',       'LES',        'RL',        'CD',
       'VCS',       'LRN',       'LRS',        'AC',        'EM',       'FST',
       'LAS',      'NACL',        'NL',       'EWC',        'HM',        'HC',
       'PCS',        'AM',       'MSI', 'KeSPA Cup',      'WLRQ',      'WSCI',
      'WLDs']
Length: 43, dtype: str

In [213]:
df['gameid'].nunique()

9331

In [214]:
df.describe()
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 111972 entries, 0 to 111971
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(124), int64(18), str(23)
memory usage: 141.0 MB

In [215]:
df.describe()

,year,playoffs,game,patch,participantid,firstPick,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
count,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111156.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,110364.000000,110364.000000,110316.000000,110316.000000,110616.000000,93230.000000,91930.000000,91930.000000,111972.000000,111972.000000,18642.000000,18662.000000,18662.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,18394.000000,276.000000,18394.000000,18394.000000,18378.000000,18662.000000,18662.000000,18662.000000,18662.000000,18252.000000,96532.000000,96532.000000,15574.0,15574.0,18644.000000,18662.000000,18662.000000,18384.000000,18404.000000,18394.000000,18394.000000,96532.000000,96532.000000,111972.000000,111972.000000,93310.000000,111972.000000,110364.000000,110364.000000,111972.000000,111972.000000,111972.000000,111972.000000,111900.000000,111972.000000,111972.000000,111972.000000,111972.000000,111972.000000,93310.000000,111900.000000,18650.000000,18394.000000,93310.000000,110582.000000,111972.000000,1656.000000,1656.000000,110582.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110256.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110268.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,110040.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.00000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000,102588.000000
mean,2026.010824,0.216911,1.833887,16.097154,29.583333,0.500000,1888.895402,0.500000,5.522523,5.533187,11.900868,16.567570,16.599561,0.580407,0.099507,0.015682,0.003263,0.271579,0.099989,0.125519,0.100000,0.534753,1.069506,0.499625,2.202497,2.202497,2.158856,2.158856,0.365119,0.354735,0.359683,0.360607,0.362781,0.355931,2.217391,0.043656,0.043656,0.490641,0.489872,0.489872,1.475619,1.475619,0.480934,0.241930,0.241930,0.0,0.0,0.500000,5.910781,5.910781,0.500000,0.499348,25.842666,25.842666,0.295208,0.295208,30597.951095,964.528301,0.200000,1246.383997,1201.843655,8695.381737,34.974887,1.098982,14.353642,0.445808,11.634602,94.621361,2.962315,20538.249455,13656.746740,434.122844,0.200000,18945.941966,0.000000,0.000000,216.163691,282.720244,69.566517,52.416063,5.844203,11.161138,5670.962542,6775.172054,117.874637,5670.962542,6775.172054,117.874637,0.000000,0.000000,0.000000,0.870284,1.219018,0.874365,0.870284,1.219018,0.874365,8887.911253,10905.720390,182.778104,8887.911253,10905.720390,182.778104,0.000000,0.000000,0.000000,1.672108,2.579660,1.677694,1.672108,2.579660,1.677694,12357.667321,15157.251109,246.922973,12357.667321,15157.251109,246.922973,0.000000,0.000000,0.000000,2.614031,4.562177,2.620647,2.614031,4.562177,2.620647,15724.795902,19490.706613,301.812668,15724.795902,19490.706613,301.812668,0.00000,0.000000,0.000000,3.627052,7.117207,3.634480,3.627052,7.117207,3.634480
std,0.106537,0.412144,0.954467,0.053786,57.650725,0.500002,330.836815,0.500002,6.587198,6.300329,13.949761,8.214425,8.214491,1.059289,0.347163,0.128194,0.058755,0.444776,0.299987,0.331309,0.300002,0.284398,0.330353,0.500013,1.395557,1.395557,1.352386,1.352386,0.659583,0.648799,0.648547,0.655168,0.656372,0.648647,1.260529,0.217480,0.217480,0.499926,0.500018,0.500018,1.339974,1.339974,0.499650,0.530375,0.530375,0.0,0.0,0.500013,3.675539,3.675539,0.500014,0.500013,12.784533,12.784533,0.640917,0.640917,31420.645337,945.376526,0.087911,1175.304107,1240.577940,10308.687176,38.228752,1.143552,15.519361,0.454390,13.349856,98.155472,2.912288,19290.350979,13118.730067,406.338544,0.061517,17801.349388,0.135028,2.394592,107.403089,284.296111,96.113297,72.399447,10.142424,10.425424,5115.009895,6137.072924,109.442461,5115.009895,6137.072924,109.442461,812.999226,636.417626,16.382822,1.394486,2.019687,1.357925,1.394486,2.019687,1.357925,8039.469095,9902.049726,169.756602,8039.469095,9902.049726,169.756602,1571.043562,1316.458569,25.334059,2.337384,3.605775,2.263780,2.337384,3.605775,2.263780,11203.390144,13759.594239,229.828998,11203.390144,13759.594239,229.828998,2451.969892,2076.536157,32.804459,3.424478,5.874698,3.306390,3.424478,5.874698,3.306390,14275.338053,17709.746946,281.335018,14275.338053,17709.746946,281.335018,3301.19197,3488.126589,37.736868,4.531256,8.726760,4.358712,4.531256,8.726760,4.358712
min,2025.000000,0.000000,1.000000,15.240000,1.000000,0.000000,1000.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.247600,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,619.000000,23.807700,0.013642,29.518700,10.154300,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.045600,3698.000000,1299.000000,49.961500,0.051677,3150.000000,-0.486885,-9.340000,7.000000,0.000000,0.000000,0.000000,0.000000,0.257900,1909.000000,854.000000,1.000000,1909.000000,854.000000,1.000000,-8762.000000,-6305.000000,-155.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2979.000000,1998.000000,3.000000,2979.000000,1998.000000,3.000000,-14704.000000,-12451.000000,-233.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,3842.000000,2495.000000,4.000000,3842.000000,2495.000000,4.000000,-20232.000000,-18841.000000,-266.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4604.000000,3090.000000,7.000000,4604.000000,3090.000000,7.000000,-22049.00000,-22919.000000,-301.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,2026.000000,0.000000,1.000000,16.060000,3.750000,0.000000,1649.000000,0.000000,1.000000,2.000000,4.000000,10.000000,10.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.318100,0.834100,0.000000,1.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.0,0.0,0.000000,2.000000,2.000000,0.000000,0.000000,15.000000,15.000000,0.000000,0.000000,11785.000000,395.795750,0.133229,570.607500,384.328250,1402.000000,10.000000,0.335675,5.000000,0.159075,3.000000,33.000000,1.090900,10182.000000,6239.000000,210.814450,0.165224,9375.000000,-0.095788,-1.660000,175.000000,35.000000,0.000000,0.000000,0.000000,6.569100,3237.000000,3558.000000,71.000000,3237.000000,3558.000000,71.000000,-373.000000,-327.000000,-8.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,4957.000000,5823.000000,110.000000,4957.000000,5823.000000,110.000000,-652.000000,-607.000000,-12.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,6829.000000,8313.000000,147.000000,6829.000000,8313.000000,147.000000,-998.000000,-918.000000,-15.000000,0.000000,1.000000,1.000000,0.000000,1.000000,1.000000,8592.000000,10664.000000,178.000000,8592.000000,10664.000000,178.000000,-1360.00000,-1488.000000,-18.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000
50%,2026.000000,0.000000,2.000000,16.090000,6.500000,0.500000,1859.000000,0.500000,3.000000,4.000000,7.000000,16.000000,16.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.497600,1.033600,0.000000,2.000000,2.000000,2.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,2.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.0,0.0,0.500000,7.000000,7.000000,0.500000,0.000000,25.000000,25.000000,0.000000,0.000000,19492.500000,632.692150,0.202591,778.064450,706.920950,5260.000000,15.000000,0.458900,9.000000,0.282900,6.000000,50.000000,1.512700,12984.000000,8869.000000,281.701450,0.204273,11958.000000,0.000000,0.000000,238.000000,244.000000,4.000000,4.000000,0.000000,8.338700,3575.000000,4480.000000,85.000000,3575.000000,4480.000000,85.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,5623.000000,7182.000000,133.000000,5623.000000,7182.000000,133.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,7844.000000,9946.000000,181.000000,7844.000000,9946.000000,181.000000,0.000000,0.000000,0.000000,1.000000,3.000000,2.000000,1.000000,3.000000,2.000000,9985.000000,12696.000000,221.000000,9985.000000,12696.000000,221.000000,0.00000,0.000000,0.000000,2.000000,4.000000,2.000000,2.000000,4.000000,2.000000
75%,2026.000000,0.000000,2.000000,16.150000,9.250000,1.000000,2085.000000,1.000000,7.000000,6.000000,13.000000,22.000000,22.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.707600,1.256700,1.000000,3.000000,3.000000,3.000000,3.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,3.000000,0.000000,0.000000,1.000000,1.000000,1.000000,3.000000,3.000000,1.000000,0.000000,0.000000,0.0,0.0,1.000000,9.000000,9.000000,1.000000,1.000000,38.000000,38.000000,0.000000,0.000000,31826.000000,968.456350,0.262569,1131.274175,1368.522325,11374.000000,54.000000,1.778700,16.000000,0.496925,14.000000,120.000000,3.863175,16939.250000,12336.000000,379.988650,0.240507,15590.000000,0.095788,1.660000,287.000000,320.000000,171.000000,135.000000,8.000000,9.908300,4049.000000,5277.000000,99.000000,4049.000000,5277.000000,99.000000,373.000000,327.000000,8.000000,1.000000,2.000000,1.000000,1.000000,2.000000,1.000000,6533.000000,8690.000000,153.000000,6533.000000,8690.000000,153.000000,652.000000,607.000000,12.000000,2.000000,3.000000,2.000000,2.000000,3.000000,2.000000,9227.000000,11890.250000,209.000000,9227.000000,11890.250000,209.000000,998.000000,918.000000,15.000000,3.000000,5.000000,3.000000,3.000000,5.000000,3.000000,11881.000000,15118.000000,258.000000,11881.000000,15118.000000,258.000000,1360.00000,1488.000000,18.000000,5.000000,8.000000,4.000000,5.000000,8.000000,4.000000
max,2027.000000,1.000000,5.000000,16.180000,200.000000,1.000000,3657.000000,1.000000,54.000000,54.000000,122.000000,54.000000,54.000000,18.000000,4.000000,3.000000,2.000000,1.000000,1.000000,1.000000,1.000000,2.095000,2.807300,1.000000,8.000000,8.000000,6.000000,6.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,4.000000,1.000000,2.000000,2.000000,6.000000,6.000000,1.000000,4.000000,4.000000,0.0,0.0,1.000000,18.000000,18.000000,1.000000,1.000000,45.000000,45.000000,10.000000,10.000000,367979.000000,6291.486900,0.554940,7334.339600,11158.123600,53929.000000,260.000000,5.263600,131.000000,2.752000,110.000000,749.000000,14.276400,123556.000000,87467.000000,2009.340000,0.443045,128590.000000,0.486885,9.340000,636.000000,1635.000000,442.000000,240.000000,58.000000,45.199300,23163.000000,23646.000000,425.000000,23163.000000,23646.000000,425.000000,8762.000000,6305.000000,155.000000,16.000000,25.000000,16.000000,16.000000,25.000000,16.000000,37358.000000,38749.000000,665.000000,37358.000000,38749.000000,665.000000,14704.000000,12451.000000,233.000000,29.000000,41.000000,29.000000,29.000000,41.000000,29.000000,52772.000000,56167.000000,899.000000,52772.000000,56167.000000,899.000000,20232.000000,18841.000000,266.000000,41.000000,73.000000,41.000000,41.000000,73.000000,41.000000,64509.000000,76298.000000,1132.000000,64509.000000,76298.000000,1132.000000,22049.00000,22919.000000,301.000000,44.000000,88.000000,44.000000,44.000000,88.000000,44.000000

In [216]:
fst_df = df[df['league'] == 'FST']
fst_df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25560,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,oe:player:d87853a5c1c5463889d70a62cdbcffc,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0.0,28,0.9444,10807,6902,232.7825,0.196186,9150.0,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25561,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,oe:player:637ed20b1e41be1c51bd1a4cb211357,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11.0,55,1.8550,12060,8155,275.0422,0.231800,11925.0,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25562,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,oe:player:d709285b163a94af9d819e568c592ba,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3.0,22,0.7420,10726,6821,230.0506,0.193883,10500.0,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25563,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,oe:player:178ec186b0d43d2669342596c2808cd,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4.0,38,1.2816,13565,9660,325.8010,0.274577,14010.0,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25564,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,oe:player:b0ec3df39d61f953e7af0afd8eb8c4a,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11.0,127,4.2833,7548,3643,122.8668,0.103554,7675.0,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26491,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,8,Red,mid,Caps,oe:player:55dd587cdc4a278be6a5c37f9e539de,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Viktor,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,3,1,7,12,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21737,817.6928,0.370717,466.1944,503.7743,4885.0,10,0.3762,8,0.3009,4.0,34,1.2790,9911,6382,240.0752,0.207640,8950.0,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8025,3663.0,5182.0,88.0,3998.0,4788.0,88.0,-335.0,394.0,0.0,0.0,3.0,1.0,2.0,0.0,1.0,5931.0,8528.0,136.0,5265.0,6822.0,123.0,666.0,1706.0,13.0,2.0,6.0,1.0,2.0,0.0,3.0,7919.0,11264.0,194.0,7403.0,10065.0,181.0,516.0,1199.0,13.0,2.0,6.0,1.0,2.0,2.0,3.0,9607.0,13354.0,230.0,8976.0,14082.0,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26492,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,oe:player:c62a5235ad6bc113a1e64eb0e9aa8c8,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3.0,40,1.5047,12236,8707,327.5361,0.283289,11925.0,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26493,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,10,Red,sup,Labrov,oe:player:bb6ac5763c6576e104a7a2f59eb4ddf,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Rakan,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,0,2,9,12,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4537,170.6708,0.077377,507.0470,463.9749,0.0,47,1.7680,12,0.4514,11.0,105,3.9498,6496,2967,111.6113,0.096525,5920.0,NaN,NaN,24.0,24.0,0,NaN,NaN,0.9028,2504.0,1757.0,9.0,2550.0,2304.0,9.0,-46.0,-547.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0,3829.0,3936.0,15.0,3732.0,3230.0,19.0,97.0,706.0,-4.0,0.0,7.0,0.0,0.0,1.0,2.0,4971.0,4573.0,21.0,4980.0,4639.0,21.0,-9.0,-66.0,0.0,0.0,7.0,1.0,0.0,3.0,2.0,6161.0,6314.0,24.0,6268.0,7303.0,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26494,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,100,Blue,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Rumble,Maokai,Akali,Vi,Xayah,Alistar,Camille,Cassiopeia,1595,1,8,12,19,8,12,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3009,0.7524,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,7.0,1.0,1.0,1.0,25.0,12.0,1.0,0.0,57024,2145.1034,NaN,3055.0345,2666.2947,32895.0,102,3.8370,36,1.3542,28.0,254,9.5549,51682,34035,1280.3135,NaN,45223.0,-0.025218,-0.18,NaN,813.0,185,NaN,NaN,37.5423,17356.0,20681.0,372.0,17656.0,19713.0,330.0,-300.0,968.0,42.0,2.0,2.0,4.0,4.0,9.0,2.0,25357.0,31403.0,558.0,28580.0,34561.0,520.0,-3223.0,-3158.0,38.0,2.0,2.0,10.0,10.0,20.0,2.0,36649.0,45707.0,786.0,37537.0,46378.0,745.0,-888.0,-671.0,41.0,4.0,7.0,10.0,10.0,20.0,4.0,46187.0,62098.0,979.0,46122.0,57751.0,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26495,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26.0,252,9.4796,48381,30734,1156.1379,NaN,46378.0,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [217]:
fst_df.shape

(540, 165)

In [218]:
fst_df['gameid'].unique()

<StringArray>
['LOLTMNT01_349243', 'LOLTMNT01_350155', 'LOLTMNT01_349264',
 'LOLTMNT01_349281', 'LOLTMNT01_349288', 'LOLTMNT01_349312',
 'LOLTMNT01_349329', 'LOLTMNT01_350246', 'LOLTMNT01_349522',
 'LOLTMNT01_350440', 'LOLTMNT01_349529', 'LOLTMNT01_350457',
 'LOLTMNT01_349555', 'LOLTMNT01_350472', 'LOLTMNT01_349576',
 'LOLTMNT01_350498', 'LOLTMNT01_349770', 'LOLTMNT01_350687',
 'LOLTMNT01_349782', 'LOLTMNT01_350703', 'LOLTMNT01_350716',
 'LOLTMNT01_349807', 'LOLTMNT01_351028', 'LOLTMNT01_350979',
 'LOLTMNT01_350983', 'LOLTMNT01_351065', 'LOLTMNT01_352009',
 'LOLTMNT01_352019', 'LOLTMNT01_351208', 'LOLTMNT01_351218',
 'LOLTMNT01_351223', 'LOLTMNT01_351241', 'LOLTMNT01_351251',
 'LOLTMNT01_352208', 'LOLTMNT01_351262', 'LOLTMNT01_351445',
 'LOLTMNT01_352417', 'LOLTMNT01_352425', 'LOLTMNT01_352447',
 'LOLTMNT01_351479', 'LOLTMNT01_352471', 'LOLTMNT01_351652',
 'LOLTMNT01_352609', 'LOLTMNT01_351658', 'LOLTMNT01_352610']
Length: 45, dtype: str

In [219]:
fst_df['gameid'].nunique()

45

In [220]:
fst_df.head(25)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25560,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,oe:player:d87853a5c1c5463889d70a62cdbcffc,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0.0,28,0.9444,10807,6902,232.7825,0.196186,9150.0,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25561,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,oe:player:637ed20b1e41be1c51bd1a4cb211357,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11.0,55,1.8550,12060,8155,275.0422,0.231800,11925.0,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25562,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,oe:player:d709285b163a94af9d819e568c592ba,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3.0,22,0.7420,10726,6821,230.0506,0.193883,10500.0,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25563,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,oe:player:178ec186b0d43d2669342596c2808cd,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4.0,38,1.2816,13565,9660,325.8010,0.274577,14010.0,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25564,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,oe:player:b0ec3df39d61f953e7af0afd8eb8c4a,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11.0,127,4.2833,7548,3643,122.8668,0.103554,7675.0,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
25565,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,6,Red,top,Bin,oe:player:fb66ef5885b4be9323905b821dc3a42,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,Jax,Azir,Karma,Rumble,Ezreal,Yunara,NaN,NaN,NaN,NaN,NaN,1779,1,11,1,2,29,9,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9781,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,23769,801.6526,0.283792,716.3238,985.0253,15150.0,17,0.5734,0,0.0000,5.0,42,1.4165,16058,12153,409.8820,0.258035,13938.0,NaN,NaN,282.0,278.0,4,NaN,NaN,9.5110,3823.0,4876.0,74.0,3202.0,4670.0,74.0,621.0,206.0,0.0,2.0,0.0,1.0,0.0,1.0,2.0,6085.0,8603.0,131.0,4694.0,7738.0,117.0,1391.0,865.0,14.0,2.0,1.0,1.0,0.0,1.0,3.0,9617.0,12067.0,187.0,6593.0,10747.0,156.0,3024.0,1320.0,31.0,4.0,1.0,1.0,1.0,1.0,4.0,12385.0,16714.0,245.0,8206.0,13352.0,195.0,4179.0,3362.0,50.0,6.0,2.0,1.0,1.0,1.0,5.0
25566,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,7,Red,jng,Xun,oe:player:fbdc4428b2d095c83aebeed5da4e4b2,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,Jarvan IV,Azir,Karma,Rumble,Ezreal,Yunara,NaN,NaN,NaN,NaN,NaN,1779,1,4,2,19,29,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9781,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,14848,500.7757,0.177279,890.6914,1104.1821,0.0,9,0.3035,15,0.5059,7.0,62,2.0911,12521,8616,290.5902,0.182938,11275.0,NaN,NaN,202.0,17.0,185,NaN,NaN,6.8128,3790.0,3658.0,68.0,4676.0,4420.0,75.0,-886.0,-762.0,-7.0,1.0,3.0,1.0,3.0,0.0,1.0,5915.0,6170.0,106.0,6447.0,6891.0,118.0,-532.0,-721.0,-12.0,2.0,5.0,1.0,3.0,1.0,3.0,8164.0,9287.0,145.0,8220.0,9040.0,154.0,-56.0,247.0,-9.0,2.0,11.0,1.0,3.0,2.0,4.0,10974.0,13279.0,189.0,9527.0,10342.0,173.0,1447.0,2937.0,16.0,4.0,15.0,1.0,3.0,2.0,6.0
25567,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,8,Red,mid,Knight,oe:player:ed29043422e3c515e1cb292464b990b,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,Ryze,Azir,Karma,Rumble,Ezreal,Yunara,NaN,NaN,NaN,NaN,NaN,1779,1,5,2,12,29,9,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.9781,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17618,594.1990,0.210352,590.5228,352.4789,5794.0,13,0.4384,12,0.4047,3.0,45,1.5177,12968,9063,305.6661,0.192429,11925.0,NaN,NaN,279.0,255.0,24,NaN,NaN,9.4098,4345.0,4548.0,82.0,3459.0,4353.0,79.0,886.0,195.0,3.0,3.0,2.0,1.0,0.0,2.0,2.0,6232.0,7530.0,136.0,5416.0,7181.0,134.0,816.0,349.0,2.0,3.0,4.0,1.0,1.0,2.0,2.0,8643.0,10420.0,189.0,7260.0,9716.0,184.0,1383.0,704.0,5.0,4.0,9.0,2.0,1.0,4.0,3.0,10604.0,14703.0,235.0,9163.0,12550.0,236.0,1441.0,2153.0,-1.0,4.0,10.0,2.0,1.0,4.0,4.0
25568,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,9,Red,bot,Viper,oe:player:9573154ad8bc9459b4c0d940315054f,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,Varus,Azir,Karma,Rumble,Ezreal,Yunara,NaN,NaN,NaN,NaN,NaN,1779,1,6,1,8,29,9,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9781,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,21070,710.6239,0.251567,327.1838,172.7150,13749.0,20,0.6745,5,0.1686,9.0,41,1.3828,15519,11614,391.7032,0.246591,13575.0,NaN,NaN,296.0,294.0,2,NaN,NaN,9.9831,3588.0,3939.0,97.0,3901.0,4021.0,98.0,-313.0,-82.0,-1.0,0.0,1.0,0.0,1.0,0.0,0.0,5991.0,7002.0,161.0,6361.0,6670.0,155.0,-370.0,332.0,6.0,0.0,1.0,0.0,1.0,0.0,0.0,9729.0,9937.0,217.0,9379.0,9470.0,216.0,350.0,467.0,1.0,3.0,3.0,0.0,2.0,1.0,1.0,12576.0,13044.0,257.0,11676.0,12064.0,282.0,900.0,980.0,-25.0,5.0,4.0,0.0,2.0,1.0,2.0
25569,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,10,Red,sup,ON,oe:player:90651ebea9a35ec4e018c8157492e17,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,Alistar,Azir,Karma,Rumble,Ezreal,Yunara,NaN,NaN,NaN,NaN,NaN,1779,1,3,3,21,29,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9781,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,6450,217.5379,0.077010,805.5987,1052.7825,3518.0,71,2.3946,5,0.1686,18.0,117,3.9460,9557,5652,190.6239,0.120007,8315.0,NaN,NaN,18.0,18.0,0,NaN,NaN,0.6071,2716.0,2872.0,13.0,2489.0,2564.0,10.0,227.0,308.0,3.0,1.0,2.0,1.0,0.0,2.0,2.0,4522.0,3740.0,14.0,3768.0,3066.0,16.0,754.0,674.0,-2.0,3.0,3.0,2.0,0.0,3.0,2.0,6027.0,5081.0,17.0,5128.0,4683.0,21.0,899.0,398.0,-4.0,3.0,9.0,3.0,0.0,5.0,4.0,7582.0,7485.0,18.0,6380.0,5515.0,28.0,1202.0,1970.0,-10.0,3.0,14.0,3.0,0.0,5.0,5.0
25570,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,100,Blue,team,NaN,NaN,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,NaN,Orianna,Poppy,Xin Zhao,Bard,Renekton,Taliyah,Vi,Ambessa,Neeko,Kai'Sa,1779,0,9,29,20,9,29,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3035,1.2816,0.0,2.0,2.0,2.0,2.0,1.0,0.0,0.0,0.0,1.0,0.0,NaN,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,1.0,9.0,0.0,0.0,11.0,39.0,0.0,1.0,66416,2240.0000,NaN,3453.6594,2684.5531,5411.0,115,3.8786,46,1.5514,29.0,270,9.1062,54706,35182,1186.5767,NaN,53260.0,-0.102736,-3.26,NaN,846.0,183,NaN,NaN,34.7049,17727.0,20028.0,336.0,18262.0,19893.0,334.0,-535.0,135.0,2.0,4.0,5.0,7.0,7.0,8.0,4.0,26686.0,31546.0,540.0,28745.0,33045.0,548.0,-2059.0,-1499.0,-8.0,5.0,7.0,10.0,10.0,14.0,5.0,36580.0,43656.0,731.0,42180.0,46792.0,755.0,-5600.0,-3136.0,-24.0,7.0,13.0,16.0,16.0,33.0,7.0,44952.0,53823.0,914.0,54121.0,65225.0,944.0,-9169.0,-11402.0,-30.0,7.0,13.0,22.0,22.0,45.0,7.0
25571,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,200,Red,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,NaN,Azir,Karma,Rumble,Ezreal,Yunara,Ryze,Jarvan IV,Varus,Alistar,Jax,1779,1,29,9,62,29,9,5.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.9781,1.2816,1.0,2.0,2.0,2.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,1.0,0.0,1.0,2.0,0.0,0.0,0.0,1.0,9.0,1.0,1.0,1.0,39.0,11.0,1.0,0.0,83755,2824.7892,NaN,3330.3204,3667.1838,38211.0,130,4.3845,37,1.2479,42.0,307,10.3541,66623,47099,1588.4992,NaN,59028.0,0.102736,3.26,NaN,862.0,215,NaN,NaN,36.3238,18262.0,19893.0,334.0,17727.0,20028.0,336.0,535.0,-135.0,-2.0,7.0,8.0,4.0,4.0,5.0,7.0,28745.0,33045.0,548.0,26686.0,31546.0,540.0,2059.0,1499.0,8.0,10.0,14.0,5.0,5.0,7.0,10.0,42180.0,46792.0,755.0,36580.0,43656.0,731.0,5600.0,3136.0,24.0,16.0,33.0,7.0,7.0,13.0,16.0,54121.0,65225.0,944.0,44952.0,53823.0,914.0,9169.0,11402.0,30.0,22.0,45.0,7.0,7.0,13.0,22.0
25572,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,1,Blue,top,Bin,oe:player:fb66ef5885b4be9323905b821dc3a42,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Sion,Orianna,Rumble,Ashe,Trundle,Azir,NaN,NaN,NaN,NaN,NaN,1570,0,0,2,3,11,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4204,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15964,610.0892,0.203055,809.3121,1992.7261,4712.0,8,0.3057,6,0.2293,3.0,28,1.0701,10190,6712,256.5096,0.206168,9675.0,NaN,NaN,269.0,269.0,0,NaN,NaN,10.2803,3582.0,5348.0,100.0,3581.0,5349.0,95.0,1.0,-1.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,5668.0,9666.0,161.0,5988.0,9103.0,156.0,-320.0,563.0,5.0,0.0,2.0,0.0,1.0,0.0,1.0,7990.0,13246.0,221.0,8680.0,12094.0,203.0,-690.0,1152.0,18.0,0.0,3.0,1.0,2.0,2.0,1.0,10048.0,16835.0,269.0,10804.0,15833.0,269.0,-756.0,1002.0,0.0,0.0,3.0,1.0,2.0,2.0,1.0
25573,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,2,Blue,jng,Xun,oe:player:fbdc4428b2d095c83aebeed5da4e4b2,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Pantheon,Orianna,Rumble,Ashe,Trundle,Azir,NaN,NaN,NaN,NaN,NaN,1570,0,4,3,3,11,13,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4204,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,13947,533.0064,0.177400,984.5732,802.0127,0.0,5,0.1911,5,0.1911,3.0,25,0.9554,9792,6314,241.2994,0.193942,9225.0,NaN,NaN,161.0,8.0,153,NaN,NaN,6.1529,3391.0,3661.0,63.0,3181.0,3783.0,72.0,210.0,-122.0,-9.0,0.0,2.0,0.0,0.0,0.0,0.0,5619.0,6224.0,99.0,4753.0,6202.0,113.0,866.0,22.0,-14.0,2.0,2.0,0.0,0.0,0.0,1.0,8003.0,8583.0,132.0,7323.0,8354.0,139.0,680.0,229.0,-7.0,4.0,2.0,1.0,1.0,2.0,2.0,9650.0,11514.0,161.0,9444.0,11169.0,175.0,206.0,345.0,-14.0,4.0,3.0,2.0,2.0,3.0,2.0
25574,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,3,Blue,mid,Knight,oe:player:ed29043422e3c515e1cb292464b990b,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Aurora,Orianna,Rumble,Ashe,Trundle,Azir,NaN,NaN,NaN,NaN,NaN,1570,0,5,2,2,11,13,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.4204,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,18913,722.7898,0.240565,808.3567,579.4395,5276.0,6,0.2293,15,0.5732,4.0,36,1.3758,11308,7830,299.2357,0.240511,10800.0,NaN,NaN,251.0,251.0,0,NaN,NaN,9.5924,3996.0,5062.0,93.0,3184.0,4566.0,84.0,812.0,496.0,9.0,2.0,0.0,0.0,0.0,0.0,2.0,6783.0,8229.0,153.0,4445.0,6730.0,117.0,2338.0,1499.0,36.0,4.0,0.0,0.0,0.0,0.0,3.0,8669.0,10682.0,203.0,6530.0,10209.0,169.0,2139.0,473.0,34.0,4.0,0.0,1.0,0.0,3.0,3.0,11151.0,13894.0,251.0,8181.0,12572.0,208.0,2970.0,1322.0,43.0,5.0,2.0,1.0,0.0,4.0,4.0
25575,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,4,Blue,bot,Viper,oe:player:9573154ad8bc9459b4c0d940315054f,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Ezreal,Orianna,Rumble,Ashe,Trundle,Azir,NaN,NaN,NaN,NaN,NaN,1570,0,2,2,5,11,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4204,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,21161,808.7006,0.269159,680.4841,362.0255,6054.0,14,0.5350,3,0.1146,5.0,22,0.8408,11957,8479,324.0382,0.260447,11508.0,NaN,NaN,256.0,252.0,4,NaN,NaN,9.7834,3347.0,3676.0,95.0,3822.0,3938.0,106.0,-475.0,-262.0,-11.0,0.0,0.0,0.0,0.0,0.0,0.0,5602.0,6019.0,137.0,6534.0,6511.0,156.0,-932.0,-492.0,-19.0,0.0,3.0,1.0,1.0,2.0,1.0,8137.0,9306.0,200.0,9898.0,9237.0,217.0,-1761.0,69.0,-17.0,0.0,4.0,1.0,2.0,3.0,2.0,11726.0,12660.0,256.0,12417.0,11456.0,271.0,-691.0,1204.0,-15.0,2.0,5.0,1.0,3.0,4.0,3.0
25576,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,5,Blue,sup,ON,oe:player:90651ebea9a35ec4e018c8157492e17,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Nami,Orianna,Rumble,Ashe,Trundle,Azir,NaN,NaN,NaN,NaN,NaN,1570,0,0,4,9,11,13,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4204,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,8634,329.9618,0.109821,591.0955,242.2166,276.0,45,1.7197,13,0.4968,12.0,102,3.8981,6699,3221,123.0955,0.098931,6715.0,NaN,NaN,21.0,21.0,0,NaN,NaN,0.8025,2397.0,2458.0,6.0,2304.0,2935.0,17.0,93.0,-477.0,-11.0,0.0,1.0,0.0,0.0,0.0,0.0,3878.0,3646.0,16.0,4089.0,4184.0,25.0,-211.0,-538.0,-9.0,0.0,4.0,2.0,1.0,2.0,0.0,5150.0,5470.0,19.0,5565.0,6059.0,28.0,-415.0,-589.0,-9.0,0.0,6.0,2.0,1.0,5.0,0.0,6495.0,7738.0,21.0,6812.0,7321.0,32.0,-317.0,417.0,-11.0,0.0,9.0,3.0,1.0,6.0,1.0
25577,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,6,Red,top,Clear,oe:player:d87853a5c1c5463889d70a62cdbcffc,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,1.0,Renekton,Nautilus,Gnar,Xin Zhao,Bard,Leona,NaN,NaN,NaN,NaN,NaN,1570,1,2,1,5,13,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4968,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19095,729.7452,0.250847,1188.4968,835.8344,8777.0,10,0.3822,4,0.1529,1.0,34,1.2994,11425,7947,303.7070,0.221867,10075.0,NaN,NaN,273.0,273.0,0,NaN,NaN,10.4331,3581.0,5349.0,95.0,3582.0,5348.0,100.0,-1.0,1.0,-5.0,0.0,0.0,0.0,0.0,0.0,0.0,5988.0,9103.0,156.0,5668.0,9666.0,161.0,320.0,-563.0,-5.0,1.0,0.0,1.0,0.0,2.0,0.0,8680.0,12094.0,203.0,7990.0,13246.0,221.0,690.0,-1152.0,-18.0,2.0,2.0,1.0,0.0,3.0,1.0,10804.0,15833.0,269.0,10048.0,16835.0,269.0,756.0,-1002.0,0.0,2.0,2.0,1.0,0.0,3.0,1.0
25578,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,7,Red,jng,Raptor,oe:player:637ed20b1e41be1c51bd1a4cb211357,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,1.0,Naafiri,Nautilus,Gnar,Xin Zhao,Bard,Leona,NaN,NaN,NaN,NaN,NaN,1570,1,2,2,5,13,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4968,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10164,388.4331,0.133523,926.9809,540.8025,3173.0,12,0.4586,8,0.3057,7.0,50,1.9108,10147,6669,254.8662,0.186185,9175.0,NaN,NaN,178.0,19.0,159,NaN,NaN,6.8025,3181.0,3783.0,72.0,3391.0,3661.0,63.0,-210.0,122.0,9.0,0.0,0.0,0.0,0.0,2.0,0.0,4753.0,6202.0,113.0,5619.0,6224.0,99.0,-866.0,-22.0,14.0,0.0,0.0,1.0,2.0,2.0,0.0,7323.0,8354.0,139.0,8003.0,8583.0,132.0,-680.0,-229.0,7.0,1.0,2.0,2.0,4.0,2.0,1.0,9444.0,11169.0,175.0,9650.0,11514.0,161.0,-206.0,-345.0,14.0,2.0,3.0,2.0,4.0,3.0,2.0

In [221]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)
fst_df

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25560,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,oe:player:d87853a5c1c5463889d70a62cdbcffc,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0.0,28,0.9444,10807,6902,232.7825,0.196186,9150.0,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25561,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,oe:player:637ed20b1e41be1c51bd1a4cb211357,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11.0,55,1.8550,12060,8155,275.0422,0.231800,11925.0,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25562,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,oe:player:d709285b163a94af9d819e568c592ba,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3.0,22,0.7420,10726,6821,230.0506,0.193883,10500.0,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25563,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,oe:player:178ec186b0d43d2669342596c2808cd,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4.0,38,1.2816,13565,9660,325.8010,0.274577,14010.0,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25564,LOLTMNT01_349243,complete,NaN,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,oe:player:b0ec3df39d61f953e7af0afd8eb8c4a,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11.0,127,4.2833,7548,3643,122.8668,0.103554,7675.0,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26491,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,8,Red,mid,Caps,oe:player:55dd587cdc4a278be6a5c37f9e539de,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Viktor,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,3,1,7,12,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21737,817.6928,0.370717,466.1944,503.7743,4885.0,10,0.3762,8,0.3009,4.0,34,1.2790,9911,6382,240.0752,0.207640,8950.0,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8025,3663.0,5182.0,88.0,3998.0,4788.0,88.0,-335.0,394.0,0.0,0.0,3.0,1.0,2.0,0.0,1.0,5931.0,8528.0,136.0,5265.0,6822.0,123.0,666.0,1706.0,13.0,2.0,6.0,1.0,2.0,0.0,3.0,7919.0,11264.0,194.0,7403.0,10065.0,181.0,516.0,1199.0,13.0,2.0,6.0,1.0,2.0,2.0,3.0,9607.0,13354.0,230.0,8976.0,14082.0,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26492,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,oe:player:c62a5235ad6bc113a1e64eb0e9aa8c8,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3.0,40,1.5047,12236,8707,327.5361,0.283289,11925.0,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26493,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,10,Red,sup,Labrov,oe:player:bb6ac5763c6576e104a7a2f59eb4ddf,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Rakan,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,0,2,9,12,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4537,170.6708,0.077377,507.0470,463.9749,0.0,47,1.7680,12,0.4514,11.0,105,3.9498,6496,2967,111.6113,0.096525,5920.0,NaN,NaN,24.0,24.0,0,NaN,NaN,0.9028,2504.0,1757.0,9.0,2550.0,2304.0,9.0,-46.0,-547.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0,3829.0,3936.0,15.0,3732.0,3230.0,19.0,97.0,706.0,-4.0,0.0,7.0,0.0,0.0,1.0,2.0,4971.0,4573.0,21.0,4980.0,4639.0,21.0,-9.0,-66.0,0.0,0.0,7.0,1.0,0.0,3.0,2.0,6161.0,6314.0,24.0,6268.0,7303.0,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26494,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,100,Blue,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Rumble,Maokai,Akali,Vi,Xayah,Alistar,Camille,Cassiopeia,1595,1,8,12,19,8,12,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3009,0.7524,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,NaN,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,0.0,1.0,7.0,1.0,1.0,1.0,25.0,12.0,1.0,0.0,57024,2145.1034,NaN,3055.0345,2666.2947,32895.0,102,3.8370,36,1.3542,28.0,254,9.5549,51682,34035,1280.3135,NaN,45223.0,-0.025218,-0.18,NaN,813.0,185,NaN,NaN,37.5423,17356.0,20681.0,372.0,17656.0,19713.0,330.0,-300.0,968.0,42.0,2.0,2.0,4.0,4.0,9.0,2.0,25357.0,31403.0,558.0,28580.0,34561.0,520.0,-3223.0,-3158.0,38.0,2.0,2.0,10.0,10.0,20.0,2.0,36649.0,45707.0,786.0,37537.0,46378.0,745.0,-888.0,-671.0,41.0,4.0,7.0,10.0,10.0,20.0,4.0,46187.0,62098.0,979.0,46122.0,57751.0,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26495,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26.0,252,9.4796,48381,30734,1156.1379,NaN,46378.0,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [222]:
df.isnull().sum().sort_values(ascending=False).head(20)

dragons (type unknown)     111696
monsterkillsownjungle      110316
monsterkillsenemyjungle    110316
url                        103632
atakhans                    96398
opp_atakhans                96398
firstbaron                  93720
firstherald                 93594
firstmidtower               93588
hextechs                    93578
chemtechs                   93578
clouds                      93578
oceans                      93578
opp_elementaldrakes         93578
elementaldrakes             93578
opp_elders                  93578
elders                      93578
mountains                   93578
gpr                         93578
turretplates                93578
dtype: int64

In [223]:
df['dragons (type unknown)'].isnull().sum()

np.int64(111696)

In [224]:
df = df.drop(columns=['dragons (type unknown)'])

In [225]:
df = df.drop(columns=['url'])

In [226]:
df.isnull().sum().sort_values(ascending=False).head(20)

monsterkillsenemyjungle    110316
monsterkillsownjungle      110316
atakhans                    96398
opp_atakhans                96398
firstbaron                  93720
firstherald                 93594
firstmidtower               93588
infernals                   93578
hextechs                    93578
oceans                      93578
clouds                      93578
elementaldrakes             93578
mountains                   93578
turretplates                93578
elders                      93578
opp_elders                  93578
opp_elementaldrakes         93578
gpr                         93578
opp_turretplates            93578
chemtechs                   93578
dtype: int64

In [227]:
df = df.drop(columns=['atakhans'])

In [228]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'playerid',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [229]:
df['playerid'].sample()

30776    oe:player:e2c655411d8d95ef73d8026704f5e7a
Name: playerid, dtype: str

In [230]:
df['playerid'].sample(5)

61717    oe:player:1a75a7cf8c98442be881fed562346f5
96486    oe:player:662e402075e397e4afaea9c752cec96
62067    oe:player:7db16a4ce881aecec2bfeb3e0c74188
59714    oe:player:3b7bd1331d5adaaedf5a228b02fa077
40057    oe:player:1a75a7cf8c98442be881fed562346f5
Name: playerid, dtype: str

In [231]:
df = df.drop(columns=['playerid'])

In [232]:
df['datacompleteness'].sample(100)

56432     complete
56163     complete
34358     complete
101360    complete
2125      complete
91520     complete
47966     complete
37775     complete
106376    complete
52058     complete
45951     complete
93338     complete
110799    complete
47013     complete
21684     complete
80784     complete
80373     complete
36368     complete
86236     complete
17676     complete
7977      complete
40291     complete
15855     complete
89324     complete
73001     complete
15819     complete
74880     complete
91616     complete
14064     complete
50001     complete
6689      complete
64695     complete
25211     complete
107081    complete
75044     complete
104916    complete
10931     complete
101609    complete
34839     complete
81243     complete
4411      complete
13259     complete
3707      complete
22470     complete
6744      complete
107321    complete
76402     complete
16743     complete
8268      complete
37928     complete
92654     complete
6533      complete
111412    complete
55886     complete
95248     complete
4721      complete
60856     complete
57438     complete
8622      complete
46249     complete
95695     complete
93155     complete
49328     complete
45754     complete
40994     complete
26002     complete
86692     complete
76737     complete
71686     complete
111052    complete
16674     complete
43611     complete
6652      complete
105226    complete
23185     complete
3018      complete
47934     complete
89590     complete
46593     complete
81234     complete
72364     complete
95431     complete
84770     complete
26140     complete
103374    complete
95914     complete
102950    complete
92659     complete
37422     complete
88593     complete
62366     complete
63321     complete
25812     complete
84068     complete
32323     complete
83615     complete
60381     complete
36540     complete
62497     complete
50583     complete
Name: datacompleteness, dtype: str

In [233]:
df['datacompleteness'].unique()

<StringArray>
['partial', 'complete']
Length: 2, dtype: str

In [234]:
df['datacompleteness'].value_counts()

datacompleteness
complete    110352
partial       1620
Name: count, dtype: int64

In [235]:
df = df[df['datacompleteness'] == 'complete']

In [236]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [237]:
df.info()

<class 'pandas.DataFrame'>
Index: 110352 entries, 36 to 111971
Columns: 161 entries, gameid to opp_deathsat25
dtypes: float64(122), int64(18), str(21)
memory usage: 136.4 MB

In [238]:
fst_df.info()

<class 'pandas.DataFrame'>
Index: 540 entries, 25560 to 26495
Columns: 165 entries, gameid to opp_deathsat25
dtypes: float64(124), int64(18), str(23)
memory usage: 700.3 KB

In [239]:
fst_df.sample(15)

,gameid,datacompleteness,url,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,playerid,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,dragons (type unknown),elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,atakhans,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25634,LOLTMNT01_349329,complete,NaN,FST,2026,NaN,0,2026-03-16 18:15:35,2,16.05,3,Blue,mid,Caps,oe:player:55dd587cdc4a278be6a5c37f9e539de,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Galio,Orianna,Ryze,Nocturne,Renekton,Trundle,NaN,NaN,NaN,NaN,NaN,2004,1,3,4,13,21,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6287,1.1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,25315,757.9341,0.228646,984.1916,1240.0000,3489.0,10,0.2994,6,0.1796,7.0,46,1.3772,12188,7824,234.2515,0.175462,11425.0,NaN,NaN,257.0,257.0,0,NaN,NaN,7.6946,3157.0,4288.0,70.0,3935.0,4607.0,76.0,-778.0,-319.0,-6.0,0.0,3.0,2.0,2.0,2.0,3.0,5014.0,7226.0,121.0,5775.0,7405.0,131.0,-761.0,-179.0,-10.0,0.0,7.0,2.0,2.0,2.0,3.0,6964.0,10164.0,174.0,8040.0,10425.0,178.0,-1076.0,-261.0,-4.0,1.0,7.0,3.0,3.0,5.0,3.0,8333.0,11592.0,197.0,9854.0,12718.0,226.0,-1521.0,-1126.0,-29.0,1.0,8.0,4.0,3.0,6.0,3.0
25582,LOLTMNT01_350155,complete,NaN,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,100,Blue,team,NaN,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Rumble,Ashe,Trundle,Azir,Ezreal,Pantheon,Sion,Nami,Aurora,1570,0,11,13,22,11,13,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4204,0.9172,0.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,0.0,0.0,2.0,7.0,0.0,0.0,20.0,31.0,0.0,1.0,78619,3004.5478,NaN,3873.8217,3978.4204,16318.0,78,2.9809,42,1.6051,27.0,213,8.1401,49946,32554,1244.1019,NaN,47923.0,0.048145,0.60,NaN,801.0,157,NaN,NaN,36.6115,16713.0,20205.0,357.0,16072.0,20571.0,374.0,641.0,-366.0,-17.0,2.0,3.0,0.0,0.0,0.0,2.0,27550.0,33784.0,566.0,25809.0,32730.0,567.0,1741.0,1054.0,-1.0,6.0,11.0,3.0,3.0,4.0,6.0,37949.0,47287.0,775.0,37996.0,45953.0,756.0,-47.0,1334.0,19.0,8.0,15.0,6.0,6.0,15.0,8.0,49070.0,62641.0,958.0,47658.0,58351.0,955.0,1412.0,4290.0,3.0,11.0,22.0,8.0,8.0,19.0,11.0
26216,LOLTMNT01_352425,complete,NaN,FST,2026,NaN,0,2026-03-21 14:58:22,3,16.05,9,Red,bot,Ruler,oe:player:eada4723af6f51cf2391d85b5fde49b,Gen.G,oe:team:50f58982d91a36557ec8aec52ab014f,1.0,Yunara,Karma,Bard,Caitlyn,Aphelios,Syndra,NaN,NaN,NaN,NaN,NaN,1815,0,1,2,2,3,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0992,0.6281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,10746,355.2397,0.165977,532.0331,301.8182,1433.0,14,0.4628,10,0.3306,5.0,46,1.5207,13243,9265,306.2810,0.287512,13355.0,NaN,NaN,318.0,309.0,9,NaN,NaN,10.5124,3349.0,3239.0,91.0,3351.0,3408.0,95.0,-2.0,-169.0,-4.0,0.0,0.0,0.0,0.0,0.0,0.0,6227.0,5659.0,151.0,5851.0,5756.0,150.0,376.0,-97.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,8328.0,8170.0,208.0,8482.0,8625.0,214.0,-154.0,-455.0,-6.0,0.0,1.0,0.0,1.0,0.0,0.0,10563.0,10693.0,266.0,10624.0,11025.0,272.0,-61.0,-332.0,-6.0,0.0,2.0,1.0,1.0,1.0,1.0
25758,LOLTMNT01_349770,complete,NaN,FST,2026,NaN,0,2026-03-18 13:11:19,1,16.05,7,Red,jng,SkewMond,oe:player:ab15060e5225b51592cd04b3aed1e09,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Vi,Varus,Karma,Jarvan IV,Seraphine,Alistar,NaN,NaN,NaN,NaN,NaN,1973,0,2,3,3,8,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2433,0.7299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10152,308.7278,0.113314,813.8469,1074.5261,0.0,10,0.3041,21,0.6386,9.0,72,2.1896,11685,7384,224.5514,0.207754,11375.0,NaN,NaN,241.0,28.0,213,NaN,NaN,7.3289,3658.0,4560.0,91.0,3670.0,4463.0,82.0,-12.0,97.0,9.0,0.0,0.0,0.0,0.0,1.0,0.0,5379.0,6514.0,123.0,5218.0,7133.0,118.0,161.0,-619.0,5.0,1.0,0.0,0.0,0.0,1.0,0.0,7101.0,9097.0,168.0,7195.0,9905.0,165.0,-94.0,-808.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,9445.0,11440.0,202.0,8955.0,12350.0,205.0,490.0,-910.0,-3.0,2.0,1.0,1.0,0.0,2.0,1.0
25962,LOLTMNT01_352208,complete,NaN,FST,2026,NaN,0,2026-03-20 17:46:57,3,16.05,7,Red,jng,JunJia,oe:player:a22a6d1fe8786cf83675e2d932fbffe,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,Vi,Poppy,Lulu,Pantheon,Viego,Maokai,NaN,NaN,NaN,NaN,NaN,1785,1,1,4,9,17,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5714,0.7731,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,8209,275.9328,0.115188,783.8319,948.7731,0.0,14,0.4706,5,0.1681,10.0,46,1.5462,10720,6803,228.6723,0.156661,9400.0,NaN,NaN,200.0,5.0,195,NaN,NaN,6.7227,3572.0,4129.0,76.0,3500.0,4441.0,83.0,72.0,-312.0,-7.0,0.0,1.0,0.0,0.0,0.0,0.0,5007.0,6277.0,108.0,5616.0,7768.0,140.0,-609.0,-1491.0,-32.0,0.0,1.0,1.0,0.0,1.0,0.0,7216.0,8934.0,149.0,7558.0,10853.0,191.0,-342.0,-1919.0,-42.0,1.0,1.0,1.0,0.0,1.0,0.0,8815.0,11206.0,175.0,9858.0,13284.0,230.0,-1043.0,-2078.0,-55.0,1.0,5.0,3.0,1.0,2.0,1.0
25717,LOLTMNT01_350472,complete,NaN,FST,2026,NaN,0,2026-03-17 17:21:45,3,16.05,2,Blue,jng,Inspired,oe:player:a8307167f3a1c933295bb9e3d43700e,LYON,oe:team:da1143bf9a245b78a8dc86417de85b3,0.0,Wukong,Orianna,Vi,Ambessa,Rakan,Karma,NaN,NaN,NaN,NaN,NaN,1835,1,3,0,6,12,4,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.3924,0.5232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12171,397.9619,0.141223,804.1308,683.6076,8059.0,10,0.3270,15,0.4905,5.0,64,2.0926,13528,9509,310.9210,0.229903,11208.0,NaN,NaN,262.0,28.0,234,NaN,NaN,8.5668,3457.0,4353.0,82.0,3349.0,3887.0,68.0,108.0,466.0,14.0,0.0,0.0,0.0,0.0,0.0,0.0,5629.0,7196.0,128.0,5452.0,6572.0,115.0,177.0,624.0,13.0,1.0,0.0,0.0,0.0,0.0,1.0,7471.0,9670.0,171.0,7582.0,9412.0,151.0,-111.0,258.0,20.0,1.0,0.0,0.0,1.0,0.0,1.0,10047.0,13054.0,214.0,9808.0,12274.0,199.0,239.0,780.0,15.0,2.0,1.0,0.0,1.0,0.0,2.0
25894,LOLTMNT01_352019,complete,NaN,FST,2026,NaN,0,2026-03-19 17:11:10,3,16.05,100,Blue,team,NaN,NaN,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,0.0,NaN,Orianna,Ryze,Qiyana,Galio,Trundle,Corki,Nami,Jax,Poppy,Hwei,1258,1,19,7,34,19,7,5.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.9062,1.2401,1.0,3.0,0.0,3.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,NaN,0.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,9.0,0.0,1.0,1.0,35.0,5.0,2.0,0.0,64011,3052.9889,NaN,2777.1224,2376.3911,36902.0,69,3.2909,28,1.3355,19.0,185,8.8235,46142,31932,1522.9889,NaN,40276.0,0.256485,4.91,NaN,631.0,145,NaN,NaN,37.0111,18814.0,21200.0,368.0,15930.0,19884.0,335.0,2884.0,1316.0,33.0,5.0,9.0,1.0,1.0,1.0,5.0,31329.0,35358.0,579.0,23655.0,30272.0,480.0,7674.0,5086.0,99.0,12.0,19.0,3.0,3.0,3.0,12.0,43587.0,47488.0,751.0,31513.0,41370.0,640.0,12074.0,6118.0,111.0,17.0,30.0,4.0,4.0,6.0,17.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25841,LOLTMNT01_350979,complete,NaN,FST,2026,NaN,0,2026-03-19 13:58:41,2,16.05,6,Red,top,Dhokla,oe:player:5385f74da3e5deb5b66d9a1ee56cf97,LYON,oe:team:da1143bf9a245b78a8dc86417de85b3,0.0,Aurora,Ryze,Rumble,Pantheon,Nami,Alistar,NaN,NaN,NaN,NaN,NaN,1554,0,0,3,1,9,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3475,1.0425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15158,585.2510,0.233387,746.1390,428.5328,7123.0,9,0.3475,1,0.0386,0.0,23,0.8880,8692,5246,202.5483,0.172885,8600.0,NaN,NaN,231.0,231.0,0,NaN,NaN,8.9189,2932.0,4653.0,72.0,3616.0,5738.0,79.0,-684.0,-1085.0,-7.0,0.0,0.0,2.0,1.0,1.0,0.0,4322.0,7548.0,105.0,6228.0,10020.0,132.0,-1906.0,-2472.0,-27.0,0.0,1.0,3.0,3.0,1.0,1.0,6566.0,11333.0,166.0,7944.0,12823.0,181.0,-1378.0,-1490.0,-15.0,0.0,1.0,3.0,3.0,1.0,2.0,8564.0,14889.0,230.0,11469.0,17101.0,226.0,-2905.0,-2212.0,4.0,0.0,1.0,3.0,7.0,3.0,2.0
25928,LOLTMNT01_351223,complete,NaN,FST,2026,NaN,0,2026-03-20 14:57:42,3,16.05,9,Red,bot,Diable,oe:player:178ec186b0d43d2669342596c2808cd,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,1.0,Varus,Ambessa,Ziggs,Bard,Aurora,Annie,NaN,NaN,NaN,NaN,NaN,1830,0,4,5,0,7,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2295,1.0164,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19040,624.2623,0.233328,551.5738,259.0492,1392.0,16,0.5246,7,0.2295,6.0,33,1.0820,12058,8049,263.9016,0.246787,11650.0,NaN,NaN,256.0,256.0,0,NaN,NaN,8.3934,3630.0,3852.0,87.0,3854.0,3886.0,96.0,-224.0,-34.0,-9.0,1.0,0.0,0.0,1.0,1.0,1.0,5669.0,6500.0,146.0,6832.0,6616.0,142.0,-1163.0,-116.0,4.0,1.0,0.0,1.0,2.0,6.0,1.0,7950.0,8671.0,194.0,9544.0,9656.0,207.0,-1594.0,-985.0,-13.0,2.0,0.0,2.0,2.0,8.0,1.0,10141.0,10545.0,236.0,13046.0,12555.0,262.0,-2905.0,-2010.0,-26.0,3.0,0.0,3.0,4.0,10.0,1.0
25910,LOLTMNT01_351218,complete,NaN,FST,2026,NaN,0,2026-03-20 14:01:48,2,16.05,3,Blue,mid,Caps,oe:player:55dd587cdc4a278be6a5c37f9e539de,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Azir,Orianna,Ryze,Karma,Ezreal,Lucian,NaN,NaN,NaN,NaN,NaN,2187,1,3,7,8,28,24,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.7682,1.3992,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,27378,751.1111,0.216771,811.8244,553.1687,2438.0,14,0.3841,10,0.2743,5.0,41,1.1248,12205,7468,204.8834,0.146973,10235.0,NaN,NaN,256.0,246.0,10,NaN,NaN,7.0233,3791.0,4754.0,90.0,3527.0,4770.0,94.0,264.0,-16.0,-4.0,1.0,1.0,1.0,0.0,1.0,2.0,5101.0,6490.0,121.0,5937.0,7686.0,141.0,-836.0,-1196.0,-20.0,1.0,2.0,3.0,2.0,3.0,3.0,6676.0,8870.0,167.0,8619.0,11004.0,201.0,-1943.0,-2134.0,-34.0,1.0,2.0,4.0,4.0,4.0,3.0,7974.0,10722.0,199.0,10752.0,14028.0,249.0,-2778.0,-3306.0,-50.0,1.0,2.0,5.0,4.0,6.0,4.0
26492,LOLTMNT01_352610,complete,NaN,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,oe:player:c62a5235ad6bc113a1e64eb0e9aa8c8,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3.0,40,1.5047,12236,8707,327.5361,0.283289,11925.0,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26235,LOLTMNT01_351479,complete,NaN,FST,2026,NaN,0,2026-03-21 16:45:59,2,16.05,4,Blue,bot,Viper,oe:player:9573154ad8bc9459b4c0d940315054f,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Yunara,Rumble,Karma,Ryze,Rakan,Kalista,NaN,NaN,NaN,NaN,NaN,1787,1,3,1,5,15,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5036,0.7387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,19112,641.7012,0.230107,514.6167,285.9317,13465.0,19,0.6379,10,0.3358,8.0,43,1.4438,15288,11367,381.6564,0.274255,12150.0,NaN,NaN,314.0,303.0,11,NaN,NaN,10.5428,3211.0,3511.0,84.0,4546.0,3596.0,111.0,-1335.0,-85.0,-27.0,0.0,0.0,0.0,2.0,0.0,0.0,5956.0,6206.0,142.0,7499.0,6294.0,174.0,-1543.0,-88.0,-32.0,1.0,0.0,1.0,2.0,0.0,0.0,8723.0,9187.0,206.0,9963.0,8850.0,243.0,-1240.0,337.0,-37.0,2.0,0.0,1.0,2.0,0.0,0.0,11376.0,12000.0,274.0,12362.0,11669.0,313.0,-986.0,331.0,-39.0,2.0,1.0,1.0,2.0,1.0,0.0
26237,LOLTMNT01_351479,complete,NaN,FST,2026,NaN,0,2026-03-21 16:45:59,2,16.05,6,Red,top,Xiaoxu,oe:player:8007ba25dee37ac1e4445a6e9f8d252,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,Renekton,Seraphine,Pantheon,Lulu,Xin Zhao,Annie,NaN,NaN,NaN,NaN,NaN,1787,0,1,5,1,7,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2350,0.7387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,14925,501.1192,0.240060,1150.2071,948.6849,1725.0,13,0.4365,2,0.0672,2.0,25,0.8394,9592,5671,190.4085,0.177568,9380.0,NaN,NaN,246.0,236.0,10,NaN,NaN,8.2597,3602.0,5044.0,99.0,3505.0,5075.0,84.0,97.0,-31.0,15.0,0.0,0.0,0.0,1.0,0.0,0.0,4998.0,7808.0,128.0,5573.0,9025.0,135.0,-575.0,-1217.0,-7.0,0.0,1.0,3.0,2.0,1.0,0.0,6554.0,10508.0,171.0,7339.0,12478.0,188.0,-785.0,-1970.0,-17.0,0.0,1.0,3.0,2.0,2.0,0.0,8515.0,13778.0,224.0,8938.0,15408.0,229.0,-423.0,-1630.0,-5.0,1.0,1.0,3.0,2.0,3.0,0.0
25685,LOLTMNT01_349529,complete,NaN,FST,2026,NaN,0,2026-03-17 14:43:27,3,16.05,6,Red,top,Xiaoxu,oe:player:8007ba25dee37ac1e4445a6e9f8d252,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,Zaahen,Varus,Neeko,Galio,Nautilus,Renata Glasc,NaN,NaN,NaN,NaN,NaN,1794,0,1,4,3,9,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3010,0.8027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,18870,631.1037,0.245646,1125.4515,1020.2676,10341.0,18,0.6020,10,0.3344,5.0,61,2.0401,9812,5877,196.5552,0.183369,9608.0,NaN,NaN,232.0,232.0,0,NaN,NaN,7.7592,3210.0,4728.0,83.0,3306.0,4943.0,81.0,-96.0,-215.0,2.0,0.0,0.0,1.0,0.0,1.0,1.0,4535.0,8032.0,121.0,5404.0,8929.0,137.0,-869.0,-897.0,-16.0,0.0,0.0,2.0,0.0,2.0,1.0,6918.0,11308.0,163.0,6803.0,10891.0,170.0,115.0,417.0,-7.0,1.0,1.0,2.0,0.0,2.0,3.0,8290.0,13653.0,195.0,9333.0,15128.0,211.0,-1043.0,-1475.0,-16.0,1.0,2.0,3.0,2.0,3.0,3.0
25891,LOLTMNT01_352019,complete,NaN,FST,2026,NaN,0,2026-03-19 17:11:10,3,16.05,8,Red,mid,Envy,oe:player:a672b5bc1c212a6922418fad18734c1,LOUD,oe:team:658a021a796aa5501503220adb38cf4,1.0,Annie,Jarvan IV,Pantheon,Varus,Dr. Mundo,LeBlanc,NaN,NaN,NaN,NaN,NaN,1258,0,2,2,2,7,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3339,1.2401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,8403,400.7790,0.197527,477.7583,262.2258,402.0,8,0.3816,3,0.1431,2.0,15,0.7154,7197,4355,207.7107,0.203343,7100.0,NaN,NaN,173.0,173.0,0,NaN,NaN,8.2512,3171.0,4982.0,80.0,4332.0,5446.0,104.0,-1161.0,-464.0,-24.0,0.0,0.0,1.0,1.0,2.0,0.0,4571.0,7311.0,124.0,7553.0,8900.0,172.0,-2982.0,-1589.0,-48.0,0.0,0.0,1.0,3.0,2.0,0.0,6578.0,9868.0,172.0,10101.0,11380.0,222.0,-3523.0,-1512.0,-50.0,1.0,0.0,2.0,3.0,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [240]:
fst_df = df[df['league'] == 'FST']
fst_df

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25560,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0.0,28,0.9444,10807,6902,232.7825,0.196186,9150.0,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25561,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11.0,55,1.8550,12060,8155,275.0422,0.231800,11925.0,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25562,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3.0,22,0.7420,10726,6821,230.0506,0.193883,10500.0,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25563,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4.0,38,1.2816,13565,9660,325.8010,0.274577,14010.0,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25564,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11.0,127,4.2833,7548,3643,122.8668,0.103554,7675.0,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26491,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,8,Red,mid,Caps,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Viktor,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,3,1,7,12,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21737,817.6928,0.370717,466.1944,503.7743,4885.0,10,0.3762,8,0.3009,4.0,34,1.2790,9911,6382,240.0752,0.207640,8950.0,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8025,3663.0,5182.0,88.0,3998.0,4788.0,88.0,-335.0,394.0,0.0,0.0,3.0,1.0,2.0,0.0,1.0,5931.0,8528.0,136.0,5265.0,6822.0,123.0,666.0,1706.0,13.0,2.0,6.0,1.0,2.0,0.0,3.0,7919.0,11264.0,194.0,7403.0,10065.0,181.0,516.0,1199.0,13.0,2.0,6.0,1.0,2.0,2.0,3.0,9607.0,13354.0,230.0,8976.0,14082.0,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26492,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3.0,40,1.5047,12236,8707,327.5361,0.283289,11925.0,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26493,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,10,Red,sup,Labrov,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Rakan,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,0,2,9,12,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4537,170.6708,0.077377,507.0470,463.9749,0.0,47,1.7680,12,0.4514,11.0,105,3.9498,6496,2967,111.6113,0.096525,5920.0,NaN,NaN,24.0,24.0,0,NaN,NaN,0.9028,2504.0,1757.0,9.0,2550.0,2304.0,9.0,-46.0,-547.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0,3829.0,3936.0,15.0,3732.0,3230.0,19.0,97.0,706.0,-4.0,0.0,7.0,0.0,0.0,1.0,2.0,4971.0,4573.0,21.0,4980.0,4639.0,21.0,-9.0,-66.0,0.0,0.0,7.0,1.0,0.0,3.0,2.0,6161.0,6314.0,24.0,6268.0,7303.0,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26494,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,100,Blue,team,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Rumble,Maokai,Akali,Vi,Xayah,Alistar,Camille,Cassiopeia,1595,1,8,12,19,8,12,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3009,0.7524,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,7.0,1.0,1.0,1.0,25.0,12.0,1.0,0.0,57024,2145.1034,NaN,3055.0345,2666.2947,32895.0,102,3.8370,36,1.3542,28.0,254,9.5549,51682,34035,1280.3135,NaN,45223.0,-0.025218,-0.18,NaN,813.0,185,NaN,NaN,37.5423,17356.0,20681.0,372.0,17656.0,19713.0,330.0,-300.0,968.0,42.0,2.0,2.0,4.0,4.0,9.0,2.0,25357.0,31403.0,558.0,28580.0,34561.0,520.0,-3223.0,-3158.0,38.0,2.0,2.0,10.0,10.0,20.0,2.0,36649.0,45707.0,786.0,37537.0,46378.0,745.0,-888.0,-671.0,41.0,4.0,7.0,10.0,10.0,20.0,4.0,46187.0,62098.0,979.0,46122.0,57751.0,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26495,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26.0,252,9.4796,48381,30734,1156.1379,NaN,46378.0,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [241]:
fst_df.info()

<class 'pandas.DataFrame'>
Index: 540 entries, 25560 to 26495
Columns: 161 entries, gameid to opp_deathsat25
dtypes: float64(122), int64(18), str(21)
memory usage: 683.4 KB

In [242]:
fst_df.sample(540)

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
26495,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26.0,252,9.4796,48381,30734,1156.1379,NaN,46378.0,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0
25833,LOLTMNT01_351028,complete,FST,2026,NaN,0,2026-03-19 13:11:55,1,16.05,10,Red,sup,Duro,Gen.G,oe:team:50f58982d91a36557ec8aec52ab014f,1.0,Seraphine,Karma,Pantheon,Rumble,Akali,Gnar,NaN,NaN,NaN,NaN,NaN,1528,1,3,1,10,17,3,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.6675,0.7853,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7167,281.4267,0.088118,320.6937,231.5969,1621.0,44,1.7277,7,0.2749,7.0,92,3.6126,7885,4492,176.3874,0.122411,6480.0,NaN,NaN,13.0,13.0,0,NaN,NaN,0.5105,2947.0,3305.0,6.0,2283.0,2870.0,15.0,664.0,435.0,-9.0,1.0,1.0,0.0,0.0,0.0,2.0,3996.0,4320.0,7.0,3404.0,4392.0,25.0,592.0,-72.0,-18.0,1.0,1.0,0.0,0.0,1.0,2.0,5653.0,5580.0,9.0,4342.0,5576.0,25.0,1311.0,4.0,-16.0,2.0,2.0,0.0,0.0,1.0,3.0,7636.0,8414.0,12.0,5451.0,6866.0,27.0,2185.0,1548.0,-15.0,3.0,10.0,1.0,0.0,3.0,5.0
25804,LOLTMNT01_350716,complete,FST,2026,NaN,0,2026-03-18 16:36:59,2,16.05,5,Blue,sup,Bie,Team Secret Whales,oe:team:740de582f50775c516c77ed7b923fd5,0.0,Nautilus,Ashe,Lulu,Rumble,Braum,Kai'Sa,NaN,NaN,NaN,NaN,NaN,1622,0,0,3,6,12,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4439,1.2577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5060,187.1763,0.073628,647.3859,957.0777,0.0,49,1.8126,5,0.1850,5.0,94,3.4772,5869,2285,84.5253,0.082421,5635.0,NaN,NaN,29.0,29.0,0,NaN,NaN,1.0727,2263.0,3094.0,18.0,2354.0,2883.0,13.0,-91.0,211.0,5.0,0.0,0.0,0.0,0.0,0.0,0.0,3332.0,4226.0,23.0,3672.0,4356.0,18.0,-340.0,-130.0,5.0,0.0,2.0,1.0,0.0,3.0,1.0,4455.0,5800.0,25.0,5029.0,6030.0,19.0,-574.0,-230.0,6.0,0.0,5.0,2.0,0.0,6.0,2.0,5469.0,6702.0,28.0,6761.0,8748.0,20.0,-1292.0,-2046.0,8.0,0.0,6.0,3.0,0.0,13.0,2.0
26201,LOLTMNT01_352417,complete,FST,2026,NaN,0,2026-03-21 14:05:13,2,16.05,6,Red,top,Kiin,Gen.G,oe:team:50f58982d91a36557ec8aec52ab014f,1.0,Vayne,Karma,Bard,Caitlyn,Jarvan IV,Jax,NaN,NaN,NaN,NaN,NaN,1935,0,2,4,3,6,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1860,0.6512,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,25521,791.3488,0.330224,730.6357,519.8140,6011.0,17,0.5271,8,0.2481,4.0,55,1.7054,11838,7615,236.1240,0.201295,11450.0,NaN,NaN,265.0,265.0,0,NaN,NaN,8.2171,3476.0,5118.0,91.0,3000.0,4268.0,66.0,476.0,850.0,25.0,0.0,0.0,0.0,0.0,0.0,0.0,5211.0,8534.0,139.0,4666.0,8255.0,118.0,545.0,279.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,6947.0,11549.0,181.0,6447.0,11390.0,169.0,500.0,159.0,12.0,0.0,1.0,1.0,0.0,1.0,1.0,8082.0,13088.0,203.0,9188.0,15477.0,201.0,-1106.0,-2389.0,2.0,0.0,1.0,3.0,1.0,6.0,1.0
25579,LOLTMNT01_350155,complete,FST,2026,NaN,0,2026-03-16 14:00:50,2,16.05,8,Red,mid,VicLa,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,1.0,Annie,Nautilus,Gnar,Xin Zhao,Bard,Leona,NaN,NaN,NaN,NaN,NaN,1570,1,0,4,9,13,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.4968,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15299,584.6752,0.200980,588.9554,379.7580,2444.0,12,0.4586,3,0.1146,4.0,23,0.8790,8913,5435,207.7070,0.151732,7950.0,NaN,NaN,209.0,209.0,0,NaN,NaN,7.9873,3184.0,4566.0,84.0,3996.0,5062.0,93.0,-812.0,-496.0,-9.0,0.0,0.0,2.0,2.0,0.0,0.0,4445.0,6730.0,117.0,6783.0,8229.0,153.0,-2338.0,-1499.0,-36.0,0.0,0.0,3.0,4.0,0.0,0.0,6530.0,10209.0,169.0,8669.0,10682.0,203.0,-2139.0,-473.0,-34.0,0.0,3.0,3.0,4.0,0.0,1.0,8181.0,12572.0,208.0,11151.0,13894.0,251.0,-2970.0,-1322.0,-43.0,0.0,4.0,4.0,5.0,2.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
25863,LOLTMNT01_351065,complete,FST,2026,NaN,0,2026-03-19 15:35:17,1,16.05,4,Blue,bot,GALA,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,Ezreal,Ambessa,Jarvan IV,Ryze,Varus,Sivir,NaN,NaN,NaN,NaN,NaN,1756,1,4,0,4,10,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3417,0.5467,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,26006,888.5877,0.353958,494.1800,345.6150,13079.0,13,0.4442,10,0.3417,8.0,39,1.3326,15252,11394,389.3166,0.266781,13833.0,NaN,NaN,342.0,322.0,20,NaN,NaN,11.6856,3788.0,3742.0,106.0,3269.0,3594.0,85.0,519.0,148.0,21.0,0.0,0.0,0.0,0.0,0.0,0.0,6600.0,6300.0,167.0,5262.0,5693.0,135.0,1338.0,607.0,32.0,0.0,2.0,0.0,0.0,0.0,1.0,9514.0,9085.0,231.0,7545.0,8042.0,201.0,1969.0,1043.0,30.0,1.0,2.0,0.0,0.0,1.0,1.0,11831.0,11979.0,303.0,9514.0,10482.0,258.0,2317.0,1497.0,45.0,1.0,2.0,0.0,0.0,1.0,1.0
25885,LOLTMNT01_352019,complete,FST,2026,NaN,0,2026-03-19 17:11:10,3,16.05,2,Blue,jng,JunJia,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,0.0,Poppy,Orianna,Ryze,Qiyana,Galio,Trundle,NaN,NaN,NaN,NaN,NaN,1258,1,6,1,6,19,7,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.9062,1.2401,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9681,461.7329,0.151240,814.2925,879.0620,7234.0,8,0.3816,9,0.4293,4.0,41,1.9555,9486,6644,316.8839,0.208067,7700.0,NaN,NaN,153.0,20.0,133,NaN,NaN,7.2973,4765.0,4469.0,80.0,3789.0,4060.0,78.0,976.0,409.0,2.0,4.0,0.0,0.0,1.0,0.0,1.0,7288.0,7579.0,121.0,5429.0,6102.0,103.0,1859.0,1477.0,18.0,6.0,3.0,0.0,1.0,2.0,4.0,9219.0,10092.0,152.0,6920.0,8403.0,135.0,2299.0,1689.0,17.0,6.0,6.0,0.0,1.0,3.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
25673,LOLTMNT01_350440,complete,FST,2026,NaN,0,2026-03-17 13:57:55,2,16.05,6,Red,top,Xiaoxu,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,Renekton,Nocturne,Varus,Ambessa,Nautilus,Neeko,NaN,NaN,NaN,NaN,NaN,1467,0,2,3,2,7,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.2863,0.9407,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10845,443.5583,0.252438,969.8160,942.2495,1175.0,11,0.4499,3,0.1227,3.0,29,1.1861,8929,5661,231.5337,0.219411,8475.0,NaN,NaN,245.0,245.0,0,NaN,NaN,10.0204,3368.0,5025.0,95.0,3808.0,5536.0,102.0,-440.0,-511.0,-7.0,0.0,0.0,1.0,0.0,1.0,1.0,5494.0,9644.0,153.0,5488.0,8848.0,151.0,6.0,796.0,2.0,1.0,0.0,1.0,0.0,1.0,2.0,7759.0,13018.0,217.0,8035.0,12283.0,214.0,-276.0,735.0,3.0,2.0,1.0,1.0,0.0,1.0,2.0,8929.0,14851.0,245.0,10532.0,15880.0,244.0,-1603.0,-1029.0,1.0,2.0,2.0,3.0,0.0,7.0,2.0
25808,LOLTMNT01_350716,complete,FST,2026,NaN,0,2026-03-18 16:36:59,2,16.05,9,Red,bot,Diable,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,1.0,Kalista,Akali,Jarvan IV,Ryze,Xayah,Yunara,NaN,NaN,NaN,NaN,NaN,1622,1,6,3,9,22,13,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8138,1.2577,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,30414,1125.0555,0.282963,721.7756,536.6338,7932.0,16,0.5919,12,0.4439,6.0,50,1.8496,14190,10606,392.3305,0.257493,12800.0,NaN,NaN,265.0,258.0,7,NaN,NaN,9.8027,3620.0,3547.0,100.0,3427.0,3342.0,92.0,193.0,205.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,6473.0,5586.0,148.0,5717.0,5452.0,143.0,756.0,134.0,5.0,2.0,2.0,1.0,0.0,3.0,1.0,9139.0,8215.0,199.0,8378.0,8184.0,200.0,761.0,31.0,-1.0,3.0,4.0,2.0,1.0,5.0,2.0,12495.0,11435.0,241.0,9906.0,9743.0,235.0,2589.0,1692.0,6.0,6.0,7.0,3.0,1.0,6.0,4.0
25635,LOLTMNT01_349329,complete,FST,2026,NaN,0,2026-03-16 18:15:35,2,16.05,4,Blue,bot,Hans Sama,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Ashe,Orianna,Ryze,Nocturne,Renekton,Trundle,NaN,NaN,NaN,NaN,NaN,2004,1,7,2,10,21,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6287,1.1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,29713,889.6108,0.268369,565.7485,382.8144,7946.0,14,0.4192,20,0.5988,7.0,72,2.1557,18359,13995,419.0120,0.313850,15775.0,NaN,NaN,364.0,333.0,31,NaN,NaN,10.8982,4034.0,3531.0,88.0,3261.0,3164.0,75.0,773.0,367.0,13.0,2.0,1.0,0.0,0.0,2.0,1.0,7413.0,6333.0,144.0,4759.0,5159.0,117.0,2654.0,1174.0,27.0,5.0,2.0,0.0,0.0,2.0,3.0,9962.0,8815.0,205.0,8041.0,8182.0,178.0,1921.0,633.0,27.0,5.0,3.0,1.0,1.0,5.0,3.0,12609.0,11895.0,267.0,10882.0,11109.0,236.0,1727.0,786.0,31.0,5.0,5.0,2.0,2.0,8.0,3.0

In [243]:
df['result'].unique()

array([0, 1])

In [244]:
df.isnull().sum().sort_values(ascending=False).head(20)

monsterkillsenemyjungle    110244
monsterkillsownjungle      110244
opp_atakhans                94778
firstbaron                  92112
pick5                       92088
pick2                       92088
pick1                       92088
pick3                       92088
pick4                       92088
firstherald                 91986
firstdragon                 91980
firstmidtower               91980
firsttower                  91978
opp_elders                  91970
hextechs                    91970
clouds                      91970
oceans                      91970
opp_elementaldrakes         91970
mountains                   91970
infernals                   91970
dtype: int64

In [245]:
df.columns.tolist()

['gameid',
 'datacompleteness',
 'league',
 'year',
 'split',
 'playoffs',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [246]:
fst_df

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25560,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0.0,28,0.9444,10807,6902,232.7825,0.196186,9150.0,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25561,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11.0,55,1.8550,12060,8155,275.0422,0.231800,11925.0,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25562,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3.0,22,0.7420,10726,6821,230.0506,0.193883,10500.0,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25563,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4.0,38,1.2816,13565,9660,325.8010,0.274577,14010.0,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25564,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11.0,127,4.2833,7548,3643,122.8668,0.103554,7675.0,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26491,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,8,Red,mid,Caps,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Viktor,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,3,1,7,12,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21737,817.6928,0.370717,466.1944,503.7743,4885.0,10,0.3762,8,0.3009,4.0,34,1.2790,9911,6382,240.0752,0.207640,8950.0,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8025,3663.0,5182.0,88.0,3998.0,4788.0,88.0,-335.0,394.0,0.0,0.0,3.0,1.0,2.0,0.0,1.0,5931.0,8528.0,136.0,5265.0,6822.0,123.0,666.0,1706.0,13.0,2.0,6.0,1.0,2.0,0.0,3.0,7919.0,11264.0,194.0,7403.0,10065.0,181.0,516.0,1199.0,13.0,2.0,6.0,1.0,2.0,2.0,3.0,9607.0,13354.0,230.0,8976.0,14082.0,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26492,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3.0,40,1.5047,12236,8707,327.5361,0.283289,11925.0,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26493,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,10,Red,sup,Labrov,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Rakan,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,0,2,9,12,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4537,170.6708,0.077377,507.0470,463.9749,0.0,47,1.7680,12,0.4514,11.0,105,3.9498,6496,2967,111.6113,0.096525,5920.0,NaN,NaN,24.0,24.0,0,NaN,NaN,0.9028,2504.0,1757.0,9.0,2550.0,2304.0,9.0,-46.0,-547.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0,3829.0,3936.0,15.0,3732.0,3230.0,19.0,97.0,706.0,-4.0,0.0,7.0,0.0,0.0,1.0,2.0,4971.0,4573.0,21.0,4980.0,4639.0,21.0,-9.0,-66.0,0.0,0.0,7.0,1.0,0.0,3.0,2.0,6161.0,6314.0,24.0,6268.0,7303.0,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26494,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,100,Blue,team,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Rumble,Maokai,Akali,Vi,Xayah,Alistar,Camille,Cassiopeia,1595,1,8,12,19,8,12,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3009,0.7524,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,7.0,1.0,1.0,1.0,25.0,12.0,1.0,0.0,57024,2145.1034,NaN,3055.0345,2666.2947,32895.0,102,3.8370,36,1.3542,28.0,254,9.5549,51682,34035,1280.3135,NaN,45223.0,-0.025218,-0.18,NaN,813.0,185,NaN,NaN,37.5423,17356.0,20681.0,372.0,17656.0,19713.0,330.0,-300.0,968.0,42.0,2.0,2.0,4.0,4.0,9.0,2.0,25357.0,31403.0,558.0,28580.0,34561.0,520.0,-3223.0,-3158.0,38.0,2.0,2.0,10.0,10.0,20.0,2.0,36649.0,45707.0,786.0,37537.0,46378.0,745.0,-888.0,-671.0,41.0,4.0,7.0,10.0,10.0,20.0,4.0,46187.0,62098.0,979.0,46122.0,57751.0,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26495,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26.0,252,9.4796,48381,30734,1156.1379,NaN,46378.0,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [247]:
df.sample(10)

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
84981,LOLTMNT01_438421,complete,NACL,2026,Summer,0,2026-08-06 00:48:04,2,16.15,10,Red,sup,Breezy,Cupid Esports,oe:team:d522e8753c50018adbb82305997c211,0.0,Nautilus,Ziggs,Jayce,Vi,Caitlyn,Sivir,NaN,NaN,NaN,NaN,NaN,2271,0,1,8,0,4,20,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.1057,0.6341,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,3569,94.2933,0.045245,580.6077,1078.8639,91.0,72,1.9022,15,0.3963,28.0,155,4.0951,8625,3717,98.2034,0.093955,8160.0,NaN,NaN,40.0,40.0,0,NaN,NaN,1.0568,2584.0,2349.0,20.0,2713.0,2459.0,9.0,-129.0,-110.0,11.0,1.0,0.0,1.0,1.0,2.0,0.0,3719.0,3342.0,30.0,4004.0,3533.0,14.0,-285.0,-191.0,16.0,1.0,0.0,2.0,1.0,4.0,0.0,4810.0,4089.0,31.0,5476.0,4599.0,21.0,-666.0,-510.0,10.0,1.0,0.0,3.0,2.0,4.0,0.0,5794.0,5724.0,33.0,6609.0,6850.0,25.0,-815.0,-1126.0,8.0,1.0,0.0,4.0,2.0,6.0,0.0
57309,LOLTMNT02_403982,complete,EWC,2026,NaN,0,2026-05-19 10:03:44,1,16.10,10,Red,sup,Lehends,Nongshim RedForce,oe:team:5cd2cd09ec94296f605dd13a2924d6c,1.0,Nautilus,Varus,Ashe,Jarvan IV,Vi,Pantheon,NaN,NaN,NaN,NaN,NaN,2867,0,0,10,13,27,35,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5651,1.2975,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9622,201.3673,0.042641,965.0645,1715.5145,184.0,88,1.8416,20,0.4186,15.0,187,3.9135,11672,5548,116.1074,0.079636,10970.0,NaN,NaN,43.0,43.0,0,NaN,NaN,0.8999,2392.0,2549.0,16.0,2302.0,2083.0,11.0,90.0,466.0,5.0,0.0,0.0,1.0,0.0,0.0,0.0,3681.0,3685.0,24.0,3317.0,2796.0,14.0,364.0,889.0,10.0,0.0,2.0,1.0,0.0,0.0,0.0,4880.0,5259.0,30.0,4856.0,5610.0,18.0,24.0,-351.0,12.0,0.0,3.0,2.0,0.0,6.0,0.0,5831.0,6240.0,32.0,6138.0,7238.0,23.0,-307.0,-998.0,9.0,0.0,3.0,4.0,0.0,10.0,0.0
102839,LOLTMNT02_463244,complete,LCKC,2026,Rounds 3-4,1,2026-09-10 10:47:39,4,16.16,200,Red,team,NaN,Dplus Kia Challengers,oe:team:64f78960f955a6b659025e38b4f0a18,0.0,NaN,Cassiopeia,Vi,Jayce,Alistar,Nautilus,Viktor,Ambessa,Skarner,Sivir,Yuumi,1510,0,5,14,6,5,14,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.1987,0.7550,0.0,1.0,3.0,1.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,9.0,0.0,0.0,5.0,37.0,0.0,1.0,65718,2611.3113,NaN,2857.3907,2813.2053,586.0,78,3.0993,38,1.5099,39.0,195,7.7483,43971,27191,1080.4371,NaN,43420.0,-0.086023,-2.40,NaN,780.0,134,NaN,NaN,36.3179,16025.0,19511.0,344.0,16733.0,20629.0,391.0,-708.0,-1118.0,-47.0,1.0,1.0,1.0,1.0,0.0,1.0,24518.0,30402.0,540.0,28294.0,32865.0,591.0,-3776.0,-2463.0,-51.0,1.0,1.0,4.0,4.0,3.0,1.0,34728.0,43757.0,745.0,39810.0,46499.0,808.0,-5082.0,-2742.0,-63.0,4.0,5.0,8.0,8.0,17.0,4.0,43859.0,56270.0,914.0,54396.0,65011.0,995.0,-10537.0,-8741.0,-81.0,5.0,6.0,14.0,14.0,33.0,5.0
80923,LOLTMNT02_444235,complete,LCP,2026,Split 3,0,2026-07-30 11:15:35,3,16.14,8,Red,mid,Fisher,DetonatioN FocusMe,oe:team:e435aa3ecb82a89e60544f5f5857a81,1.0,Akali,Ezreal,Olaf,Lee Sin,Galio,LeBlanc,NaN,NaN,NaN,NaN,NaN,1843,1,4,1,5,18,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5860,0.9116,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,20200,657.6234,0.236570,607.9436,439.6636,7085.0,12,0.3907,3,0.0977,9.0,32,1.0418,12521,8486,276.2670,0.197652,12325.0,NaN,NaN,287.0,287.0,0,NaN,NaN,9.3435,3677.0,4508.0,89.0,3924.0,4743.0,93.0,-247.0,-235.0,-4.0,1.0,0.0,0.0,0.0,2.0,1.0,5252.0,6820.0,138.0,6011.0,7557.0,156.0,-759.0,-737.0,-18.0,1.0,0.0,0.0,0.0,2.0,1.0,7270.0,10074.0,200.0,7935.0,9762.0,205.0,-665.0,312.0,-5.0,1.0,2.0,0.0,0.0,2.0,1.0,9302.0,12743.0,255.0,10160.0,13228.0,244.0,-858.0,-485.0,11.0,1.0,2.0,0.0,1.0,2.0,1.0
29958,LOLTMNT02_376179,complete,LCKC,2026,Rounds 1-2,0,2026-04-03 06:01:19,2,16.06,7,Red,jng,Sharvel,Dplus Kia Challengers,oe:team:64f78960f955a6b659025e38b4f0a18,1.0,Camille,Ambessa,Jarvan IV,Rumble,Nautilus,Anivia,NaN,NaN,NaN,NaN,NaN,1756,1,2,2,19,26,5,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.8884,1.0592,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12165,415.6606,0.140720,937.6196,883.6333,13228.0,10,0.3417,11,0.3759,9.0,54,1.8451,12830,8972,306.5604,0.195605,11858.0,NaN,NaN,220.0,14.0,206,NaN,NaN,7.5171,3689.0,3837.0,72.0,3950.0,4471.0,87.0,-261.0,-634.0,-15.0,0.0,2.0,0.0,1.0,0.0,0.0,5506.0,6640.0,112.0,5651.0,6699.0,126.0,-145.0,-59.0,-14.0,1.0,2.0,0.0,1.0,1.0,0.0,7564.0,9545.0,143.0,7005.0,8310.0,152.0,559.0,1235.0,-9.0,2.0,7.0,1.0,1.0,2.0,1.0,10437.0,13626.0,181.0,8421.0,10108.0,171.0,2016.0,3518.0,10.0,2.0,12.0,2.0,1.0,4.0,3.0
38158,LOLTMNT01_366999,complete,AL,2026,Spring,0,2026-04-17 18:00:53,1,16.07,100,Blue,team,NaN,BAAM Esports,oe:team:b1a205489742f1e0600c6489b5d15a8,1.0,NaN,Rengar,Qiyana,Naafiri,Zaahen,Garen,Yunara,Nocturne,Lulu,Gnar,Galio,1870,1,20,20,39,20,20,2.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.6417,1.2834,1.0,3.0,2.0,3.0,2.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,8.0,5.0,1.0,0.0,34.0,30.0,1.0,0.0,115977,3721.1872,NaN,4143.0802,4290.8984,41766.0,95,3.0481,42,1.3476,19.0,254,8.1497,65488,45036,1445.0053,NaN,59673.0,-0.033693,-0.14,NaN,869.0,203,NaN,NaN,34.3957,16645.0,21128.0,363.0,17367.0,21710.0,382.0,-722.0,-582.0,-19.0,2.0,4.0,3.0,3.0,0.0,2.0,27915.0,34645.0,557.0,26907.0,33876.0,588.0,1008.0,769.0,-31.0,6.0,11.0,4.0,4.0,0.0,6.0,39235.0,48231.0,745.0,37949.0,47893.0,783.0,1286.0,338.0,-38.0,10.0,17.0,7.0,7.0,3.0,10.0,47142.0,58714.0,921.0,49666.0,63287.0,979.0,-2524.0,-4573.0,-58.0,10.0,17.0,10.0,10.0,10.0,10.0
34757,LOLTMNT01_364042,complete,LJL,2026,NaN,0,2026-04-12 06:08:33,1,16.07,6,Red,top,Looter,Bamboo Juice,oe:team:a0360aac17e130e37f2d351cd95db75,0.0,Cassiopeia,Pantheon,Karma,Sion,K'Sante,Orianna,NaN,NaN,NaN,NaN,NaN,1584,0,2,4,0,10,27,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.3788,1.4015,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7502,284.1667,0.129869,878.0303,451.3636,3921.0,10,0.3788,1,0.0379,2.0,26,0.9848,9141,5634,213.4091,0.170418,8500.0,NaN,NaN,215.0,215.0,0,NaN,NaN,8.1439,3516.0,5021.0,81.0,3103.0,5123.0,74.0,413.0,-102.0,7.0,1.0,0.0,0.0,0.0,1.0,1.0,4877.0,7847.0,121.0,5175.0,8597.0,109.0,-298.0,-750.0,12.0,1.0,0.0,1.0,1.0,4.0,1.0,6991.0,11829.0,187.0,6875.0,12022.0,154.0,116.0,-193.0,33.0,1.0,0.0,1.0,1.0,5.0,1.0,8527.0,15409.0,214.0,8367.0,15365.0,180.0,160.0,44.0,34.0,1.0,0.0,3.0,1.0,7.0,1.0
84102,LOLTMNT01_437091,complete,LJL,2026,Summer,1,2026-08-05 08:16:25,1,16.15,7,Red,jng,Ellim,FENNEL,oe:team:d418f5db39c1766ac692224837b3c24,0.0,Jayce,Pyke,Camille,Nautilus,Kai'Sa,Yunara,NaN,NaN,NaN,NaN,NaN,1869,1,6,2,10,19,9,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6100,0.8989,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,29967,962.0225,0.336326,817.3997,478.2665,4193.0,5,0.1605,13,0.4173,4.0,44,1.4125,16384,12296,394.7352,0.257515,15750.0,NaN,NaN,280.0,21.0,259,NaN,NaN,8.9888,3772.0,4338.0,84.0,3479.0,3948.0,76.0,293.0,390.0,8.0,0.0,2.0,1.0,0.0,1.0,1.0,6782.0,7227.0,128.0,4925.0,5988.0,108.0,1857.0,1239.0,20.0,3.0,4.0,1.0,0.0,1.0,4.0,9025.0,9949.0,171.0,7330.0,9375.0,153.0,1695.0,574.0,18.0,3.0,4.0,1.0,0.0,3.0,4.0,11840.0,13378.0,221.0,9385.0,11617.0,188.0,2455.0,1761.0,33.0,4.0,4.0,1.0,1.0,3.0,4.0
106951,LOLTMNT04_191104,complete,LEC,2026,Summer,1,2026-09-19 16:20:50,2,16.17,8,Red,mid,kyeahoo,Karmine Corp,oe:team:f3aa9bbd924ce3af42ac53f8326bc7c,1.0,Ryze,Nocturne,Akali,Pantheon,Orianna,Yone,NaN,NaN,NaN,NaN,NaN,1856,0,1,3,4,7,20,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.2263,0.8728,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,14931,482.6832,0.212073,698.4698,559.8491,5209.0,12,0.3879,9,0.2909,8.0,46,1.4871,11582,7520,243.1034,0.202931,10850.0,NaN,NaN,267.0,259.0,8,NaN,NaN,8.6315,3776.0,5038.0,104.0,3212.0,4600.0,86.0,564.0,438.0,18.0,0.0,1.0,0.0,0.0,0.0,0.0,5340.0,7477.0,150.0,4875.0,7187.0,135.0,465.0,290.0,15.0,0.0,1.0,0.0,0.0,0.0,0.0,7735.0,10871.0,220.0,6256.0,9937.0,173.0,1479.0,934.0,47.0,0.0,2.0,0.0,0.0,2.0,0.0,9196.0,13020.0,253.0,7801.0,14256.0,215.0,1395.0,-1236.0,38.0,0.0,3.0,1.0,0.0,5.0,0.0
65665,13290-13290_game_3,complete,LPL,2026,Split 2,1,2026-06-03 11:02:45,3,16.10,2,Blue,jng,Xun,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,Wukong,Nocturne,Varus,Naafiri,Nautilus,Zeri,NaN,NaN,NaN,NaN,NaN,2197,1,3,0,8,17,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4643,0.7647,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16698,456.0218,0.170995,926.9276,873.3728,5512.0,12,0.3277,14,0.3823,9.0,67,1.8298,16005,11248,307.1825,0.214420,14822.0,NaN,NaN,312.0,32.0,280,NaN,NaN,8.5207,3587.0,3862.0,72.0,3850.0,4004.0,73.0,-263.0,-142.0,-1.0,1.0,0.0,0.0,1.0,2.0,0.0,5788.0,6138.0,99.0,6008.0,7104.0,126.0,-220.0,-966.0,-27.0,2.0,1.0,0.0,2.0,2.0,0.0,8114.0,9535.0,146.0,7697.0,9767.0,169.0,417.0,-232.0,-23.0,2.0,2.0,0.0,2.0,2.0,0.0,9838.0,12141.0,187.0,9347.0,11918.0,208.0,491.0,223.0,-21.0,2.0,2.0,0.0,2.0,2.0,0.0

In [248]:
fst_df = df[df['league'] == 'FST']

In [249]:
fst_df

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25560,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,1,Blue,top,Clear,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Ambessa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,6,2,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16935,571.1636,0.254984,776.7960,1048.8027,4060.0,12,0.4047,2,0.0675,0.0,28,0.9444,10807,6902,232.7825,0.196186,9150.0,NaN,NaN,225.0,221.0,4,NaN,NaN,7.5885,3202.0,4670.0,74.0,3823.0,4876.0,74.0,-621.0,-206.0,0.0,0.0,1.0,2.0,2.0,0.0,1.0,4694.0,7738.0,117.0,6085.0,8603.0,131.0,-1391.0,-865.0,-14.0,0.0,1.0,3.0,2.0,1.0,1.0,6593.0,10747.0,156.0,9617.0,12067.0,187.0,-3024.0,-1320.0,-31.0,1.0,1.0,4.0,4.0,1.0,1.0,8206.0,13352.0,195.0,12385.0,16714.0,245.0,-4179.0,-3362.0,-50.0,1.0,1.0,5.0,6.0,2.0,1.0
25561,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,2,Blue,jng,Raptor,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Vi,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,4,6,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10688,360.4722,0.160925,938.2462,894.7723,0.0,12,0.4047,12,0.4047,11.0,55,1.8550,12060,8155,275.0422,0.231800,11925.0,NaN,NaN,192.0,24.0,168,NaN,NaN,6.4755,4676.0,4420.0,75.0,3790.0,3658.0,68.0,886.0,762.0,7.0,3.0,0.0,1.0,1.0,3.0,1.0,6447.0,6891.0,118.0,5915.0,6170.0,106.0,532.0,721.0,12.0,3.0,1.0,3.0,2.0,5.0,1.0,8220.0,9040.0,154.0,8164.0,9287.0,145.0,56.0,-247.0,9.0,3.0,2.0,4.0,2.0,11.0,1.0,9527.0,10342.0,173.0,10974.0,13279.0,189.0,-1447.0,-2937.0,-16.0,3.0,2.0,6.0,4.0,15.0,1.0
25562,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,3,Blue,mid,VicLa,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Taliyah,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,1,5,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17117,577.3019,0.257724,475.9528,191.3322,1313.0,12,0.4047,6,0.2024,3.0,22,0.7420,10726,6821,230.0506,0.193883,10500.0,NaN,NaN,267.0,263.0,4,NaN,NaN,9.0051,3459.0,4353.0,79.0,4345.0,4548.0,82.0,-886.0,-195.0,-3.0,0.0,2.0,2.0,3.0,2.0,1.0,5416.0,7181.0,134.0,6232.0,7530.0,136.0,-816.0,-349.0,-2.0,1.0,2.0,2.0,3.0,4.0,1.0,7260.0,9716.0,184.0,8643.0,10420.0,189.0,-1383.0,-704.0,-5.0,1.0,4.0,3.0,4.0,9.0,2.0,9163.0,12550.0,236.0,10604.0,14703.0,235.0,-1441.0,-2153.0,1.0,1.0,4.0,4.0,4.0,10.0,2.0
25563,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,4,Blue,bot,Diable,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Kai'Sa,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,2,4,3,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,11931,402.3946,0.179640,566.7116,331.5683,38.0,13,0.4384,10,0.3373,4.0,38,1.2816,13565,9660,325.8010,0.274577,14010.0,NaN,NaN,316.0,309.0,7,NaN,NaN,10.6577,3901.0,4021.0,98.0,3588.0,3939.0,97.0,313.0,82.0,1.0,1.0,0.0,0.0,0.0,1.0,0.0,6361.0,6670.0,155.0,5991.0,7002.0,161.0,370.0,-332.0,-6.0,1.0,0.0,0.0,0.0,1.0,0.0,9379.0,9470.0,216.0,9729.0,9937.0,217.0,-350.0,-467.0,-1.0,2.0,1.0,1.0,3.0,3.0,0.0,11676.0,12064.0,282.0,12576.0,13044.0,257.0,-900.0,-980.0,25.0,2.0,1.0,2.0,5.0,4.0,0.0
25564,LOLTMNT01_349243,complete,FST,2026,NaN,0,2026-03-16 13:10:29,1,16.05,5,Blue,sup,Kellin,BNK FEARX,oe:team:5c2e7e9ea8dfcba0150d9a5619baecf,0.0,Neeko,Orianna,Poppy,Xin Zhao,Bard,Renekton,NaN,NaN,NaN,NaN,NaN,1779,0,0,8,6,9,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3035,1.2816,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9745,328.6678,0.146727,695.9528,218.0776,0.0,66,2.2260,16,0.5396,11.0,127,4.2833,7548,3643,122.8668,0.103554,7675.0,NaN,NaN,29.0,29.0,0,NaN,NaN,0.9781,2489.0,2564.0,10.0,2716.0,2872.0,13.0,-227.0,-308.0,-3.0,0.0,2.0,2.0,1.0,2.0,1.0,3768.0,3066.0,16.0,4522.0,3740.0,14.0,-754.0,-674.0,2.0,0.0,3.0,2.0,3.0,3.0,2.0,5128.0,4683.0,21.0,6027.0,5081.0,17.0,-899.0,-398.0,4.0,0.0,5.0,4.0,3.0,9.0,3.0,6380.0,5515.0,28.0,7582.0,7485.0,18.0,-1202.0,-1970.0,10.0,0.0,5.0,5.0,3.0,14.0,3.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26491,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,8,Red,mid,Caps,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Viktor,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,3,1,7,12,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21737,817.6928,0.370717,466.1944,503.7743,4885.0,10,0.3762,8,0.3009,4.0,34,1.2790,9911,6382,240.0752,0.207640,8950.0,NaN,NaN,234.0,234.0,0,NaN,NaN,8.8025,3663.0,5182.0,88.0,3998.0,4788.0,88.0,-335.0,394.0,0.0,0.0,3.0,1.0,2.0,0.0,1.0,5931.0,8528.0,136.0,5265.0,6822.0,123.0,666.0,1706.0,13.0,2.0,6.0,1.0,2.0,0.0,3.0,7919.0,11264.0,194.0,7403.0,10065.0,181.0,516.0,1199.0,13.0,2.0,6.0,1.0,2.0,2.0,3.0,9607.0,13354.0,230.0,8976.0,14082.0,217.0,631.0,-728.0,13.0,3.0,7.0,1.0,2.0,2.0,3.0
26492,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,9,Red,bot,Hans Sama,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Kai'Sa,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,4,1,3,12,8,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12287,462.2069,0.209551,526.5705,280.1755,1063.0,9,0.3386,12,0.4514,3.0,40,1.5047,12236,8707,327.5361,0.283289,11925.0,NaN,NaN,271.0,271.0,0,NaN,NaN,10.1944,3881.0,3932.0,85.0,3627.0,4370.0,101.0,254.0,-438.0,-16.0,2.0,0.0,0.0,0.0,0.0,0.0,7077.0,6350.0,136.0,6247.0,7207.0,166.0,830.0,-857.0,-30.0,4.0,1.0,0.0,0.0,0.0,0.0,9569.0,9533.0,208.0,8836.0,10567.0,240.0,733.0,-1034.0,-32.0,4.0,1.0,0.0,0.0,0.0,0.0,11645.0,11590.0,265.0,11067.0,13644.0,303.0,578.0,-2054.0,-38.0,4.0,3.0,0.0,0.0,0.0,0.0
26493,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,10,Red,sup,Labrov,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,Rakan,Ambessa,Caitlyn,Neeko,Ahri,Syndra,NaN,NaN,NaN,NaN,NaN,1595,0,0,2,9,12,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4514,0.7524,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4537,170.6708,0.077377,507.0470,463.9749,0.0,47,1.7680,12,0.4514,11.0,105,3.9498,6496,2967,111.6113,0.096525,5920.0,NaN,NaN,24.0,24.0,0,NaN,NaN,0.9028,2504.0,1757.0,9.0,2550.0,2304.0,9.0,-46.0,-547.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0,3829.0,3936.0,15.0,3732.0,3230.0,19.0,97.0,706.0,-4.0,0.0,7.0,0.0,0.0,1.0,2.0,4971.0,4573.0,21.0,4980.0,4639.0,21.0,-9.0,-66.0,0.0,0.0,7.0,1.0,0.0,3.0,2.0,6161.0,6314.0,24.0,6268.0,7303.0,23.0,-107.0,-989.0,1.0,0.0,9.0,1.0,0.0,3.0,3.0
26494,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,100,Blue,team,NaN,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,0.0,NaN,Orianna,Ryze,Rumble,Maokai,Akali,Vi,Xayah,Alistar,Camille,Cassiopeia,1595,1,8,12,19,8,12,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3009,0.7524,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,7.0,1.0,1.0,1.0,25.0,12.0,1.0,0.0,57024,2145.1034,NaN,3055.0345,2666.2947,32895.0,102,3.8370,36,1.3542,28.0,254,9.5549,51682,34035,1280.3135,NaN,45223.0,-0.025218,-0.18,NaN,813.0,185,NaN,NaN,37.5423,17356.0,20681.0,372.0,17656.0,19713.0,330.0,-300.0,968.0,42.0,2.0,2.0,4.0,4.0,9.0,2.0,25357.0,31403.0,558.0,28580.0,34561.0,520.0,-3223.0,-3158.0,38.0,2.0,2.0,10.0,10.0,20.0,2.0,36649.0,45707.0,786.0,37537.0,46378.0,745.0,-888.0,-671.0,41.0,4.0,7.0,10.0,10.0,20.0,4.0,46187.0,62098.0,979.0,46122.0,57751.0,924.0,65.0,4347.0,55.0,4.0,7.0,12.0,12.0,26.0,4.0
26495,LOLTMNT01_352610,complete,FST,2026,NaN,0,2026-03-22 16:04:39,4,16.05,200,Red,team,NaN,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,1.0,NaN,Ambessa,Caitlyn,Neeko,Ahri,Syndra,K'Sante,Rakan,Kai'Sa,Viktor,Wukong,1595,0,12,8,26,12,8,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4514,0.7524,0.0,3.0,1.0,3.0,1.0,1.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,7.0,0.0,0.0,12.0,25.0,0.0,1.0,58635,2205.7053,NaN,2865.5172,2750.8966,10587.0,83,3.1223,40,1.5047,26.0,252,9.4796,48381,30734,1156.1379,NaN,46378.0,0.025218,0.18,NaN,782.0,172,NaN,NaN,35.8871,17656.0,19713.0,330.0,17356.0,20681.0,372.0,300.0,-968.0,-42.0,4.0,9.0,2.0,2.0,2.0,4.0,28580.0,34561.0,520.0,25357.0,31403.0,558.0,3223.0,3158.0,-38.0,10.0,20.0,2.0,2.0,2.0,10.0,37537.0,46378.0,745.0,36649.0,45707.0,786.0,888.0,671.0,-41.0,10.0,20.0,4.0,4.0,7.0,10.0,46122.0,57751.0,924.0,46187.0,62098.0,979.0,-65.0,-4347.0,-55.0,12.0,26.0,4.0,4.0,7.0,12.0

In [250]:
df['playoffs'].unique()

array([0, 1])

In [251]:
df['playoffs'].value_counts()

playoffs
0    86388
1    23964
Name: count, dtype: int64

In [252]:
df.sample(15)

,gameid,datacompleteness,league,year,split,playoffs,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
89337,LOLTMNT04_181926,complete,EBL,2026,Summer,0,2026-08-13 17:00:27,2,16.15,10,Red,sup,Candy,Lupus Esports,oe:team:1b4462a50541e063fc148be4082fd0b,0.0,Rell,Caitlyn,Tristana,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1912,1,1,1,13,16,9,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5021,0.7845,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4896,153.6402,0.051226,416.4226,490.1987,153.0,55,1.7259,15,0.4707,22.0,125,3.9226,8298,4122,129.3515,0.089707,7305.0,NaN,NaN,33.0,33.0,0,NaN,NaN,1.0356,2263.0,2563.0,14.0,2243.0,2457.0,16.0,20.0,106.0,-2.0,0.0,1.0,0.0,0.0,0.0,1.0,3308.0,3422.0,19.0,3376.0,3343.0,21.0,-68.0,79.0,-2.0,0.0,1.0,0.0,0.0,1.0,1.0,4590.0,4351.0,28.0,4322.0,4002.0,25.0,268.0,349.0,3.0,0.0,2.0,0.0,0.0,1.0,1.0,5655.0,5559.0,32.0,5406.0,5502.0,32.0,249.0,57.0,0.0,0.0,3.0,0.0,0.0,1.0,1.0
74658,LOLTMNT01_427240,complete,EWC,2026,NaN,1,2026-07-16 11:07:53,1,16.13,7,Red,jng,HamBak,Sentinels,oe:team:f90422f1cbcb24bc2a855202582ec29,0.0,Naafiri,Jayce,Vi,Nocturne,Poppy,Wukong,NaN,NaN,NaN,NaN,NaN,1926,0,3,7,5,10,25,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.3115,1.0903,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,11276,351.2773,0.164883,841.5888,459.4393,1938.0,8,0.2492,11,0.3427,7.0,52,1.6199,11614,7409,230.8100,0.205321,11250.0,NaN,NaN,215.0,33.0,182,NaN,NaN,6.6978,3937.0,4085.0,76.0,4604.0,4351.0,82.0,-667.0,-266.0,-6.0,1.0,1.0,1.0,2.0,0.0,1.0,5948.0,5910.0,107.0,7718.0,7099.0,115.0,-1770.0,-1189.0,-8.0,2.0,4.0,3.0,6.0,0.0,2.0,8088.0,9023.0,154.0,10597.0,10212.0,167.0,-2509.0,-1189.0,-13.0,2.0,5.0,3.0,6.0,1.0,2.0,10011.0,11078.0,183.0,15474.0,14760.0,215.0,-5463.0,-3682.0,-32.0,3.0,5.0,5.0,12.0,1.0,2.0
74330,LOLTMNT01_425900,complete,EWC,2026,NaN,1,2026-07-15 13:04:22,1,16.13,3,Blue,mid,HongQ,JD Gaming,oe:team:b42d0f31f2727621b963042276817c4,1.0,Orianna,Ezreal,Akali,Lee Sin,Olaf,Viktor,NaN,NaN,NaN,NaN,NaN,1853,1,8,1,7,23,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7447,0.9714,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,23690,767.0804,0.255036,403.3891,374.6033,4863.0,26,0.8419,11,0.3562,15.0,67,2.1695,15705,11649,377.1937,0.225362,14850.0,NaN,NaN,331.0,327.0,4,NaN,NaN,10.7178,3814.0,4952.0,99.0,3787.0,5335.0,98.0,27.0,-383.0,1.0,1.0,0.0,1.0,1.0,0.0,0.0,5748.0,7348.0,149.0,5834.0,7899.0,148.0,-86.0,-551.0,1.0,2.0,0.0,1.0,1.0,0.0,1.0,8056.0,10817.0,199.0,7293.0,10573.0,194.0,763.0,244.0,5.0,3.0,1.0,1.0,1.0,0.0,3.0,11199.0,14321.0,254.0,9801.0,13423.0,254.0,1398.0,898.0,0.0,4.0,3.0,1.0,1.0,0.0,4.0
35163,LOLTMNT04_155549,complete,NL,2026,NaN,0,2026-04-12 12:22:34,1,16.07,4,Blue,bot,Looki,Karmine Corp Blue Stars,oe:team:343268a42863e8fc2767e02e4042de8,1.0,Ashe,Karma,Aurora,Ambessa,Mel,Ahri,NaN,NaN,NaN,NaN,NaN,1887,1,4,1,15,27,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8585,1.2719,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,24096,766.1685,0.233321,479.1415,324.3561,5550.0,10,0.3180,10,0.3180,2.0,39,1.2401,16180,12055,383.3068,0.268373,13150.0,NaN,NaN,317.0,305.0,12,NaN,NaN,10.0795,3776.0,3849.0,88.0,3336.0,3501.0,85.0,440.0,348.0,3.0,1.0,1.0,0.0,0.0,0.0,1.0,6308.0,6074.0,139.0,6014.0,5494.0,139.0,294.0,580.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,8684.0,9158.0,206.0,8203.0,8261.0,200.0,481.0,897.0,6.0,2.0,1.0,0.0,0.0,0.0,1.0,11126.0,11252.0,245.0,11433.0,10345.0,243.0,-307.0,907.0,2.0,3.0,4.0,1.0,2.0,1.0,2.0
26538,LOLTMNT05_181176,complete,EM,2026,Winter,0,2026-03-23 17:19:33,2,16.06,7,Red,jng,Daglas,Team Heretics Academy,oe:team:2dfc66b98002c5afad2a98dbf86e350,0.0,Xin Zhao,Orianna,Jarvan IV,Vi,K'Sante,Ornn,NaN,NaN,NaN,NaN,NaN,2306,0,4,3,2,8,14,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.2082,0.5724,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15614,406.2619,0.161637,1233.8248,943.2177,0.0,12,0.3122,10,0.2602,11.0,61,1.5872,14872,9892,257.3807,0.221159,14775.0,NaN,NaN,304.0,39.0,265,NaN,NaN,7.9098,3990.0,4616.0,87.0,3406.0,3778.0,72.0,584.0,838.0,15.0,1.0,0.0,0.0,0.0,1.0,0.0,6343.0,7541.0,128.0,5286.0,6195.0,105.0,1057.0,1346.0,23.0,3.0,1.0,1.0,1.0,2.0,2.0,8232.0,10143.0,158.0,7833.0,8943.0,145.0,399.0,1200.0,13.0,4.0,1.0,2.0,3.0,2.0,2.0,10236.0,13399.0,206.0,9308.0,11021.0,174.0,928.0,2378.0,32.0,4.0,1.0,2.0,3.0,2.0,2.0
5287,LOLTMNT01_326059,complete,LCS,2026,Lock-In,0,2026-01-25 22:12:03,2,16.02,8,Red,mid,Zinie,Shopify Rebellion,oe:team:b360f1d729b0a8e0f29a5243c4200fa,0.0,Ryze,Ambessa,Rumble,Jayce,Vi,Pantheon,NaN,NaN,NaN,NaN,NaN,2337,0,2,5,2,9,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2311,0.7959,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20810,534.2747,0.199547,764.9294,792.2978,10427.0,25,0.6418,10,0.2567,13.0,60,1.5404,14734,9691,248.8062,0.209826,14325.0,NaN,NaN,338.0,317.0,21,NaN,NaN,8.6778,3609.0,5002.0,93.0,3834.0,5485.0,102.0,-225.0,-483.0,-9.0,1.0,0.0,0.0,1.0,1.0,0.0,5185.0,7310.0,141.0,6365.0,8291.0,160.0,-1180.0,-981.0,-19.0,1.0,0.0,1.0,2.0,2.0,0.0,6787.0,9174.0,175.0,8597.0,10326.0,192.0,-1810.0,-1152.0,-17.0,1.0,0.0,3.0,3.0,4.0,0.0,8774.0,13693.0,235.0,9852.0,12071.0,223.0,-1078.0,1622.0,12.0,1.0,0.0,3.0,3.0,4.0,0.0
42490,LOLTMNT04_158087,complete,AL,2026,Spring,0,2026-04-24 16:00:57,1,16.07,100,Blue,team,NaN,One More Esports,oe:team:ca663b1c89065ae6491db8e9cd5c305,1.0,NaN,Rumble,LeBlanc,Ambessa,Vi,Aatrox,Karma,Caitlyn,Aurora,Xin Zhao,Ornn,1479,0,9,23,14,9,23,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.3651,1.2982,1.0,2.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,1.0,10.0,0.0,0.0,8.0,40.0,0.0,1.0,65783,2668.6815,NaN,4185.5172,2775.5781,10248.0,66,2.6775,20,0.8114,16.0,178,7.2211,41996,25532,1035.7809,NaN,40610.0,-0.210639,-1.84,NaN,657.0,157,NaN,NaN,33.0223,17655.0,21107.0,349.0,17952.0,20994.0,373.0,-297.0,113.0,-24.0,4.0,4.0,3.0,3.0,5.0,4.0,26061.0,33242.0,535.0,29232.0,34787.0,599.0,-3171.0,-1545.0,-64.0,5.0,4.0,6.0,6.0,9.0,5.0,35204.0,45971.0,718.0,40041.0,48218.0,819.0,-4837.0,-2247.0,-101.0,7.0,7.0,8.0,8.0,14.0,7.0,41996.0,54157.0,814.0,59603.0,69163.0,964.0,-17607.0,-15006.0,-150.0,9.0,14.0,23.0,23.0,55.0,9.0
58569,LOLTMNT02_406958,complete,LCK,2026,Rounds 1-2,0,2026-05-21 08:06:57,1,16.10,10,Red,sup,Bluffing,Hanwha Life Esports,oe:team:3a1d18f46bcb3716ebcfcf4ef068934,1.0,Nautilus,Varus,Ezreal,Jarvan IV,K'Sante,Sion,NaN,NaN,NaN,NaN,NaN,2177,1,1,6,21,25,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.6890,1.2127,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7208,198.6587,0.062652,780.3307,1460.0643,599.0,66,1.8190,17,0.4685,10.0,152,4.1893,10861,6144,169.3339,0.109572,10075.0,NaN,NaN,38.0,38.0,0,NaN,NaN,1.0473,2288.0,2636.0,21.0,2447.0,2977.0,15.0,-159.0,-341.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,3405.0,3162.0,25.0,3834.0,3695.0,21.0,-429.0,-533.0,4.0,0.0,1.0,1.0,0.0,3.0,0.0,4946.0,4895.0,30.0,4941.0,4588.0,26.0,5.0,307.0,4.0,0.0,5.0,2.0,0.0,4.0,0.0,6392.0,7260.0,32.0,6304.0,6695.0,30.0,88.0,565.0,2.0,0.0,8.0,4.0,0.0,10.0,1.0
69980,LOLTMNT01_405652,complete,LCS,2026,Spring,1,2026-06-13 21:09:46,2,16.11,9,Red,bot,Zven,Cloud9,oe:team:fc8e90107dabb9a35c490b0d86adea0,1.0,Jhin,Akali,Karma,Lucian,LeBlanc,K'Sante,NaN,NaN,NaN,NaN,NaN,1460,0,0,0,3,4,24,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1644,1.1507,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,11990,492.7397,0.209835,382.9726,200.4247,1474.0,9,0.3699,2,0.0822,2.0,20,0.8219,9116,5862,240.9041,0.241145,8700.0,NaN,NaN,226.0,226.0,0,NaN,NaN,9.2877,3379.0,3518.0,95.0,3343.0,3887.0,88.0,36.0,-369.0,7.0,0.0,0.0,0.0,0.0,0.0,0.0,5511.0,5914.0,143.0,6164.0,6479.0,142.0,-653.0,-565.0,1.0,0.0,0.0,0.0,1.0,2.0,0.0,7447.0,7917.0,184.0,8834.0,9373.0,194.0,-1387.0,-1456.0,-10.0,0.0,1.0,0.0,1.0,6.0,1.0,9116.0,10325.0,226.0,11715.0,12561.0,247.0,-2599.0,-2236.0,-21.0,0.0,3.0,0.0,2.0,10.0,1.0
107694,LOLTMNT01_462651,complete,HC,2026,Summer,0,2026-09-20 16:08:15,2,16.17,7,Red,jng,Crazzor,Priority,oe:team:502996d9790340c5fd7b86a5b93b1c9,0.0,Zed,Nasus,Shaco,Cassiopeia,NaN,Heimerdinger,NaN,NaN,NaN,NaN,NaN,1983,1,5,9,10,39,44,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,1.1800,2.5113,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,20205,611.3464,0.113749,953.3434,528.9561,1519.0,3,0.0908,4,0.1210,3.0,30,0.9077,14084,9763,295.4009,0.180957,13750.0,NaN,NaN,186.0,34.0,152,NaN,NaN,5.6278,4170.0,3591.0,64.0,4605.0,3865.0,72.0,-435.0,-274.0,-8.0,2.0,1.0,1.0,3.0,0.0,2.0,6186.0,5875.0,102.0,7091.0,6732.0,109.0,-905.0,-857.0,-7.0,3.0,2.0,2.0,5.0,2.0,2.0,8357.0,8594.0,134.0,9576.0,9521.0,140.0,-1219.0,-927.0,-6.0,3.0,3.0,4.0,7.0,5.0,3.0,10714.0,11203.0,150.0,12648.0,12997.0,164.0,-1934.0,-1794.0,-14.0,4.0,6.0,7.0,10.0,10.0,4.0
44312,LOLTMNT02_390920,complete,HC,2026,Spring,0,2026-04-27 18:06:25,2,16.08,9,Red,bot,Kargic,Rugby Club Havířov,oe:team:9207ee887f39a2b40bc365f9bfb0942,0.0,Sivir,Jarvan IV,Jayce,Syndra,Xayah,Yunara,NaN,NaN,NaN,NaN,NaN,2034,0,5,8,16,28,36,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8260,1.8879,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,28063,827.8171,0.221873,766.3717,493.1268,951.0,9,0.2655,2,0.0590,0.0,18,0.5310,14137,9712,286.4897,0.234470,14350.0,NaN,NaN,252.0,238.0,14,NaN,NaN,7.4336,4118.0,3634.0,84.0,3494.0,3330.0,75.0,624.0,304.0,9.0,3.0,2.0,0.0,1.0,0.0,2.0,5767.0,5178.0,107.0,6119.0,5023.0,106.0,-352.0,155.0,1.0,3.0,6.0,3.0,4.0,0.0,4.0,8080.0,7842.0,145.0,9677.0,7849.0,154.0,-1597.0,-7.0,-9.0,3.0,11.0,4.0,5.0,2.0,6.0,10639.0,10849.0,186.0,11900.0,9400.0,203.0,-1261.0,1449.0,-17.0,4.0,12.0,4.0,5.0,2.0,6.0
82071,13388-13388_game_1,complete,LPL,2026,Split 3,0,2026-08-01 12:04:15,1,16.14,4,Blue,bot,Viper,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,Orianna,Poppy,Gnar,Ezreal,Vayne,Renekton,NaN,NaN,NaN,NaN,NaN,2030,1,4,1,9,20,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5911,0.8867,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16664,492.5320,0.185841,344.5123,221.4680,4630.0,18,0.5320,8,0.2365,6.0,40,1.1823,15104,10687,315.8719,0.231565,13269.0,NaN,NaN,290.0,278.0,12,NaN,NaN,8.5714,3491.0,4588.0,101.0,3488.0,4344.0,99.0,3.0,244.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,5698.0,6823.0,150.0,5983.0,7047.0,158.0,-285.0,-224.0,-8.0,0.0,0.0,0.0,0.0,0.0,0.0,7667.0,10024.0,212.0,8455.0,10416.0,231.0,-788.0,-392.0,-19.0,0.0,0.0,0.0,1.0,0.0,0.0,10263.0,12086.0,245.0,10921.0,13413.0,289.0,-658.0,-1327.0,-44.0,2.0,3.0,0.0,1.0,0.0,0.0
57922,LOLTMNT01_390278,complete,VCS,2026,Summer,0,2026-05-20 10:56:44,2,16.09,100,Blue,team,NaN,MVK Esports Academy,oe:team:311b75248911cd31fe0c9cc0ba40215,1.0,NaN,Ezreal,Varus,Ryze,Braum,Seraphine,Jarvan IV,Sion,Aurora,Sett,Miss Fortune,2099,0,16,29,40,16,29,2.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4574,1.2863,0.0,2.0,4.0,2.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,2.0,0.0,0.0,4.0,9.0,0.0,0.0,21.0,38.0,0.0,1.0,93285,2666.5555,NaN,4586.7556,6398.0467,20114.0,119,3.4016,61,1.7437,43.0,338,9.6617,65938,43150,1233.4445,NaN,64535.0,-0.092656,-2.07,NaN,950.0,216,NaN,NaN,33.3302,17476.0,19836.0,361.0,18036.0,20049.0,345.0,-560.0,-213.0,16.0,3.0,3.0,5.0,5.0,5.0,3.0,25954.0,30218.0,536.0,29460.0,32349.0,527.0,-3506.0,-2131.0,9.0,4.0,5.0,11.0,11.0,19.0,4.0,35819.0,42500.0,749.0,41021.0,46584.0,744.0,-5202.0,-4084.0,5.0,5.0,6.0,15.0,15.0,26.0,5.0,48470.0,58438.0,893.0,52541.0,61485.0,919.0,-4071.0,-3047.0,-26.0,12.0,26.0,18.0,18.0,33.0,12.0
70945,LOLTMNT02_425127,complete,NACL,2026,NaN,0,2026-06-18 22:32:56,3,16.12,2,Blue,jng,Verdict,DeathMark E-Sports,NaN,1.0,Wukong,Kindred,Nasus,Hwei,K'Sante,Jarvan IV,NaN,NaN,NaN,NaN,NaN,2469,0,6,5,6,24,27,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5832,1.2394,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,30840,749.4532,0.244519,925.4921,1526.6586,12685.0,7,0.1701,22,0.5346,5.0,74,1.7983,16722,11410,277.2783,0.229981,15108.0,NaN,NaN,274.0,57.0,217,NaN,NaN,6.6586,3197.0,3622.0,70.0,3594.0,3650.0,67.0,-397.0,-28.0,3.0,0.0,0.0,1.0,1.0,1.0,0.0,5971.0,6668.0,116.0,6573.0,7312.0,103.0,-602.0,-644.0,13.0,3.0,0.0,2.0,5.0,2.0,1.0,9074.0,9801.0,161.0,8325.0,9778.0,146.0,749.0,23.0,15.0,4.0,2.0,2.0,5.0,2.0,2.0,12048.0,12921.0,192.0,11135.0,13354.0,196.0,913.0,-433.0,-4.0,6.0,4.0,2.0,7.0,3.0,2.0
7380,13099-13099_game_3,complete,LPL,2026,Split 1,0,2026-01-30 12:59:44,3,16.02,1,Blue,top,Bin,Bilibili Gaming,oe:team:d356a144644879dabb5f34cd99c886d,1.0,K'Sante,Malphite,Yunara,Bard,Rell,Lulu,NaN,NaN,NaN,NaN,NaN,1976,0,4,4,3,14,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4251,1.0931,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,21767,660.9413,0.215526,975.0000,1843.5729,2320.0,12,0.3644,4,0.1215,4.0,31,0.9413,12319,8012,243.2794,0.210183,12179.0,NaN,NaN,288.0,288.0,0,NaN,NaN,8.7449,3580.0,5131.0,101.0,3372.0,5348.0,95.0,208.0,-217.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,5703.0,9052.0,156.0,4783.0,8591.0,137.0,920.0,461.0,19.0,1.0,0.0,0.0,0.0,0.0,1.0,7894.0,11945.0,210.0,6592.0,12508.0,193.0,1302.0,-563.0,17.0,1.0,0.0,0.0,0.0,0.0,1.0,9726.0,14715.0,246.0,8722.0,16057.0,246.0,1004.0,-1342.0,0.0,2.0,2.0,1.0,0.0,2.0,2.0

In [253]:
df = df.drop(columns = 'playoffs')

In [254]:
df.sample(10)

,gameid,datacompleteness,league,year,split,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
101362,LOLTMNT01_457428,complete,LCS,2026,Summer,2026-09-06 20:57:45,2,16.17,100,Blue,team,NaN,Shopify Rebellion,oe:team:b360f1d729b0a8e0f29a5243c4200fa,1.0,NaN,Syndra,Vi,Bard,Olaf,Jarvan IV,Lee Sin,Ashe,Seraphine,K'Sante,Azir,1923,0,7,26,13,7,26,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2184,1.0296,0.0,0.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,3.0,10.0,1.0,0.0,17.0,40.0,0.0,2.0,68899,2149.7348,NaN,3737.8783,3585.2106,17805.0,115,3.5881,44,1.3729,40.0,277,8.6427,53647,32654,1018.8456,NaN,52245.0,-0.148014,-2.01,NaN,874.0,195,NaN,NaN,33.3541,17414.0,21043.0,356.0,16601.0,20271.0,365.0,813.0,772.0,-9.0,3.0,4.0,1.0,1.0,1.0,4.0,26276.0,33200.0,555.0,25983.0,32210.0,549.0,293.0,990.0,6.0,4.0,7.0,4.0,4.0,6.0,5.0,33844.0,42751.0,723.0,37729.0,46859.0,747.0,-3885.0,-4108.0,-24.0,4.0,7.0,9.0,9.0,19.0,5.0,43596.0,54820.0,913.0,48125.0,61137.0,929.0,-4529.0,-6317.0,-16.0,5.0,10.0,11.0,11.0,25.0,6.0
72403,LOLTMNT01_417464,complete,LRN,2026,Split 2,2026-07-04 20:32:59,2,16.13,8,Red,mid,Sweeho,LYON Academy,oe:team:6a7a3de886a10bd30d57577290fb45e,0.0,Akali,Nocturne,Ambessa,Jarvan IV,Kai'Sa,Draven,NaN,NaN,NaN,NaN,NaN,2034,0,12,10,5,25,43,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7375,2.0059,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,42024,1239.6460,0.306277,1266.6667,741.5044,6465.0,11,0.3245,6,0.1770,4.0,50,1.4749,15874,11449,337.7286,0.240197,14850.0,NaN,NaN,207.0,207.0,0,NaN,NaN,6.1062,4222.0,5108.0,67.0,2837.0,4458.0,71.0,1385.0,650.0,-4.0,4.0,1.0,0.0,0.0,0.0,3.0,6062.0,7619.0,108.0,4522.0,6874.0,110.0,1540.0,745.0,-2.0,6.0,1.0,1.0,0.0,2.0,4.0,7343.0,9559.0,131.0,7563.0,10267.0,146.0,-220.0,-708.0,-15.0,6.0,2.0,3.0,4.0,4.0,5.0,11886.0,12038.0,154.0,10198.0,13052.0,183.0,1688.0,-1014.0,-29.0,10.0,2.0,6.0,8.0,7.0,6.0
62190,LOLTMNT02_414210,complete,LJL,2026,Spring,2026-05-27 10:13:36,3,16.10,7,Red,jng,Grit,DetonatioN FocusMe Academy,oe:team:845f7165c7cdaad9d2a2d764375d0df,0.0,Sejuani,Vi,Jarvan IV,Ambessa,Jax,Gwen,NaN,NaN,NaN,NaN,NaN,1817,0,1,4,6,9,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2972,1.1558,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10434,344.5460,0.159315,855.1569,941.8382,0.0,13,0.4293,16,0.5283,12.0,76,2.5096,9590,5608,185.1844,0.170057,8950.0,NaN,NaN,147.0,38.0,109,NaN,NaN,4.8542,3327.0,3516.0,65.0,4188.0,4256.0,79.0,-861.0,-740.0,-14.0,0.0,2.0,0.0,2.0,0.0,0.0,5043.0,5849.0,96.0,5904.0,6231.0,104.0,-861.0,-382.0,-8.0,0.0,4.0,1.0,3.0,2.0,0.0,6710.0,8052.0,128.0,7680.0,8900.0,138.0,-970.0,-848.0,-10.0,0.0,5.0,1.0,3.0,2.0,0.0,7562.0,8571.0,135.0,9744.0,11356.0,165.0,-2182.0,-2785.0,-30.0,0.0,5.0,2.0,5.0,3.0,0.0
62928,LOLTMNT02_413692,complete,LCKC,2026,Rounds 1-2,2026-05-28 06:01:31,2,16.10,1,Blue,top,Kangin,BNK FEARX Youth,oe:team:20edec57649c30e1ed81e4b42634ac1,0.0,Ambessa,Nocturne,Lucian,Karma,Skarner,Vi,NaN,NaN,NaN,NaN,NaN,1904,0,3,3,1,11,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3466,1.2290,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,13168,414.9580,0.171713,717.6996,1199.7479,4918.0,11,0.3466,9,0.2836,2.0,33,1.0399,12218,8058,253.9286,0.216641,12150.0,NaN,NaN,274.0,266.0,8,NaN,NaN,8.6345,3490.0,5472.0,98.0,3325.0,5025.0,90.0,165.0,447.0,8.0,0.0,0.0,0.0,0.0,0.0,0.0,5451.0,8609.0,147.0,5554.0,8787.0,145.0,-103.0,-178.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,8629.0,12622.0,211.0,8396.0,12963.0,207.0,233.0,-341.0,4.0,1.0,0.0,0.0,1.0,1.0,0.0,10649.0,14667.0,247.0,10747.0,17037.0,256.0,-98.0,-2370.0,-9.0,3.0,0.0,1.0,2.0,4.0,0.0
89725,LOLTMNT01_443493,complete,NACL,2026,Summer,2026-08-14 03:34:42,2,16.15,2,Blue,jng,Kisno,NRG,oe:team:e758ebe9a5a2cc81b9c8078479c2d87,0.0,Xin Zhao,Shen,Pantheon,Varus,Jhin,Bard,NaN,NaN,NaN,NaN,NaN,1381,1,4,0,7,21,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.9124,1.2165,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15352,666.9949,0.197560,1069.3990,654.3519,6875.0,10,0.4345,9,0.3910,7.0,39,1.6944,10826,7733,335.9739,0.199263,9450.0,NaN,NaN,175.0,16.0,159,NaN,NaN,7.6032,3369.0,4022.0,74.0,3491.0,4009.0,73.0,-122.0,13.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,6001.0,6647.0,109.0,4788.0,5665.0,101.0,1213.0,982.0,8.0,3.0,1.0,0.0,0.0,1.0,2.0,8822.0,9600.0,148.0,7107.0,7808.0,128.0,1715.0,1792.0,20.0,4.0,3.0,0.0,2.0,2.0,3.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
95350,LOLTMNT05_219225,complete,EBL,2026,Summer,2026-08-25 17:52:27,3,16.16,100,Blue,team,NaN,Magaza Esports,oe:team:8b7f6ca4d6c6251072fa4044da4d8b3,1.0,NaN,Lee Sin,Nocturne,NaN,Ezreal,Sivir,Syndra,Camille,Sejuani,Aphelios,Tahm Kench,1815,0,6,27,8,6,27,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.1983,1.0909,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,1.0,2.0,9.0,0.0,0.0,15.0,37.0,0.0,1.0,73746,2437.8843,NaN,3967.7025,4060.9256,14881.0,90,2.9752,33,1.0909,38.0,241,7.9669,53688,33797,1117.2562,NaN,51623.0,-0.135479,-2.88,NaN,874.0,190,NaN,NaN,35.1736,16156.0,20611.0,359.0,18574.0,21293.0,339.0,-2418.0,-682.0,20.0,1.0,0.0,6.0,6.0,10.0,1.0,25601.0,33467.0,553.0,27016.0,33619.0,530.0,-1415.0,-152.0,23.0,3.0,2.0,8.0,8.0,13.0,3.0,35439.0,44065.0,738.0,38692.0,47981.0,738.0,-3253.0,-3916.0,0.0,3.0,2.0,12.0,12.0,24.0,3.0,44064.0,54871.0,894.0,51231.0,63773.0,890.0,-7167.0,-8902.0,4.0,5.0,7.0,17.0,17.0,43.0,5.0
1605,LOLTMNT05_172141,complete,LIT,2026,Winter,2026-01-16 17:13:20,1,16.01,10,Red,sup,downfall,P11 Esports,oe:team:51815048971b363597530c6d350a27f,0.0,Neeko,Dr. Mundo,Gwen,Naafiri,Ekko,Akali,NaN,NaN,NaN,NaN,NaN,1546,0,0,6,2,6,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2329,1.2031,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9283,360.2717,0.151258,713.0530,290.1035,0.0,30,1.1643,6,0.2329,6.0,80,3.1048,6103,2674,103.7775,0.099073,5695.0,NaN,NaN,36.0,36.0,0,NaN,NaN,1.3972,2370.0,2751.0,21.0,2639.0,2592.0,5.0,-269.0,159.0,16.0,0.0,0.0,1.0,0.0,2.0,0.0,3544.0,3672.0,26.0,4022.0,3719.0,7.0,-478.0,-47.0,19.0,0.0,1.0,3.0,1.0,2.0,0.0,4759.0,5187.0,33.0,5884.0,5941.0,11.0,-1125.0,-754.0,22.0,0.0,1.0,5.0,2.0,5.0,1.0,5969.0,7143.0,36.0,8211.0,9040.0,19.0,-2242.0,-1897.0,17.0,0.0,2.0,6.0,2.0,12.0,1.0
77497,LOLTMNT05_213051,complete,LFL,2026,NaN,2026-07-23 17:00:01,1,16.14,2,Blue,jng,Kaboom,Ici Japon Corp. Esport,oe:team:7d2c778dc03e3fe0db9e45a57895b88,1.0,Lee Sin,Poppy,Cassiopeia,Ezreal,Sion,Jhin,NaN,NaN,NaN,NaN,NaN,1667,0,1,5,3,4,14,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.1440,0.6479,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,2.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9336,336.0288,0.131149,793.2094,631.1338,0.0,11,0.3959,6,0.2160,5.0,40,1.4397,9709,6033,217.1446,0.212880,9450.0,NaN,NaN,198.0,13.0,185,NaN,NaN,7.1266,3418.0,4198.0,78.0,3857.0,4179.0,80.0,-439.0,19.0,-2.0,0.0,0.0,1.0,0.0,2.0,0.0,5322.0,6647.0,115.0,5806.0,6795.0,118.0,-484.0,-148.0,-3.0,0.0,3.0,2.0,1.0,2.0,0.0,6806.0,8495.0,144.0,8574.0,9620.0,161.0,-1768.0,-1125.0,-17.0,0.0,3.0,3.0,3.0,3.0,0.0,8868.0,11152.0,185.0,11731.0,12597.0,194.0,-2863.0,-1445.0,-9.0,1.0,3.0,4.0,6.0,3.0,0.0
34402,LOLTMNT01_361987,complete,LCP,2026,Split 2,2026-04-11 12:58:20,2,16.07,100,Blue,team,NaN,GAM Esports,oe:team:9cae7677cd0dbcc1cd86653870b73c2,1.0,NaN,Akali,Vi,Sion,K'Sante,Leona,Jarvan IV,Jayce,Mel,Sivir,Neeko,1872,0,7,11,13,7,11,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2244,0.5769,0.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,3.0,7.0,0.0,0.0,16.0,32.0,0.0,1.0,65871,2111.2500,NaN,2486.6026,1851.2500,14868.0,128,4.1026,51,1.6346,46.0,313,10.0321,53476,33004,1057.8205,NaN,51525.0,-0.017431,-0.74,NaN,886.0,172,NaN,NaN,33.9103,16238.0,19459.0,338.0,16824.0,20052.0,351.0,-586.0,-593.0,-13.0,1.0,2.0,2.0,2.0,2.0,1.0,25870.0,31454.0,531.0,27370.0,32767.0,566.0,-1500.0,-1313.0,-35.0,3.0,4.0,4.0,4.0,4.0,3.0,36238.0,43860.0,727.0,35983.0,43533.0,765.0,255.0,327.0,-38.0,6.0,10.0,4.0,4.0,4.0,6.0,44531.0,54010.0,912.0,44675.0,54880.0,951.0,-144.0,-870.0,-39.0,6.0,10.0,4.0,4.0,4.0,6.0
11745,13120-13120_game_2,complete,LPL,2026,Split 1,2026-02-07 12:12:44,2,16.02,10,Red,sup,Zhuo,Ninjas in Pyjamas,oe:team:48d7941ccbd5b89aca46c57b0c2f8fb,0.0,Bard,Orianna,Jayce,Dr. Mundo,Nautilus,Leona,NaN,NaN,NaN,NaN,NaN,1909,1,0,2,15,20,8,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.6286,0.8800,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,6802,213.7873,0.093941,520.1991,267.1241,967.0,69,2.1687,32,1.0058,15.0,189,5.9403,9092,4922,154.6988,0.100055,7690.0,NaN,NaN,43.0,43.0,0,NaN,NaN,1.3515,2602.0,2346.0,13.0,2311.0,2240.0,14.0,291.0,106.0,-1.0,0.0,1.0,0.0,0.0,0.0,1.0,3855.0,3330.0,20.0,3419.0,3217.0,22.0,436.0,113.0,-2.0,0.0,4.0,0.0,0.0,0.0,2.0,5172.0,4686.0,33.0,4636.0,4124.0,28.0,536.0,562.0,5.0,0.0,4.0,0.0,0.0,1.0,2.0,6346.0,6090.0,38.0,5961.0,5013.0,33.0,385.0,1077.0,5.0,0.0,6.0,1.0,0.0,2.0,3.0

In [255]:
df = df.drop(columns='datacompleteness')

In [256]:
df.columns.tolist()

['gameid',
 'league',
 'year',
 'split',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [257]:
df['year'].nunique()

2

In [258]:
df['year'].unique()

array([2026, 2027])

In [259]:
df = df.drop(columns='year')

In [260]:
df.sample(15)

,gameid,league,split,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
109252,LOLTMNT02_468622,VCS,Finals,2026-09-25 11:36:08,4,16.18,5,Blue,sup,Elio,Saigon Warriors,oe:team:ae60cc9a2621d479d88fb39258c8e44,1.0,Neeko,Jayce,Pantheon,Renekton,Yorick,Viego,NaN,NaN,NaN,NaN,NaN,1929,1,1,1,4,15,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4666,0.5599,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9248,287.6516,0.127823,316.4230,146.9362,2656.0,65,2.0218,11,0.3421,26.0,123,3.8258,8515,4304,133.8725,0.086550,6555.0,NaN,NaN,37.0,37.0,0,NaN,NaN,1.1509,2303.0,2464.0,11.0,2411.0,2610.0,10.0,-108.0,-146.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,3767.0,3231.0,21.0,3726.0,3676.0,23.0,41.0,-445.0,-2.0,1.0,0.0,0.0,0.0,0.0,0.0,5072.0,5303.0,26.0,4983.0,5594.0,29.0,89.0,-291.0,-3.0,1.0,1.0,1.0,0.0,0.0,0.0,6369.0,6426.0,30.0,6024.0,6581.0,32.0,345.0,-155.0,-2.0,1.0,2.0,1.0,0.0,1.0,0.0
41735,LOLTMNT05_186302,TCL,Spring,2026-04-23 15:33:55,2,16.08,200,Red,team,NaN,Team Phoenix,oe:team:445fca0316af5c74e06054968209184,0.0,NaN,Rumble,Nautilus,Nami,Gnar,Sivir,Yunara,Lulu,Xin Zhao,Sylas,Cho'Gath,1552,0,3,16,9,3,16,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.1160,0.7345,0.0,1.0,2.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,11.0,0.0,0.0,10.0,45.0,0.0,2.0,40717,1574.1108,NaN,3758.7371,2817.4871,12921.0,64,2.4742,23,0.8892,20.0,174,6.7268,42786,25578,988.8402,NaN,40310.0,-0.264277,-4.49,NaN,665.0,126,NaN,NaN,30.5799,14797.0,19785.0,321.0,16515.0,21159.0,377.0,-1718.0,-1374.0,-56.0,0.0,0.0,0.0,0.0,0.0,0.0,21956.0,29933.0,473.0,28680.0,34311.0,581.0,-6724.0,-4378.0,-108.0,0.0,0.0,5.0,5.0,12.0,0.0,30330.0,40139.0,629.0,40385.0,46792.0,786.0,-10055.0,-6653.0,-157.0,0.0,0.0,7.0,7.0,18.0,0.0,41808.0,55171.0,777.0,53112.0,63226.0,967.0,-11304.0,-8055.0,-190.0,3.0,9.0,11.0,11.0,30.0,3.0
90399,LOLTMNT05_217160,LEC,Summer,2026-08-15 17:02:23,1,16.16,4,Blue,bot,Hans Sama,G2 Esports,oe:team:7d6673d3a9d00363c6bebc1a630da6e,0.0,Varus,Cassiopeia,Vi,Locke,Ezreal,Trundle,NaN,NaN,NaN,NaN,NaN,2922,1,5,3,4,16,19,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3285,0.7187,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,28288,580.8624,0.271875,704.5996,411.1088,12389.0,22,0.4517,26,0.5339,7.0,93,1.9097,24158,17922,368.0082,0.286884,21525.0,NaN,NaN,506.0,461.0,45,NaN,NaN,10.3901,4126.0,4283.0,101.0,3060.0,3380.0,74.0,1066.0,903.0,27.0,1.0,0.0,0.0,0.0,0.0,1.0,6640.0,7127.0,165.0,5342.0,6178.0,131.0,1298.0,949.0,34.0,1.0,0.0,0.0,0.0,0.0,1.0,9759.0,10183.0,228.0,7544.0,8635.0,193.0,2215.0,1548.0,35.0,3.0,1.0,0.0,0.0,0.0,1.0,12338.0,12787.0,287.0,10174.0,11930.0,257.0,2164.0,857.0,30.0,4.0,1.0,1.0,0.0,1.0,1.0
10303,13111-13111_game_2,LPL,Split 1,2026-02-05 12:25:13,2,16.02,8,Red,mid,Creme,Top Esports,oe:team:fcec508e780bbd1ad493852640f5b36,0.0,Ryze,Jayce,Neeko,Jarvan IV,Anivia,Bard,NaN,NaN,NaN,NaN,NaN,1690,1,4,0,5,13,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4615,0.7101,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,20946,743.6450,0.330019,600.7101,474.7456,10213.0,16,0.5680,18,0.6391,5.0,57,2.0237,13238,9515,337.8107,0.229643,10895.0,NaN,NaN,301.0,301.0,0,NaN,NaN,10.6864,3856.0,5000.0,101.0,3997.0,5094.0,104.0,-141.0,-94.0,-3.0,1.0,0.0,0.0,1.0,0.0,1.0,6355.0,8485.0,159.0,5929.0,7905.0,154.0,426.0,580.0,5.0,2.0,1.0,0.0,2.0,1.0,2.0,8748.0,11750.0,230.0,7978.0,12711.0,219.0,770.0,-961.0,11.0,2.0,2.0,0.0,2.0,1.0,2.0,10651.0,15320.0,268.0,9568.0,15180.0,265.0,1083.0,140.0,3.0,3.0,3.0,0.0,2.0,1.0,2.0
6777,LOLTMNT01_332352,HW,NaN,2026-01-29 17:06:19,2,16.02,10,Red,sup,Mita,eSuba,oe:team:3faefd9245a4ef6ba347fbcf2a51515,0.0,Braum,Jayce,Ryze,Orianna,Lulu,Karma,NaN,NaN,NaN,NaN,NaN,1589,0,0,10,9,12,31,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4531,1.6237,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5822,219.8364,0.060644,1131.0132,985.4877,0.0,31,1.1705,2,0.0755,6.0,60,2.2656,6372,2855,107.8037,0.095703,6010.0,NaN,NaN,13.0,13.0,0,NaN,NaN,0.4909,2465.0,2869.0,10.0,2515.0,3168.0,15.0,-50.0,-299.0,-5.0,0.0,3.0,2.0,0.0,3.0,1.0,3682.0,4275.0,12.0,4225.0,5066.0,23.0,-543.0,-791.0,-11.0,0.0,6.0,4.0,1.0,7.0,1.0,4777.0,5479.0,13.0,5726.0,6574.0,26.0,-949.0,-1095.0,-13.0,0.0,8.0,6.0,1.0,12.0,2.0,6105.0,6671.0,13.0,7553.0,9484.0,28.0,-1448.0,-2813.0,-15.0,0.0,9.0,9.0,1.0,20.0,2.0
83950,LOLTMNT01_435898,LRS,Split 2,2026-08-04 22:03:17,3,16.15,100,Blue,team,NaN,Malvinas Gaming,oe:team:d5772fdb1ae7fcc8046fa2e056a8715,0.0,NaN,Jayce,Locke,Ziggs,LeBlanc,Aurora,Naafiri,Xerath,Pantheon,Ambessa,Miss Fortune,1434,0,6,21,11,6,21,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.2510,1.1297,0.0,0.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,8.0,0.0,0.0,9.0,34.0,0.0,1.0,62444,2612.7197,NaN,3445.8577,2516.4017,6364.0,69,2.8870,21,0.8787,26.0,157,6.5690,40077,24072,1007.1967,NaN,37980.0,-0.196174,-3.84,NaN,667.0,140,NaN,NaN,33.7657,16265.0,19048.0,299.0,18818.0,20297.0,328.0,-2553.0,-1249.0,-29.0,3.0,5.0,8.0,8.0,10.0,3.0,24735.0,30600.0,480.0,29294.0,33418.0,524.0,-4559.0,-2818.0,-44.0,4.0,6.0,11.0,11.0,17.0,4.0,34638.0,43868.0,686.0,40718.0,46827.0,735.0,-6080.0,-2959.0,-49.0,6.0,11.0,15.0,15.0,24.0,6.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81273,LOLTMNT05_213640,LFL,NaN,2026-07-30 17:58:34,1,16.14,10,Red,sup,Mersa,Joblife,oe:team:7380b73561abdd86c2391e9481acd4b,0.0,Rell,Syndra,Orianna,Locke,Gnar,Ambessa,NaN,NaN,NaN,NaN,NaN,2268,0,1,6,16,22,25,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.5820,1.2434,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7826,207.0370,0.080347,764.8148,1003.2011,0.0,78,2.0635,17,0.4497,31.0,164,4.3386,9721,4819,127.4868,0.105962,9410.0,NaN,NaN,33.0,33.0,0,NaN,NaN,0.8730,2652.0,2303.0,13.0,2608.0,2432.0,12.0,44.0,-129.0,1.0,1.0,1.0,2.0,0.0,3.0,2.0,3821.0,3364.0,20.0,3732.0,3924.0,20.0,89.0,-560.0,0.0,1.0,3.0,3.0,0.0,4.0,3.0,5042.0,4558.0,23.0,4848.0,5372.0,22.0,194.0,-814.0,1.0,1.0,5.0,3.0,0.0,5.0,4.0,6335.0,5674.0,27.0,6328.0,6986.0,23.0,7.0,-1312.0,4.0,1.0,9.0,5.0,0.0,8.0,7.0
17027,LOLTMNT02_355562,RL,Winter,2026-02-19 20:29:16,2,16.03,200,Red,team,NaN,Onion Team,oe:team:7119e0d00f85f16ce1fc32c5862f3d6,0.0,NaN,Rumble,Caitlyn,Varus,Akali,Syndra,Neeko,Vi,Kog'Maw,Ezreal,Dr. Mundo,1627,0,15,32,23,15,32,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.5532,1.7333,1.0,1.0,2.0,1.0,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,4.0,11.0,1.0,0.0,23.0,45.0,0.0,3.0,77485,2857.4677,NaN,4991.5427,2995.5009,27995.0,63,2.3233,23,0.8482,11.0,146,5.3841,52362,34389,1268.1868,NaN,52758.0,-0.148371,-2.94,NaN,778.0,140,NaN,NaN,33.8537,16896.0,18967.0,313.0,19311.0,19216.0,356.0,-2415.0,-249.0,-43.0,4.0,5.0,7.0,7.0,10.0,5.0,26539.0,31481.0,514.0,30519.0,31459.0,545.0,-3980.0,22.0,-31.0,6.0,7.0,9.0,9.0,14.0,7.0,38244.0,43868.0,708.0,42740.0,46708.0,756.0,-4496.0,-2840.0,-48.0,10.0,15.0,15.0,15.0,23.0,11.0,47291.0,55618.0,856.0,59019.0,65653.0,939.0,-11728.0,-10035.0,-83.0,12.0,19.0,24.0,24.0,35.0,13.0
61263,LOLTMNT02_411758,LCKC,Rounds 1-2,2026-05-25 10:51:17,2,16.10,4,Blue,bot,OddEye,HANJIN BRION Challengers,oe:team:fa3d687a87bcae80362f784a7da571d,0.0,Caitlyn,Orianna,Jarvan IV,Karma,Lee Sin,Naafiri,NaN,NaN,NaN,NaN,NaN,2153,0,0,1,8,11,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3065,0.7246,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19120,532.8379,0.236195,428.6670,324.5797,5315.0,19,0.5295,13,0.3623,6.0,56,1.5606,15529,10861,302.6753,0.269368,15550.0,NaN,NaN,392.0,374.0,18,NaN,NaN,10.9243,3538.0,3365.0,76.0,3507.0,3156.0,74.0,31.0,209.0,2.0,0.0,3.0,0.0,1.0,2.0,2.0,5539.0,5406.0,128.0,5892.0,5502.0,131.0,-353.0,-96.0,-3.0,0.0,3.0,0.0,2.0,2.0,2.0,7830.0,7897.0,195.0,8132.0,7952.0,194.0,-302.0,-55.0,1.0,0.0,3.0,0.0,2.0,2.0,2.0,10276.0,10586.0,263.0,11541.0,11662.0,271.0,-1265.0,-1076.0,-8.0,0.0,4.0,0.0,3.0,3.0,2.0
77189,LOLTMNT02_435575,LPLOL,Summer,2026-07-22 20:11:01,1,16.14,6,Red,top,WG FIK,Way Gaming Esports,NaN,0.0,K'Sante,Lee Sin,Riven,Bard,Ambessa,Poppy,NaN,NaN,NaN,NaN,NaN,1786,0,1,7,4,18,26,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6047,1.4782,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,7820,262.7100,0.093436,916.0246,1149.7424,0.0,13,0.4367,4,0.1344,1.0,32,1.0750,8328,4409,148.1187,0.133869,8475.0,NaN,NaN,184.0,180.0,4,NaN,NaN,6.1814,2719.0,4518.0,53.0,3957.0,4927.0,87.0,-1238.0,-409.0,-34.0,0.0,1.0,2.0,2.0,0.0,1.0,4068.0,7727.0,94.0,6983.0,9527.0,146.0,-2915.0,-1800.0,-52.0,0.0,1.0,3.0,4.0,0.0,1.0,5308.0,9384.0,124.0,9691.0,13206.0,184.0,-4383.0,-3822.0,-60.0,0.0,1.0,5.0,5.0,3.0,1.0,7194.0,12431.0,158.0,11232.0,15644.0,217.0,-4038.0,-3213.0,-59.0,1.0,4.0,5.0,5.0,5.0,2.0
40171,LOLTMNT02_381624,CD,Split 1,2026-04-20 21:41:27,1,16.08,8,Red,mid,Dioge,Team Solid,oe:team:417b52ed11031f54e82d5b16592957e,1.0,Ahri,Karma,Ryze,Nautilus,Mel,Akali,NaN,NaN,NaN,NaN,NaN,2005,0,5,3,3,10,21,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2993,0.9277,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,21892,655.1222,0.244497,704.5885,340.1596,6196.0,11,0.3292,8,0.2394,8.0,40,1.1970,12653,8287,247.9900,0.233068,12300.0,NaN,NaN,273.0,273.0,0,NaN,NaN,8.1696,3121.0,4595.0,84.0,4081.0,4631.0,94.0,-960.0,-36.0,-10.0,0.0,0.0,0.0,2.0,0.0,0.0,5357.0,6921.0,127.0,5503.0,6936.0,136.0,-146.0,-15.0,-9.0,2.0,0.0,0.0,2.0,0.0,0.0,8104.0,9638.0,182.0,7524.0,10052.0,189.0,580.0,-414.0,-7.0,4.0,0.0,0.0,2.0,1.0,0.0,10312.0,11961.0,229.0,10642.0,12983.0,232.0,-330.0,-1022.0,-3.0,5.0,0.0,1.0,6.0,2.0,0.0
22117,LOLTMNT06_171307,NLC,Winter,2026-03-05 17:09:59,1,16.04,2,Blue,jng,Mafro,Verdant,oe:team:b33646d7b7b14dd6da17a88f6ddb592,0.0,Pantheon,Orianna,Rumble,Varus,Ashe,Nami,NaN,NaN,NaN,NaN,NaN,1810,1,8,3,8,27,6,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.8950,1.0939,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19466,645.2818,0.183938,947.1050,665.7680,1767.0,5,0.1657,3,0.0994,4.0,24,0.7956,12874,8906,295.2265,0.189728,11300.0,NaN,NaN,177.0,10.0,167,NaN,NaN,5.8674,3541.0,3645.0,66.0,3728.0,3689.0,70.0,-187.0,-44.0,-4.0,1.0,1.0,2.0,1.0,1.0,1.0,5956.0,6465.0,110.0,5382.0,5924.0,113.0,574.0,541.0,-3.0,3.0,1.0,2.0,1.0,1.0,1.0,8608.0,9513.0,134.0,7039.0,7992.0,141.0,1569.0,1521.0,-7.0,5.0,6.0,2.0,1.0,2.0,3.0,10719.0,12243.0,158.0,8219.0,9971.0,160.0,2500.0,2272.0,-2.0,6.0,8.0,3.0,1.0,3.0,4.0
10494,LOLTMNT04_152699,LIT,Winter,2026-02-05 18:03:58,2,16.02,7,Red,jng,Jekko,Zena Esports,oe:team:01d50b1de5bdc717131b31c64378a5b,0.0,Xin Zhao,Varus,Wukong,Nocturne,Caitlyn,Aphelios,NaN,NaN,NaN,NaN,NaN,1696,0,2,3,1,6,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2123,0.7429,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,9625,340.5071,0.163986,830.9788,866.9929,1647.0,4,0.1415,4,0.1415,3.0,22,0.7783,9196,5461,193.1958,0.191224,8875.0,NaN,NaN,189.0,18.0,171,NaN,NaN,6.6863,3805.0,4264.0,81.0,3285.0,3504.0,69.0,520.0,760.0,12.0,1.0,0.0,1.0,0.0,1.0,1.0,5577.0,6627.0,120.0,4840.0,5511.0,103.0,737.0,1116.0,17.0,2.0,0.0,1.0,0.0,2.0,1.0,7099.0,8682.0,155.0,6917.0,8567.0,150.0,182.0,115.0,5.0,2.0,0.0,1.0,0.0,4.0,1.0,8586.0,10662.0,181.0,9331.0,11803.0,181.0,-745.0,-1141.0,0.0,2.0,1.0,1.0,1.0,7.0,1.0
62637,LOLTMNT05_195369,LFL,NaN,2026-05-27 18:09:25,3,16.10,10,Red,sup,Prime,Karmine Corp Blue,oe:team:42bf6c1040db8f2221ff017fa4d34e4,0.0,Neeko,Orianna,Anivia,Lulu,Elise,Pyke,NaN,NaN,NaN,NaN,NaN,2106,0,0,5,6,9,23,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2564,0.9117,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9224,262.7920,0.117791,581.1681,420.8547,411.0,62,1.7664,12,0.3419,10.0,125,3.5613,8114,3542,100.9117,0.092572,7960.0,NaN,NaN,28.0,28.0,0,NaN,NaN,0.7977,2408.0,2607.0,15.0,2513.0,2712.0,12.0,-105.0,-105.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,3794.0,4026.0,18.0,4051.0,3672.0,20.0,-257.0,354.0,-2.0,0.0,3.0,1.0,0.0,4.0,1.0,4979.0,4972.0,21.0,5548.0,5066.0,27.0,-569.0,-94.0,-6.0,0.0,4.0,2.0,0.0,6.0,1.0,5986.0,6920.0,22.0,7199.0,6090.0,34.0,-1213.0,830.0,-12.0,0.0,5.0,2.0,1.0,7.0,1.0
83787,LOLTMNT04_182285,PRM,Summer,2026-08-04 19:24:44,2,16.15,4,Blue,bot,DenVoksne,Unicorns of Love Sexy Edition,oe:team:6a060bd74c9041bf0aa89adf9d15d12,1.0,Vladimir,Poppy,Jarvan IV,Skarner,Swain,Renekton,NaN,NaN,NaN,NaN,NaN,1716,1,4,1,4,23,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.8042,1.2238,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,21306,744.9650,0.228016,965.1049,454.2657,8238.0,8,0.2797,4,0.1399,2.0,30,1.0490,14048,10272,359.1608,0.238985,11900.0,NaN,NaN,279.0,273.0,6,NaN,NaN,9.7552,3579.0,4371.0,83.0,3396.0,4433.0,95.0,183.0,-62.0,-12.0,1.0,0.0,0.0,0.0,0.0,1.0,6484.0,7084.0,133.0,5701.0,6779.0,144.0,783.0,305.0,-11.0,2.0,0.0,0.0,0.0,0.0,2.0,8681.0,9910.0,184.0,7915.0,9285.0,194.0,766.0,625.0,-10.0,2.0,1.0,0.0,1.0,0.0,3.0,11377.0,12906.0,250.0,10725.0,12725.0,263.0,652.0,181.0,-13.0,2.0,1.0,0.0,1.0,1.0,3.0

In [261]:
df

,gameid,league,split,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
36,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,1,Blue,top,Diobello,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Gnar,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,7,6,1,22,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21194,724.1686,0.226739,870.7175,702.4374,8005.0,10,0.3417,3,0.1025,0.0,27,0.9226,12087,8229,281.1731,0.221322,10033.0,NaN,NaN,189.0,187.0,2,NaN,NaN,6.4579,2647.0,4230.0,57.0,4017.0,5185.0,85.0,-1370.0,-955.0,-28.0,0.0,0.0,2.0,2.0,0.0,0.0,5857.0,8207.0,109.0,7296.0,8799.0,123.0,-1439.0,-592.0,-14.0,1.0,0.0,2.0,5.0,1.0,2.0,8993.0,12371.0,147.0,9225.0,11307.0,158.0,-232.0,1064.0,-11.0,5.0,1.0,3.0,6.0,4.0,3.0,10372.0,13489.0,164.0,11475.0,14049.0,192.0,-1103.0,-560.0,-28.0,6.0,1.0,4.0,7.0,4.0,4.0
37,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,2,Blue,jng,Mario,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Xin Zhao,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,5,7,3,22,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16300,556.9476,0.174382,1230.5809,709.1344,0.0,3,0.1025,5,0.1708,2.0,26,0.8884,11051,7193,245.7745,0.193459,10850.0,NaN,NaN,180.0,6.0,174,NaN,NaN,6.1503,3798.0,3685.0,66.0,3865.0,4143.0,80.0,-67.0,-458.0,-14.0,2.0,0.0,2.0,1.0,1.0,1.0,5533.0,5956.0,104.0,5829.0,6597.0,120.0,-296.0,-641.0,-16.0,2.0,1.0,3.0,2.0,1.0,2.0,7434.0,7910.0,129.0,8344.0,9734.0,164.0,-910.0,-1824.0,-35.0,3.0,1.0,5.0,4.0,1.0,3.0,9356.0,10417.0,160.0,9942.0,12089.0,194.0,-586.0,-1672.0,-34.0,4.0,2.0,5.0,4.0,2.0,3.0
38,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,3,Blue,mid,DejaVu,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Ahri,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,1,6,5,22,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15244,520.8656,0.163085,644.0091,268.9749,1191.0,11,0.3759,13,0.4442,2.0,45,1.5376,9943,6085,207.9157,0.163660,10010.0,NaN,NaN,226.0,226.0,0,NaN,NaN,7.7221,3373.0,4986.0,86.0,3784.0,5200.0,103.0,-411.0,-214.0,-17.0,0.0,2.0,0.0,1.0,0.0,0.0,5453.0,7073.0,127.0,5452.0,7277.0,143.0,1.0,-204.0,-16.0,1.0,2.0,2.0,2.0,1.0,2.0,7439.0,9601.0,165.0,7564.0,9792.0,165.0,-125.0,-191.0,0.0,1.0,4.0,4.0,5.0,3.0,5.0,9044.0,11959.0,213.0,9377.0,12766.0,221.0,-333.0,-807.0,-8.0,1.0,4.0,4.0,5.0,3.0,5.0
39,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,4,Blue,bot,Rharesh,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Corki,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,8,6,5,22,29,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,31210,1066.4009,0.333893,700.6948,429.9431,8271.0,10,0.3417,6,0.2050,0.0,24,0.8200,15036,11178,381.9362,0.300635,14483.0,NaN,NaN,266.0,262.0,4,NaN,NaN,9.0888,4422.0,3726.0,87.0,3468.0,3609.0,65.0,954.0,117.0,22.0,3.0,0.0,1.0,2.0,0.0,2.0,8051.0,6707.0,124.0,6051.0,5455.0,92.0,2000.0,1252.0,32.0,7.0,1.0,3.0,4.0,3.0,3.0,10664.0,9257.0,176.0,8390.0,8152.0,140.0,2274.0,1105.0,36.0,8.0,3.0,4.0,4.0,6.0,3.0,13164.0,12089.0,232.0,10523.0,10163.0,194.0,2641.0,1926.0,38.0,8.0,3.0,4.0,4.0,6.0,4.0
40,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,5,Blue,sup,Shredder,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Leona,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,1,4,14,22,29,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9525,325.4556,0.101901,784.7494,833.6446,915.0,47,1.6059,11,0.3759,8.0,119,4.0661,8354,4496,153.6219,0.120924,7985.0,NaN,NaN,26.0,26.0,0,NaN,NaN,0.8884,2839.0,2810.0,13.0,2483.0,2024.0,13.0,356.0,786.0,0.0,0.0,4.0,1.0,0.0,1.0,2.0,4713.0,4670.0,18.0,3872.0,3831.0,18.0,841.0,839.0,0.0,1.0,7.0,3.0,0.0,5.0,3.0,6422.0,6258.0,25.0,5193.0,6034.0,21.0,1229.0,224.0,4.0,1.0,11.0,3.0,0.0,10.0,4.0,7421.0,7596.0,26.0,6285.0,7496.0,23.0,1136.0,100.0,3.0,1.0,12.0,3.0,0.0,11.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111967,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,8,Red,mid,Grevthar,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,Lissandra,Naafiri,Jayce,Jax,Renekton,Kennen,NaN,NaN,NaN,NaN,NaN,1685,0,4,4,6,14,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4985,1.5312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,23004,819.1335,0.261951,632.7240,281.2700,4064.0,11,0.3917,6,0.2136,7.0,40,1.4243,10890,7177,255.5608,0.219386,10125.0,NaN,NaN,235.0,235.0,0,NaN,NaN,8.3680,3286.0,4354.0,74.0,4375.0,4894.0,86.0,-1089.0,-540.0,-12.0,1.0,1.0,1.0,3.0,2.0,1.0,5597.0,7522.0,134.0,6991.0,7960.0,142.0,-1394.0,-438.0,-8.0,2.0,1.0,1.0,5.0,2.0,1.0,7727.0,9713.0,164.0,10579.0,11592.0,196.0,-2852.0,-1879.0,-32.0,3.0,2.0,3.0,7.0,5.0,1.0,9968.0,12751.0,211.0,11666.0,12499.0,210.0,-1698.0,252.0,1.0,4.0,6.0,3.0,7.0,6.0,2.0
111968,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,9,Red,bot,Kojima,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,Corki,Naafiri,Jayce,Jax,Renekton,Kennen,NaN,NaN,NaN,NaN,NaN,1685,0,7,5,5,14,29,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4985,1.5312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,31565,1123.9763,0.359437,664.1306,368.1187,2986.0,13,0.4629,8,0.2849,4.0,40,1.4243,15280,11567,411.8813,0.353580,15183.0,NaN,NaN,246.0,242.0,4,NaN,NaN,8.7596,4046.0,3619.0,75.0,3965.0,4004.0,77.0,81.0,-385.0,-2.0,2.0,2.0,2.0,2.0,3.0,1.0,7001.0,6067.0,135.0,6546.0,6520.0,125.0,455.0,-453.0,10.0,3.0,3.0,2.0,2.0,4.0,2.0,9301.0,8505.0,191.0,10206.0,9379.0,165.0,-905.0,-874.0,26.0,3.0,4.0,4.0,5.0,8.0,3.0,14028.0,10696.0,221.0,12645.0,12117.0,225.0,1383.0,-1421.0,-4.0,7.0,5.0,4.0,6.0,8.0,3.0
111969,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,10,Red,sup,Guigs,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,Nautilus,Naafiri,Jayce,Jax,Renekton,Kennen,NaN,NaN,NaN,NaN,NaN,1685,0,0,5,12,14,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4985,1.5312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7131,253.9228,0.081202,659.8576,1009.0682,0.0,51,1.8160,13,0.4629,17.0,113,4.0237,7164,3451,122.8843,0.105490,6860.0,NaN,NaN,40.0,40.0,0,NaN,NaN,1.4243,2656.0,2449.0,20.0,3349.0,2270.0,11.0,-693.0,179.0,9.0,0.0,4.0,2.0,2.0,5.0,0.0,4067.0,4141.0,31.0,4479.0,3517.0,18.0,-412.0,624.0,13.0,0.0,6.0,2.0,2.0,5.0,1.0,5165.0,5646.0,35.0,6238.0,6054.0,23.0,-1073.0,-408.0,12.0,0.0,7.0,4.0,2.0,13.0,1.0,6549.0,7649.0,39.0,7589.0,7565.0,27.0,-1040.0,84.0,12.0,0.0,12.0,4.0,3.0,13.0,2.0
111970,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,100,Blue,team,NaN,LØS,oe:team:ea65e6cc48a9be50fc5334369a5fca5,0.0,NaN,Cassiopeia,Lulu,Orianna,Galio,LeBlanc,Bard,Jarvan IV,Ezreal,Akali,Camille,1685,1,29,14,70,29,14,4.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,1.0326,1.5312,1.0,3.0,0.0,3.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,1.0,1.0,1.0,40.0,10.0,1.0,0.0,95963,3417.0801,NaN,4177.3887,3692.0475,42491.0,96,3.4184,49,1.7448,43.0,292,10.3976,62461,43896,1563.0623,NaN,56096.0,0.121554,3.2,NaN,767.0,197,NaN,NaN,34.3264,18893.0,20515.0,348.0,16701.0,19702.0,312.0,2192.0,813.0,36.0,7.0,16.0,4.0,4.0,9.0,7.0,29543.0,33787.0,540.0,26821.0,32036.0,510.0,2722.0,1751.0,30.0,11.0,21.0,7.0,7.0,13.0,11.0,45207.0,50442.0,718.0,35896.0,42874.0,665.0,9311.0,7568.0,53.0,22.0,48.0,9.0,9.0,17.0,22.0,54313.0,59512.0,857.0,47042.0,54590.0,801.0,7271.0,4922.0,56.0,24.0,51.0,14.0,14.0,32.0,24.0
111971,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,200,Red,team,NaN,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,NaN,Naafiri,Jayce,Jax,Renekton,Kennen,Nocturne,Corki,Nautilus,Ambessa,Lissandra,1685,0,14,29,32,14,29,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4985,1.5312,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0,9.0,0.0,0.0,10.0,40.0,0.0,1.0,87818,3127.0504,NaN,3988.4154,3434.5282,9469.0,96,3.4184,38,1.3531,42.0,257,9.1513,51279,32714,1164.8902,NaN,49668.0,-0.121554,-3.2,NaN,722.0,155,NaN,NaN,31.2285,16701.0,19702.0,312.0,18893.0,20515.0,348.0,-2192.0,-813.0,-36.0,4.0,9.0,7.0,7.0,16.0,4.0,26821.0,32036.0,510.0,29543.0,33787.0,540.0,-2722.0,-1751.0,-30.0,7.0,13.0,11.0,11.0,21.0,7.0,35896.0,42874.0,665.0,45207.0,50442.0,718.0,-9311.0,-7568.0,-53.0,9.0,17.0,22.0,22.0,48.0,9.0,47042.0,54590.0,801.0,54313.0,59512.0,857.0,-7271.0,-4922.0,-56.0,14.0,32.0,24.0,24.0,51.0,14.0

In [262]:
df = df.reset_index(drop=True)

In [263]:
df

,gameid,league,split,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
0,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,1,Blue,top,Diobello,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Gnar,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,7,6,1,22,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,21194,724.1686,0.226739,870.7175,702.4374,8005.0,10,0.3417,3,0.1025,0.0,27,0.9226,12087,8229,281.1731,0.221322,10033.0,NaN,NaN,189.0,187.0,2,NaN,NaN,6.4579,2647.0,4230.0,57.0,4017.0,5185.0,85.0,-1370.0,-955.0,-28.0,0.0,0.0,2.0,2.0,0.0,0.0,5857.0,8207.0,109.0,7296.0,8799.0,123.0,-1439.0,-592.0,-14.0,1.0,0.0,2.0,5.0,1.0,2.0,8993.0,12371.0,147.0,9225.0,11307.0,158.0,-232.0,1064.0,-11.0,5.0,1.0,3.0,6.0,4.0,3.0,10372.0,13489.0,164.0,11475.0,14049.0,192.0,-1103.0,-560.0,-28.0,6.0,1.0,4.0,7.0,4.0,4.0
1,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,2,Blue,jng,Mario,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Xin Zhao,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,5,7,3,22,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,16300,556.9476,0.174382,1230.5809,709.1344,0.0,3,0.1025,5,0.1708,2.0,26,0.8884,11051,7193,245.7745,0.193459,10850.0,NaN,NaN,180.0,6.0,174,NaN,NaN,6.1503,3798.0,3685.0,66.0,3865.0,4143.0,80.0,-67.0,-458.0,-14.0,2.0,0.0,2.0,1.0,1.0,1.0,5533.0,5956.0,104.0,5829.0,6597.0,120.0,-296.0,-641.0,-16.0,2.0,1.0,3.0,2.0,1.0,2.0,7434.0,7910.0,129.0,8344.0,9734.0,164.0,-910.0,-1824.0,-35.0,3.0,1.0,5.0,4.0,1.0,3.0,9356.0,10417.0,160.0,9942.0,12089.0,194.0,-586.0,-1672.0,-34.0,4.0,2.0,5.0,4.0,2.0,3.0
2,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,3,Blue,mid,DejaVu,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Ahri,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,1,6,5,22,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15244,520.8656,0.163085,644.0091,268.9749,1191.0,11,0.3759,13,0.4442,2.0,45,1.5376,9943,6085,207.9157,0.163660,10010.0,NaN,NaN,226.0,226.0,0,NaN,NaN,7.7221,3373.0,4986.0,86.0,3784.0,5200.0,103.0,-411.0,-214.0,-17.0,0.0,2.0,0.0,1.0,0.0,0.0,5453.0,7073.0,127.0,5452.0,7277.0,143.0,1.0,-204.0,-16.0,1.0,2.0,2.0,2.0,1.0,2.0,7439.0,9601.0,165.0,7564.0,9792.0,165.0,-125.0,-191.0,0.0,1.0,4.0,4.0,5.0,3.0,5.0,9044.0,11959.0,213.0,9377.0,12766.0,221.0,-333.0,-807.0,-8.0,1.0,4.0,4.0,5.0,3.0,5.0
3,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,4,Blue,bot,Rharesh,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Corki,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,8,6,5,22,29,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,31210,1066.4009,0.333893,700.6948,429.9431,8271.0,10,0.3417,6,0.2050,0.0,24,0.8200,15036,11178,381.9362,0.300635,14483.0,NaN,NaN,266.0,262.0,4,NaN,NaN,9.0888,4422.0,3726.0,87.0,3468.0,3609.0,65.0,954.0,117.0,22.0,3.0,0.0,1.0,2.0,0.0,2.0,8051.0,6707.0,124.0,6051.0,5455.0,92.0,2000.0,1252.0,32.0,7.0,1.0,3.0,4.0,3.0,3.0,10664.0,9257.0,176.0,8390.0,8152.0,140.0,2274.0,1105.0,36.0,8.0,3.0,4.0,4.0,6.0,3.0,13164.0,12089.0,232.0,10523.0,10163.0,194.0,2641.0,1926.0,38.0,8.0,3.0,4.0,4.0,6.0,4.0
4,LOLTMNT05_171038,LIT,Winter,2026-01-08 17:08:27,1,16.01,5,Blue,sup,Shredder,GMBLERS Esports,oe:team:eb2f7366b23f654102ef78cfbd9ab56,1.0,Leona,Zyra,Lillia,Wukong,Veigar,Viktor,NaN,NaN,NaN,NaN,NaN,1756,0,1,4,14,22,29,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.7517,1.7426,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9525,325.4556,0.101901,784.7494,833.6446,915.0,47,1.6059,11,0.3759,8.0,119,4.0661,8354,4496,153.6219,0.120924,7985.0,NaN,NaN,26.0,26.0,0,NaN,NaN,0.8884,2839.0,2810.0,13.0,2483.0,2024.0,13.0,356.0,786.0,0.0,0.0,4.0,1.0,0.0,1.0,2.0,4713.0,4670.0,18.0,3872.0,3831.0,18.0,841.0,839.0,0.0,1.0,7.0,3.0,0.0,5.0,3.0,6422.0,6258.0,25.0,5193.0,6034.0,21.0,1229.0,224.0,4.0,1.0,11.0,3.0,0.0,10.0,4.0,7421.0,7596.0,26.0,6285.0,7496.0,23.0,1136.0,100.0,3.0,1.0,12.0,3.0,0.0,11.0,4.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
110347,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,8,Red,mid,Grevthar,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,Lissandra,Naafiri,Jayce,Jax,Renekton,Kennen,NaN,NaN,NaN,NaN,NaN,1685,0,4,4,6,14,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4985,1.5312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,23004,819.1335,0.261951,632.7240,281.2700,4064.0,11,0.3917,6,0.2136,7.0,40,1.4243,10890,7177,255.5608,0.219386,10125.0,NaN,NaN,235.0,235.0,0,NaN,NaN,8.3680,3286.0,4354.0,74.0,4375.0,4894.0,86.0,-1089.0,-540.0,-12.0,1.0,1.0,1.0,3.0,2.0,1.0,5597.0,7522.0,134.0,6991.0,7960.0,142.0,-1394.0,-438.0,-8.0,2.0,1.0,1.0,5.0,2.0,1.0,7727.0,9713.0,164.0,10579.0,11592.0,196.0,-2852.0,-1879.0,-32.0,3.0,2.0,3.0,7.0,5.0,1.0,9968.0,12751.0,211.0,11666.0,12499.0,210.0,-1698.0,252.0,1.0,4.0,6.0,3.0,7.0,6.0,2.0
110348,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,9,Red,bot,Kojima,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,Corki,Naafiri,Jayce,Jax,Renekton,Kennen,NaN,NaN,NaN,NaN,NaN,1685,0,7,5,5,14,29,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4985,1.5312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,31565,1123.9763,0.359437,664.1306,368.1187,2986.0,13,0.4629,8,0.2849,4.0,40,1.4243,15280,11567,411.8813,0.353580,15183.0,NaN,NaN,246.0,242.0,4,NaN,NaN,8.7596,4046.0,3619.0,75.0,3965.0,4004.0,77.0,81.0,-385.0,-2.0,2.0,2.0,2.0,2.0,3.0,1.0,7001.0,6067.0,135.0,6546.0,6520.0,125.0,455.0,-453.0,10.0,3.0,3.0,2.0,2.0,4.0,2.0,9301.0,8505.0,191.0,10206.0,9379.0,165.0,-905.0,-874.0,26.0,3.0,4.0,4.0,5.0,8.0,3.0,14028.0,10696.0,221.0,12645.0,12117.0,225.0,1383.0,-1421.0,-4.0,7.0,5.0,4.0,6.0,8.0,3.0
110349,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,10,Red,sup,Guigs,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,Nautilus,Naafiri,Jayce,Jax,Renekton,Kennen,NaN,NaN,NaN,NaN,NaN,1685,0,0,5,12,14,29,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4985,1.5312,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,7131,253.9228,0.081202,659.8576,1009.0682,0.0,51,1.8160,13,0.4629,17.0,113,4.0237,7164,3451,122.8843,0.105490,6860.0,NaN,NaN,40.0,40.0,0,NaN,NaN,1.4243,2656.0,2449.0,20.0,3349.0,2270.0,11.0,-693.0,179.0,9.0,0.0,4.0,2.0,2.0,5.0,0.0,4067.0,4141.0,31.0,4479.0,3517.0,18.0,-412.0,624.0,13.0,0.0,6.0,2.0,2.0,5.0,1.0,5165.0,5646.0,35.0,6238.0,6054.0,23.0,-1073.0,-408.0,12.0,0.0,7.0,4.0,2.0,13.0,1.0,6549.0,7649.0,39.0,7589.0,7565.0,27.0,-1040.0,84.0,12.0,0.0,12.0,4.0,3.0,13.0,2.0
110350,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,100,Blue,team,NaN,LØS,oe:team:ea65e6cc48a9be50fc5334369a5fca5,0.0,NaN,Cassiopeia,Lulu,Orianna,Galio,LeBlanc,Bard,Jarvan IV,Ezreal,Akali,Camille,1685,1,29,14,70,29,14,4.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,1.0326,1.5312,1.0,3.0,0.0,3.0,0.0,0.0,1.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,9.0,1.0,1.0,1.0,40.0,10.0,1.0,0.0,95963,3417.0801,NaN,4177.3887,3692.0475,42491.0,96,3.4184,49,1.7448,43.0,292,10.3976,62461,43896,1563.0623,NaN,56096.0,0.121554,3.2,NaN,767.0,197,NaN,NaN,34.3264,18893.0,20515.0,348.0,16701.0,19702.0,312.0,2192.0,813.0,36.0,7.0,16.0,4.0,4.0,9.0,7.0,29543.0,33787.0,540.0,26821.0,32036.0,510.0,2722.0,1751.0,30.0,11.0,21.0,7.0,7.0,13.0,11.0,45207.0,50442.0,718.0,35896.0,42874.0,665.0,9311.0,7568.0,53.0,22.0,48.0,9.0,9.0,17.0,22.0,54313.0,59512.0,857.0,47042.0,54590.0,801.0,7271.0,4922.0,56.0,24.0,51.0,14.0,14.0,32.0,24.0
110351,LOLTMNT01_469172,CBLOL,NaN,2026-09-30 22:47:59,3,16.17,200,Red,team,NaN,KaBuM! Ilha das Lendas,oe:team:a36eecb3eab2d2a79f411e462878d26,1.0,NaN,Naafiri,Jayce,Jax,Renekton,Kennen,Nocturne,Corki,Nautilus,Ambessa,Lissandra,1685,0,14,29,32,14,29,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4985,1.5312,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,1.0,9.0,0.0,0.0,10.0,40.0,0.0,1.0,87818,3127.0504,NaN,3988.4154,3434.5282,9469.0,96,3.4184,38,1.3531,42.0,257,9.1513,51279,32714,1164.8902,NaN,49668.0,-0.121554,-3.2,NaN,722.0,155,NaN,NaN,31.2285,16701.0,19702.0,312.0,18893.0,20515.0,348.0,-2192.0,-813.0,-36.0,4.0,9.0,7.0,7.0,16.0,4.0,26821.0,32036.0,510.0,29543.0,33787.0,540.0,-2722.0,-1751.0,-30.0,7.0,13.0,11.0,11.0,21.0,7.0,35896.0,42874.0,665.0,45207.0,50442.0,718.0,-9311.0,-7568.0,-53.0,9.0,17.0,22.0,22.0,48.0,9.0,47042.0,54590.0,801.0,54313.0,59512.0,857.0,-7271.0,-4922.0,-56.0,14.0,32.0,24.0,24.0,51.0,14.0

In [264]:
df.columns.tolist()

['gameid',
 'league',
 'split',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'monsterkillsownjungle',
 'monsterkillsenemyjungle',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [265]:
df = df.drop(columns='split')

In [266]:
df.sample(15)

,gameid,league,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,monsterkillsownjungle,monsterkillsenemyjungle,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
59389,13280-13280_game_1,LPL,2026-05-23 10:55:44,1,16.10,2,Blue,jng,Junhao,ThunderTalk Gaming,oe:team:df80f468a3f9a722df056fe9104f052,0.0,Lee Sin,Karma,Nocturne,Lucian,Caitlyn,Lulu,NaN,NaN,NaN,NaN,NaN,1728,1,3,1,10,15,8,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.5208,0.7986,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8327,289.1319,0.115909,768.8889,1289.4444,6865.0,19,0.6597,9,0.3125,8.0,51,1.7708,12553,8752,303.8889,0.219744,10594.0,NaN,NaN,226.0,15.0,211,NaN,NaN,7.8472,3858.0,3958.0,73.0,3758.0,4931.0,94.0,100.0,-973.0,-21.0,1.0,1.0,0.0,0.0,0.0,0.0,5885.0,7030.0,127.0,5390.0,7124.0,131.0,495.0,-94.0,-4.0,1.0,2.0,0.0,0.0,0.0,0.0,7654.0,9394.0,162.0,7867.0,9731.0,176.0,-213.0,-337.0,-14.0,1.0,4.0,1.0,1.0,0.0,0.0,10231.0,13437.0,199.0,9968.0,11908.0,208.0,263.0,1529.0,-9.0,1.0,8.0,1.0,2.0,0.0,0.0
55396,LOLTMNT02_401875,HM,2026-05-16 16:46:15,1,16.10,5,Blue,sup,Mita,eSuba,oe:team:3faefd9245a4ef6ba347fbcf2a51515,1.0,Rell,Jarvan IV,Lucian,Renekton,Jayce,Bard,NaN,NaN,NaN,NaN,NaN,1878,0,1,8,12,16,28,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5112,1.3738,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5009,160.0319,0.054164,704.9840,1096.7732,0.0,34,1.0863,20,0.6390,6.0,130,4.1534,8270,4163,133.0032,0.118354,7725.0,NaN,NaN,31.0,31.0,0,NaN,NaN,0.9904,2841.0,2412.0,14.0,2681.0,2451.0,18.0,160.0,-39.0,-4.0,1.0,2.0,1.0,1.0,1.0,0.0,4244.0,3538.0,17.0,4440.0,4183.0,25.0,-196.0,-645.0,-8.0,1.0,6.0,4.0,2.0,6.0,1.0,5296.0,4462.0,20.0,5685.0,5391.0,28.0,-389.0,-929.0,-8.0,1.0,6.0,4.0,2.0,6.0,1.0,7018.0,7170.0,30.0,6817.0,6998.0,30.0,201.0,172.0,0.0,1.0,12.0,6.0,2.0,10.0,2.0
33282,LOLTMNT01_361810,LJL,2026-04-11 06:24:25,1,16.07,7,Red,jng,Elative,Uwinks,oe:team:342d21aef61df511e384bea62cc7304,0.0,Graves,Ashe,Rek'Sai,Poppy,LeBlanc,Warwick,NaN,NaN,NaN,NaN,NaN,1284,1,8,0,4,20,1,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.9346,0.9813,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15747,735.8411,0.235885,498.0374,439.7196,8804.0,4,0.1869,1,0.0467,2.0,22,1.0280,11699,8804,411.4019,0.255603,9050.0,NaN,NaN,219.0,25.0,194,NaN,NaN,10.2336,4539.0,3922.0,71.0,2851.0,2812.0,51.0,1688.0,1110.0,20.0,4.0,1.0,0.0,0.0,0.0,4.0,7088.0,7675.0,132.0,3939.0,4228.0,69.0,3149.0,3447.0,63.0,6.0,1.0,0.0,0.0,0.0,6.0,10156.0,12384.0,203.0,4924.0,5162.0,79.0,5232.0,7222.0,124.0,8.0,1.0,0.0,0.0,0.0,8.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
46904,LOLTMNT01_369848,LCP,2026-05-02 11:17:30,1,16.09,9,Red,bot,Artemis,GAM Esports,oe:team:9cae7677cd0dbcc1cd86653870b73c2,1.0,Sivir,Nautilus,Nocturne,Sion,Bard,Pyke,NaN,NaN,NaN,NaN,NaN,2074,0,1,1,4,8,13,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.2314,0.6075,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,15995,462.7290,0.205470,361.6779,277.2035,7877.0,14,0.4050,11,0.3182,5.0,49,1.4176,16437,11930,345.1302,0.298483,15375.0,NaN,NaN,391.0,379.0,12,NaN,NaN,11.3115,3787.0,3934.0,90.0,3666.0,4142.0,103.0,121.0,-208.0,-13.0,1.0,1.0,0.0,0.0,0.0,1.0,6717.0,6724.0,153.0,5818.0,6445.0,154.0,899.0,279.0,-1.0,1.0,1.0,0.0,0.0,0.0,1.0,9374.0,9954.0,215.0,8296.0,8927.0,201.0,1078.0,1027.0,14.0,1.0,4.0,0.0,1.0,1.0,2.0,11856.0,12906.0,275.0,10665.0,11582.0,270.0,1191.0,1324.0,5.0,1.0,4.0,0.0,1.0,2.0,2.0
40132,LOLTMNT05_185230,TCL,2026-04-22 15:39:43,2,16.08,5,Blue,sup,Virgo,Bushido Wildcats,oe:team:105f13a20172b3dbd963c7738617873,1.0,Lulu,Ryze,Nocturne,Nautilus,Sion,Ornn,NaN,NaN,NaN,NaN,NaN,1565,1,0,0,9,11,3,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4217,0.5367,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,2661,102.0192,0.055982,133.5719,61.4185,1462.0,39,1.4952,8,0.3067,10.0,96,3.6805,7371,3903,149.6358,0.102692,6340.0,NaN,NaN,33.0,33.0,0,NaN,NaN,1.2652,2241.0,3075.0,17.0,2371.0,3036.0,28.0,-130.0,39.0,-11.0,0.0,0.0,0.0,0.0,0.0,0.0,3538.0,4566.0,25.0,3502.0,3965.0,33.0,36.0,601.0,-8.0,0.0,2.0,0.0,0.0,1.0,1.0,5135.0,6391.0,29.0,4814.0,5782.0,40.0,321.0,609.0,-11.0,0.0,2.0,0.0,0.0,2.0,1.0,6763.0,9060.0,33.0,5969.0,7383.0,42.0,794.0,1677.0,-9.0,0.0,5.0,0.0,0.0,2.0,1.0
43881,LOLTMNT02_391326,HLL,2026-04-28 13:13:25,1,16.08,10,Red,sup,Abagnale,GOAL,oe:team:007a3c4175ca4f86d9dc49e4f2e9cf8,0.0,Bard,Pantheon,Karma,Orianna,Ryze,Viktor,NaN,NaN,NaN,NaN,NaN,2083,1,0,4,18,23,12,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6625,1.0082,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10360,298.4157,0.081890,621.6323,464.2727,745.0,70,2.0163,21,0.6049,10.0,150,4.3207,9410,4885,140.7105,0.100282,8170.0,NaN,NaN,51.0,47.0,4,NaN,NaN,1.4690,2521.0,3170.0,17.0,2699.0,2671.0,16.0,-178.0,499.0,1.0,0.0,3.0,1.0,1.0,0.0,1.0,3774.0,4834.0,27.0,4095.0,3954.0,22.0,-321.0,880.0,5.0,0.0,5.0,2.0,1.0,3.0,1.0,4946.0,5702.0,31.0,5667.0,5427.0,26.0,-721.0,275.0,5.0,0.0,5.0,3.0,2.0,4.0,1.0,6284.0,8063.0,38.0,6894.0,7445.0,28.0,-610.0,618.0,10.0,0.0,6.0,3.0,2.0,6.0,2.0
64799,LOLTMNT02_417123,PCS,2026-06-03 10:40:41,3,16.10,200,Red,team,NaN,CTBC Flying Oyster Academy,oe:team:2d2d70decb08dfb9bd23327e33e4198,0.0,NaN,Irelia,Orianna,Nocturne,Naafiri,Vi,Yunara,Lulu,Viktor,Wukong,Sion,1949,0,5,16,12,5,16,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.1539,0.6465,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,3.0,9.0,0.0,1.0,18.0,41.0,0.0,1.0,80881,2489.9230,NaN,3562.5962,4349.0303,12669.0,115,3.5403,52,1.6008,47.0,316,9.7281,55064,33806,1040.7183,NaN,54758.0,-0.08381,-1.0,NaN,949.0,213,NaN,NaN,35.7722,16752.0,20118.0,357.0,16769.0,19865.0,356.0,-17.0,253.0,1.0,2.0,4.0,2.0,2.0,2.0,2.0,26215.0,32098.0,547.0,25835.0,31766.0,562.0,380.0,332.0,-15.0,4.0,9.0,4.0,4.0,8.0,4.0,33285.0,42356.0,715.0,35398.0,43074.0,727.0,-2113.0,-718.0,-12.0,4.0,9.0,7.0,7.0,17.0,4.0,42600.0,56950.0,955.0,44380.0,55922.0,953.0,-1780.0,1028.0,2.0,4.0,9.0,7.0,7.0,17.0,4.0
58616,LOLTMNT02_407475,NACL,2026-05-21 22:48:55,4,16.10,9,Red,bot,Mobility,Winthrop University,oe:team:333ba9fefa87eda14bd32c5420d7002,1.0,Jinx,Naafiri,Vi,Nocturne,Twisted Fate,Blitzcrank,NaN,NaN,NaN,NaN,NaN,2118,1,16,2,4,23,13,3.0,2.0,2.0,1.0,0.0,0.0,0.0,1.0,0.6516,1.0198,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,36876,1044.6459,0.321035,446.9688,329.1785,20756.0,16,0.4533,20,0.5666,3.0,69,1.9547,24824,20228,573.0312,0.411421,22075.0,NaN,NaN,380.0,358.0,22,NaN,NaN,10.7649,3892.0,3260.0,80.0,3567.0,3357.0,87.0,325.0,-97.0,-7.0,2.0,0.0,2.0,0.0,2.0,1.0,7032.0,5468.0,132.0,5465.0,5276.0,132.0,1567.0,192.0,0.0,3.0,2.0,2.0,0.0,2.0,1.0,9307.0,8152.0,199.0,7922.0,8427.0,206.0,1385.0,-275.0,-7.0,3.0,2.0,2.0,0.0,2.0,1.0,14377.0,10817.0,240.0,10570.0,10512.0,232.0,3807.0,305.0,8.0,8.0,3.0,2.0,2.0,5.0,2.0
50744,LOLTMNT01_380311,NACL,2026-05-08 22:13:55,1,16.09,9,Red,bot,Bazz,Apex Mission Impossible,oe:team:fa12fb801e77d60b9fde291b93c5d3f,0.0,Varus,Orianna,Karma,Neeko,Jax,Nautilus,NaN,NaN,NaN,NaN,NaN,2012,0,1,3,1,5,18,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1491,0.6859,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,23869,711.7992,0.312323,507.4056,258.5189,2077.0,18,0.5368,5,0.1491,6.0,40,1.1928,11897,7517,224.1650,0.228529,11400.0,NaN,NaN,297.0,297.0,0,NaN,NaN,8.8569,3383.0,3778.0,96.0,3533.0,3613.0,99.0,-150.0,165.0,-3.0,0.0,0.0,0.0,0.0,0.0,0.0,5299.0,5937.0,147.0,5638.0,5848.0,148.0,-339.0,89.0,-1.0,0.0,0.0,0.0,0.0,0.0,0.0,7763.0,8811.0,204.0,8993.0,8530.0,195.0,-1230.0,281.0,9.0,1.0,1.0,0.0,3.0,1.0,1.0,9589.0,11402.0,251.0,11325.0,11049.0,258.0,-1736.0,353.0,-7.0,1.0,1.0,1.0,3.0,2.0,1.0
50888,LOLTMNT01_380576,LAS,2026-05-09 09:42:33,2,16.09,9,Red,bot,Revenge,DN SOOPers Academy,oe:team:00ae39840233a9dc8db235166c32ba7,0.0,Sivir,Orianna,Pantheon,Nautilus,Galio,Annie,NaN,NaN,NaN,NaN,NaN,1686,1,2,1,13,26,7,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.9253,1.1744,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,25222,897.5801,0.252447,746.7616,504.6619,8483.0,13,0.4626,4,0.1423,4.0,33,1.1744,13609,9894,352.0996,0.229049,11200.0,NaN,NaN,285.0,269.0,16,NaN,NaN,10.1423,3468.0,3880.0,85.0,3733.0,3901.0,90.0,-265.0,-21.0,-5.0,0.0,2.0,1.0,1.0,0.0,0.0,5638.0,6476.0,137.0,6282.0,6823.0,152.0,-644.0,-347.0,-15.0,0.0,2.0,1.0,1.0,0.0,1.0,8050.0,9389.0,200.0,8207.0,9085.0,198.0,-157.0,304.0,2.0,0.0,4.0,1.0,1.0,0.0,2.0,11127.0,12948.0,250.0,9905.0,11062.0,239.0,1222.0,1886.0,11.0,1.0,10.0,1.0,1.0,1.0,4.0
94892,LOLTMNT02_458934,HM,2026-08-27 17:02:11,2,16.16,9,Red,bot,Nephix,Bohemian Guardians,oe:team:ab34660aa4f67f0fd1e8f6680b4bcc4,0.0,Yunara,Syndra,Ezreal,Orianna,Wukong,Skarner,NaN,NaN,NaN,NaN,NaN,1850,1,18,3,10,31,4,4.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0054,1.1351,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,45393,1472.2054,0.411377,672.7135,483.1784,13091.0,9,0.2919,18,0.5838,4.0,49,1.5892,19286,15236,494.1405,0.326786,17300.0,NaN,NaN,283.0,263.0,20,NaN,NaN,9.1784,3868.0,3024.0,76.0,3198.0,3024.0,77.0,670.0,0.0,-1.0,1.0,4.0,1.0,0.0,1.0,3.0,7076.0,5611.0,135.0,5098.0,4920.0,117.0,1978.0,691.0,18.0,4.0,5.0,2.0,0.0,2.0,5.0,10259.0,8067.0,185.0,6726.0,6648.0,160.0,3533.0,1419.0,25.0,7.0,8.0,2.0,0.0,2.0,8.0,13225.0,11016.0,224.0,8570.0,8107.0,192.0,4655.0,2909.0,32.0,9.0,10.0,3.0,0.0,3.0,10.0
37623,LOLTMNT02_378587,LJL,2026-04-18 04:10:48,1,16.08,4,Blue,bot,Sunleaf,NOVEX,oe:team:712397f5e921b372b59b907a485387e,1.0,Sivir,Elise,Viktor,Caitlyn,Azir,Illaoi,NaN,NaN,NaN,NaN,NaN,1637,0,1,3,1,3,20,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.1100,0.8430,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,9591,351.5333,0.203290,452.7306,242.3458,376.0,6,0.2199,3,0.1100,1.0,13,0.4765,10060,6445,236.2248,0.266147,9300.0,NaN,NaN,224.0,224.0,0,NaN,NaN,8.2101,3045.0,2931.0,59.0,3393.0,3787.0,85.0,-348.0,-856.0,-26.0,1.0,0.0,0.0,0.0,0.0,1.0,5123.0,5831.0,115.0,5710.0,6359.0,137.0,-587.0,-528.0,-22.0,1.0,0.0,0.0,0.0,0.0,1.0,7294.0,7672.0,157.0,9005.0,9625.0,195.0,-1711.0,-1953.0,-38.0,1.0,1.0,2.0,1.0,6.0,1.0,9622.0,10320.0,218.0,11780.0,13238.0,251.0,-2158.0,-2918.0,-33.0,1.0,1.0,3.0,2.0,8.0,1.0
61705,LOLTMNT05_196372,PRM,2026-05-27 17:03:57,3,16.10,2,Blue,jng,Markoon,G2 NORD,oe:team:1f1ed22b8cadc3bd717b2fbf0b63e62,1.0,Jarvan IV,Corki,Aurora,Bard,Jayce,LeBlanc,NaN,NaN,NaN,NaN,NaN,1829,1,4,0,14,21,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6889,0.8857,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10709,351.3067,0.141723,451.0990,1524.7020,2720.0,10,0.3280,5,0.1640,7.0,42,1.3778,13162,9155,300.3280,0.219765,11025.0,NaN,NaN,215.0,20.0,195,NaN,NaN,7.0530,3765.0,4197.0,74.0,3421.0,4005.0,79.0,344.0,192.0,-5.0,1.0,1.0,0.0,0.0,0.0,0.0,5653.0,6402.0,106.0,5111.0,6066.0,114.0,542.0,336.0,-8.0,2.0,2.0,0.0,1.0,0.0,0.0,7970.0,9477.0,151.0,6856.0,8338.0,151.0,1114.0,1139.0,0.0,2.0,7.0,0.0,1.0,0.0,1.0,10644.0,12613.0,190.0,8202.0,10251.0,177.0,2442.0,2362.0,13.0,3.0,9.0,0.0,1.0,0.0,2.0
109587,LOLTMNT01_466956,CBLOL,2026-09-28 21:04:54,1,16.17,4,Blue,bot,Scenari0,Golden Lions,oe:team:dbea9378f0ff4aec096cd27745d47da,0.0,Yunara,Karma,Cassiopeia,Ryze,Seraphine,Nautilus,NaN,NaN,NaN,NaN,NaN,1493,0,3,7,2,10,21,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4019,1.2458,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,13689,550.1273,0.222912,674.5881,398.0576,5806.0,13,0.5224,5,0.2009,5.0,33,1.3262,10564,7243,291.0784,0.272154,9550.0,NaN,NaN,225.0,217.0,8,NaN,NaN,9.0422,3748.0,3271.0,82.0,4226.0,3610.0,85.0,-478.0,-339.0,-3.0,1.0,1.0,3.0,2.0,3.0,1.0,6439.0,5582.0,128.0,6977.0,5786.0,132.0,-538.0,-204.0,-4.0,2.0,1.0,4.0,4.0,5.0,1.0,8423.0,7885.0,176.0,9340.0,7719.0,179.0,-917.0,166.0,-3.0,2.0,2.0,6.0,5.0,5.0,1.0,10564.0,10359.0,225.0,13209.0,10188.0,231.0,-2645.0,171.0,-6.0,3.0,2.0,7.0,9.0,7.0,1.0
15507,LOLTMNT02_355321,HW,2026-02-18 17:00:41,2,16.03,4,Blue,bot,KNEZA,EXILE esports,oe:team:dba2e551039e079ceae513ba7386109,1.0,Jinx,Naafiri,Akali,Ambessa,Diana,Sylas,NaN,NaN,NaN,NaN,NaN,1983,0,3,7,4,15,26,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4539,1.2405,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,23539,712.2239,0.294079,674.6747,417.5794,3264.0,11,0.3328,9,0.2723,4.0,41,1.2405,14692,10371,313.7973,0.248562,14650.0,NaN,NaN,311.0,291.0,20,NaN,NaN,9.4100,4298.0,3704.0,85.0,3327.0,3818.0,85.0,971.0,-114.0,0.0,3.0,0.0,0.0,0.0,0.0,1.0,6159.0,5307.0,115.0,6703.0,6136.0,138.0,-544.0,-829.0,-23.0,3.0,1.0,2.0,2.0,1.0,1.0,8811.0,8001.0,185.0,9967.0,9228.0,199.0,-1156.0,-1227.0,-14.0,3.0,1.0,3.0,3.0,3.0,1.0,11011.0,10270.0,232.0,14036.0,12799.0,271.0,-3025.0,-2529.0,-39.0,3.0,3.0,4.0,6.0,4.0,1.0

In [267]:
df['monsterkillsownjungle'].unique()

array([ nan,   0., 142.,   3.,   7., 133.,   4.,   1., 151., 140.,  23.,
       171., 182.,  20., 198., 202., 206., 147.,  27., 207., 177., 117.,
        12., 115.,  10., 129., 124., 157., 158., 176., 169., 183.,  17.,
       178., 199., 197., 138.,  16., 109., 139., 125., 148.,   9., 155.,
       156., 159., 128.,   6., 132., 134., 152.])

In [268]:
df['monsterkillsenemyjungle'].unique()

array([nan,  1., 19.,  0., 20.,  4.,  3., 33.,  7., 41., 17.,  8., 12.,
        5., 25., 38.,  2., 26., 40.,  6., 14., 18., 24., 10.])

In [269]:
df['monsterkillsownjungle'].isnull().all()

np.False_

In [270]:
df['monsterkillsenemyjungle'].isnull().all()

np.False_

In [271]:
df = df.drop(columns=['monsterkillsenemyjungle', 'monsterkillsownjungle'])

In [272]:
df.columns.tolist()

['gameid',
 'league',
 'date',
 'game',
 'patch',
 'participantid',
 'side',
 'position',
 'playername',
 'teamname',
 'teamid',
 'firstPick',
 'champion',
 'ban1',
 'ban2',
 'ban3',
 'ban4',
 'ban5',
 'pick1',
 'pick2',
 'pick3',
 'pick4',
 'pick5',
 'gamelength',
 'result',
 'kills',
 'deaths',
 'assists',
 'teamkills',
 'teamdeaths',
 'doublekills',
 'triplekills',
 'quadrakills',
 'pentakills',
 'firstblood',
 'firstbloodkill',
 'firstbloodassist',
 'firstbloodvictim',
 'team kpm',
 'ckpm',
 'firstdragon',
 'dragons',
 'opp_dragons',
 'elementaldrakes',
 'opp_elementaldrakes',
 'infernals',
 'mountains',
 'clouds',
 'oceans',
 'chemtechs',
 'hextechs',
 'elders',
 'opp_elders',
 'firstherald',
 'heralds',
 'opp_heralds',
 'void_grubs',
 'opp_void_grubs',
 'firstbaron',
 'barons',
 'opp_barons',
 'opp_atakhans',
 'firsttower',
 'towers',
 'opp_towers',
 'firstmidtower',
 'firsttothreetowers',
 'turretplates',
 'opp_turretplates',
 'inhibitors',
 'opp_inhibitors',
 'damagetochampions',
 'dpm',
 'damageshare',
 'damagetakenperminute',
 'damagemitigatedperminute',
 'damagetotowers',
 'wardsplaced',
 'wpm',
 'wardskilled',
 'wcpm',
 'controlwardsbought',
 'visionscore',
 'vspm',
 'totalgold',
 'earnedgold',
 'earned gpm',
 'earnedgoldshare',
 'goldspent',
 'gspd',
 'gpr',
 'total cs',
 'minionkills',
 'monsterkills',
 'cspm',
 'goldat10',
 'xpat10',
 'csat10',
 'opp_goldat10',
 'opp_xpat10',
 'opp_csat10',
 'golddiffat10',
 'xpdiffat10',
 'csdiffat10',
 'killsat10',
 'assistsat10',
 'deathsat10',
 'opp_killsat10',
 'opp_assistsat10',
 'opp_deathsat10',
 'goldat15',
 'xpat15',
 'csat15',
 'opp_goldat15',
 'opp_xpat15',
 'opp_csat15',
 'golddiffat15',
 'xpdiffat15',
 'csdiffat15',
 'killsat15',
 'assistsat15',
 'deathsat15',
 'opp_killsat15',
 'opp_assistsat15',
 'opp_deathsat15',
 'goldat20',
 'xpat20',
 'csat20',
 'opp_goldat20',
 'opp_xpat20',
 'opp_csat20',
 'golddiffat20',
 'xpdiffat20',
 'csdiffat20',
 'killsat20',
 'assistsat20',
 'deathsat20',
 'opp_killsat20',
 'opp_assistsat20',
 'opp_deathsat20',
 'goldat25',
 'xpat25',
 'csat25',
 'opp_goldat25',
 'opp_xpat25',
 'opp_csat25',
 'golddiffat25',
 'xpdiffat25',
 'csdiffat25',
 'killsat25',
 'assistsat25',
 'deathsat25',
 'opp_killsat25',
 'opp_assistsat25',
 'opp_deathsat25']

In [273]:
df[df['game'] == 5]

,gameid,league,date,game,patch,participantid,side,position,playername,teamname,teamid,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
5628,LOLTMNT01_326904,LCK,2026-01-28 11:49:42,5,16.02,1,Blue,top,Rich,Kiwoom DRX,oe:team:1d0389df0c5eea93b04122ba167c010,0.0,K'Sante,Rumble,Jayce,Varus,Miss Fortune,Caitlyn,NaN,NaN,NaN,NaN,NaN,2586,1,1,0,12,20,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4640,0.6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,28046,650.7193,0.220967,954.2227,2255.6381,9270.0,29,0.6729,17,0.3944,5.0,91,2.1114,15761,10210,236.8910,0.190293,13875.0,NaN,NaN,350.0,346.0,4,8.1206,3559.0,4945.0,93.0,3401.0,5026.0,89.0,158.0,-81.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,5136.0,8445.0,140.0,5469.0,8556.0,147.0,-333.0,-111.0,-7.0,0.0,0.0,0.0,0.0,0.0,0.0,6895.0,11526.0,192.0,7294.0,11890.0,200.0,-399.0,-364.0,-8.0,0.0,0.0,0.0,0.0,0.0,0.0,9346.0,15718.0,244.0,8814.0,15073.0,248.0,532.0,645.0,-4.0,1.0,0.0,0.0,0.0,1.0,1.0
5629,LOLTMNT01_326904,LCK,2026-01-28 11:49:42,5,16.02,2,Blue,jng,Willer,Kiwoom DRX,oe:team:1d0389df0c5eea93b04122ba167c010,0.0,Aatrox,Rumble,Jayce,Varus,Miss Fortune,Caitlyn,NaN,NaN,NaN,NaN,NaN,2586,1,4,2,13,20,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.4640,0.6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,22184,514.7100,0.174782,1097.0766,1061.9258,3429.0,14,0.3248,21,0.4872,12.0,89,2.0650,16434,10883,252.5058,0.202837,14575.0,NaN,NaN,293.0,26.0,267,6.7981,3647.0,4455.0,85.0,4030.0,4268.0,85.0,-383.0,187.0,0.0,0.0,1.0,1.0,1.0,0.0,0.0,5417.0,6987.0,127.0,6283.0,7568.0,139.0,-866.0,-581.0,-12.0,0.0,2.0,2.0,2.0,0.0,0.0,6973.0,8889.0,158.0,8111.0,9924.0,185.0,-1138.0,-1035.0,-27.0,0.0,2.0,2.0,2.0,0.0,0.0,8757.0,11646.0,196.0,9871.0,12618.0,228.0,-1114.0,-972.0,-32.0,0.0,2.0,2.0,2.0,0.0,0.0
5630,LOLTMNT01_326904,LCK,2026-01-28 11:49:42,5,16.02,3,Blue,mid,Ucal,Kiwoom DRX,oe:team:1d0389df0c5eea93b04122ba167c010,0.0,Syndra,Rumble,Jayce,Varus,Miss Fortune,Caitlyn,NaN,NaN,NaN,NaN,NaN,2586,1,7,2,9,20,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4640,0.6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,26567,616.4037,0.209314,294.7332,127.4014,7067.0,19,0.4408,11,0.2552,2.0,69,1.6009,16522,10971,254.5476,0.204477,15050.0,NaN,NaN,345.0,345.0,0,8.0046,3685.0,4844.0,92.0,3380.0,4826.0,89.0,305.0,18.0,3.0,1.0,0.0,0.0,0.0,1.0,0.0,5661.0,7370.0,147.0,5878.0,7995.0,152.0,-217.0,-625.0,-5.0,1.0,0.0,0.0,1.0,2.0,0.0,7555.0,10399.0,209.0,7655.0,10950.0,207.0,-100.0,-551.0,2.0,1.0,0.0,0.0,1.0,2.0,0.0,9067.0,12577.0,247.0,9362.0,12965.0,249.0,-295.0,-388.0,-2.0,1.0,0.0,0.0,2.0,2.0,0.0
5631,LOLTMNT01_326904,LCK,2026-01-28 11:49:42,5,16.02,4,Blue,bot,Jiwoo,Kiwoom DRX,oe:team:1d0389df0c5eea93b04122ba167c010,0.0,Jhin,Rumble,Jayce,Varus,Miss Fortune,Caitlyn,NaN,NaN,NaN,NaN,NaN,2586,1,8,0,9,20,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4640,0.6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,42171,978.4455,0.332254,372.6914,261.4849,11200.0,20,0.4640,20,0.4640,9.0,62,1.4385,21824,16273,377.5638,0.303296,18975.0,NaN,NaN,409.0,392.0,17,9.4896,3314.0,3155.0,84.0,3394.0,3589.0,86.0,-80.0,-434.0,-2.0,0.0,1.0,0.0,0.0,1.0,0.0,5689.0,5524.0,132.0,5808.0,5515.0,129.0,-119.0,9.0,3.0,1.0,1.0,0.0,0.0,2.0,1.0,7618.0,8214.0,192.0,7848.0,8648.0,192.0,-230.0,-434.0,0.0,1.0,1.0,0.0,0.0,2.0,1.0,10103.0,10344.0,250.0,10422.0,11239.0,262.0,-319.0,-895.0,-12.0,1.0,1.0,0.0,0.0,3.0,1.0
5632,LOLTMNT01_326904,LCK,2026-01-28 11:49:42,5,16.02,5,Blue,sup,Andil,Kiwoom DRX,oe:team:1d0389df0c5eea93b04122ba167c010,0.0,Nautilus,Rumble,Jayce,Varus,Miss Fortune,Caitlyn,NaN,NaN,NaN,NaN,NaN,2586,1,0,2,17,20,6,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4640,0.6032,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,7956,184.5940,0.062683,480.7193,810.3944,0.0,79,1.8329,14,0.3248,17.0,159,3.6891,10868,5317,123.3643,0.099098,9340.0,NaN,NaN,32.0,32.0,0,0.7425,2317.0,2698.0,12.0,2317.0,2406.0,17.0,0.0,292.0,-5.0,0.0,1.0,0.0,0.0,1.0,1.0,3564.0,3784.0,22.0,3657.0,3417.0,24.0,-93.0,367.0,-2.0,0.0,2.0,1.0,0.0,3.0,1.0,4626.0,4216.0,26.0,4944.0,4241.0,35.0,-318.0,-25.0,-9.0,0.0,2.0,1.0,0.0,3.0,1.0,5858.0,5520.0,27.0,5995.0,6068.0,38.0,-137.0,-548.0,-11.0,0.0,2.0,2.0,0.0,4.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
109207,LOLTMNT01_468525,CBLOL,2026-09-27 19:49:11,5,16.17,8,Red,mid,Feisty,LØS,oe:team:ea65e6cc48a9be50fc5334369a5fca5,0.0,Twisted Fate,Cassiopeia,Olaf,Qiyana,Kai'Sa,Rakan,NaN,NaN,NaN,NaN,NaN,1883,1,3,0,11,19,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6054,0.6691,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,17709,564.2804,0.231836,492.3951,281.1046,4037.0,8,0.2549,8,0.2549,5.0,35,1.1152,14025,9908,315.7090,0.207998,11685.0,NaN,NaN,277.0,277.0,0,8.8263,3669.0,5100.0,90.0,3744.0,5248.0,107.0,-75.0,-148.0,-17.0,0.0,0.0,0.0,0.0,0.0,0.0,5589.0,7960.0,147.0,5468.0,7878.0,161.0,121.0,82.0,-14.0,0.0,0.0,0.0,0.0,0.0,0.0,7979.0,11205.0,194.0,6894.0,9883.0,199.0,1085.0,1322.0,-5.0,0.0,2.0,0.0,0.0,0.0,1.0,10708.0,15931.0,242.0,8791.0,12122.0,245.0,1917.0,3809.0,-3.0,2.0,4.0,0.0,0.0,0.0,2.0
109208,LOLTMNT01_468525,CBLOL,2026-09-27 19:49:11,5,16.17,9,Red,bot,Duduhh,LØS,oe:team:ea65e6cc48a9be50fc5334369a5fca5,0.0,Corki,Cassiopeia,Olaf,Qiyana,Kai'Sa,Rakan,NaN,NaN,NaN,NaN,NaN,1883,1,6,1,5,19,2,2.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6054,0.6691,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19085,608.1253,0.249849,498.4811,291.4923,17284.0,16,0.5098,7,0.2230,8.0,42,1.3383,17071,12954,412.7669,0.271942,17483.0,NaN,NaN,311.0,311.0,0,9.9097,3564.0,3735.0,92.0,4026.0,3624.0,107.0,-462.0,111.0,-15.0,0.0,0.0,0.0,0.0,0.0,0.0,6180.0,6443.0,156.0,6464.0,5752.0,172.0,-284.0,691.0,-16.0,0.0,0.0,0.0,0.0,0.0,0.0,8674.0,8969.0,207.0,9009.0,8288.0,240.0,-335.0,681.0,-33.0,1.0,0.0,0.0,0.0,0.0,0.0,11143.0,11948.0,270.0,11474.0,10414.0,304.0,-331.0,1534.0,-34.0,1.0,2.0,0.0,0.0,0.0,1.0
109209,LOLTMNT01_468525,CBLOL,2026-09-27 19:49:11,5,16.17,10,Red,sup,Ackerman,LØS,oe:team:ea65e6cc48a9be50fc5334369a5fca5,0.0,Poppy,Cassiopeia,Olaf,Qiyana,Kai'Sa,Rakan,NaN,NaN,NaN,NaN,NaN,1883,1,0,1,16,19,2,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6054,0.6691,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,5484,174.7424,0.071793,388.2315,484.7796,1665.0,57,1.8163,8,0.2549,23.0,117,3.7281,8815,4698,149.6973,0.098626,7440.0,NaN,NaN,38.0,38.0,0,1.2108,2419.0,2818.0,19.0,2431.0,3111.0,23.0,-12.0,-293.0,-4.0,0.0,0.0,0.0,0.0,0.0,0.0,3550.0,4030.0,30.0,3672.0,4566.0,33.0,-122.0,-536.0,-3.0,0.0,0.0,0.0,0.0,0.0,0.0,5112.0,5995.0,32.0,4674.0,5784.0,35.0,438.0,211.0,-3.0,0.0,4.0,0.0,0.0,0.0,1.0,6484.0,7832.0,35.0,5743.0,8043.0,37.0,741.0,-211.0,-2.0,0.0,7.0,0.0,0.0,0.0,2.0
109210,LOLTMNT01_468525,CBLOL,2026-09-27 19:49:11,5,16.17,100,Blue,team,NaN,LOUD,oe:team:658a021a796aa5501503220adb38cf4,1.0,NaN,Caitlyn,Renekton,Viktor,Shen,Alistar,Naafiri,LeBlanc,Camille,Thresh,Jinx,1883,0,2,19,5,2,19,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.0637,0.6691,1.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,9.0,1.0,0.0,17.0,39.0,0.0,2.0,49413,1574.4981,NaN,3113.3404,2241.5082,19888.0,97,3.0908,45,1.4339,51.0,274,8.7307,53444,32859,1047.0207,NaN,50953.0,-0.191729,-2.33,NaN,941.0,230,37.3128,16716.0,20704.0,390.0,17084.0,21038.0,367.0,-368.0,-334.0,23.0,0.0,0.0,1.0,1.0,1.0,0.0,25061.0,32109.0,593.0,26435.0,34325.0,587.0,-1374.0,-2216.0,6.0,0.0,0.0,2.0,2.0,1.0,0.0,33610.0,43384.0,793.0,37784.0,48759.0,791.0,-4174.0,-5375.0,2.0,0.0,0.0,6.0,6.0,8.0,0.0,42535.0,54803.0,989.0,48820.0,64354.0,998.0,-6285.0,-9551.0,-9.0,0.0,0.0,10.0,10.0,17.0,0.0
109211,LOLTMNT01_468525,CBLOL,2026-09-27 19:49:11,5,16.17,200,Red,team,NaN,LØS,oe:team:ea65e6cc48a9be50fc5334369a5fca5,0.0,NaN,Cassiopeia,Olaf,Qiyana,Kai'Sa,Rakan,Pantheon,Twisted Fate,Kennen,Poppy,Corki,1883,1,19,2,44,19,2,3.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,0.6054,0.6691,0.0,2.0,2.0,2.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,1.0,1.0,0.0,0.0,1.0,9.0,3.0,0.0,1.0,39.0,17.0,2.0,0.0,76386,2433.9671,NaN,2621.5189,2032.8943,39078.0,99,3.1545,39,1.2427,47.0,292,9.3043,68220,47635,1517.8439,NaN,61758.0,0.191729,2.33,NaN,957.0,229,37.7908,17084.0,21038.0,367.0,16716.0,20704.0,390.0,368.0,334.0,-23.0,1.0,1.0,0.0,0.0,0.0,1.0,26435.0,34325.0,587.0,25061.0,32109.0,593.0,1374.0,2216.0,-6.0,2.0,1.0,0.0,0.0,0.0,2.0,37784.0,48759.0,791.0,33610.0,43384.0,793.0,4174.0,5375.0,-2.0,6.0,8.0,0.0,0.0,0.0,6.0,48820.0,64354.0,998.0,42535.0,54803.0,989.0,6285.0,9551.0,9.0,10.0,17.0,0.0,0.0,0.0,10.0

In [274]:
df.groupby('teamid')['teamname'].nunique().value_counts()

teamname
1    354
Name: count, dtype: int64

In [275]:
df = df.drop(columns='teamid')

In [276]:
df[df['game'] == 5].sample(15)

,gameid,league,date,game,patch,participantid,side,position,playername,teamname,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
100733,LOLTMNT04_189435,RL,2026-09-08 19:17:59,5,16.17,6,Red,top,frajgo,Bomba Team,0.0,Twisted Fate,Nocturne,Viktor,Lulu,Kai'Sa,Kalista,NaN,NaN,NaN,NaN,NaN,1707,0,1,3,3,10,16,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3515,0.9139,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12650,444.6397,0.192159,548.4007,277.8207,6057.0,11,0.3866,3,0.1054,2.0,29,1.0193,10596,6838,240.3515,0.212922,10250.0,NaN,NaN,232.0,224.0,8,8.1547,3903.0,4981.0,88.0,3319.0,5317.0,90.0,584.0,-336.0,-2.0,0.0,1.0,0.0,0.0,0.0,0.0,5767.0,8530.0,138.0,5399.0,9139.0,151.0,368.0,-609.0,-13.0,0.0,1.0,1.0,0.0,0.0,0.0,7549.0,11388.0,179.0,7676.0,12667.0,218.0,-127.0,-1279.0,-39.0,0.0,3.0,1.0,0.0,0.0,1.0,9822.0,14128.0,221.0,9780.0,15633.0,265.0,42.0,-1505.0,-44.0,1.0,3.0,2.0,1.0,1.0,1.0
26334,LOLTMNT01_352758,VCS,2026-03-25 13:39:10,5,16.05,7,Red,jng,tiphat,Saigon Warriors,0.0,Zyra,Rumble,Akali,Ashe,Lee Sin,Nidalee,NaN,NaN,NaN,NaN,NaN,2040,1,10,3,7,28,10,1.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,0.8235,1.1176,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,20966,616.6471,0.209338,577.4118,299.1471,5171.0,13,0.3824,14,0.4118,11.0,60,1.7647,17139,12702,373.5882,0.240105,15325.0,NaN,NaN,293.0,47.0,246,8.6176,4281.0,4129.0,73.0,3898.0,4318.0,87.0,383.0,-189.0,-14.0,3.0,0.0,0.0,0.0,0.0,0.0,6543.0,7287.0,129.0,6195.0,6628.0,114.0,348.0,659.0,15.0,4.0,0.0,1.0,2.0,0.0,1.0,9312.0,10203.0,164.0,8747.0,10523.0,178.0,565.0,-320.0,-14.0,6.0,2.0,2.0,2.0,1.0,2.0,11497.0,13737.0,217.0,11565.0,13364.0,215.0,-68.0,373.0,2.0,6.0,2.0,2.0,3.0,1.0,2.0
57659,LOLTMNT02_405860,CD,2026-05-20 23:34:27,5,16.10,200,Red,team,NaN,Vivo Keyd Stars Academy,0.0,NaN,Ezreal,Caitlyn,Kalista,Karma,Miss Fortune,Annie,Aatrox,Jax,Xayah,Rakan,2056,1,18,3,49,18,3,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.5253,0.6128,1.0,4.0,1.0,4.0,1.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,1.0,2.0,0.0,0.0,1.0,10.0,1.0,1.0,1.0,41.0,13.0,2.0,0.0,80391,2346.0409,NaN,2821.2257,3397.5875,41599.0,137,3.9981,76,2.2179,39.0,421,12.2860,70414,48065,1402.6751,NaN,62073.0,0.128102,2.34,NaN,966.0,264,35.8949,16784.0,20384.0,351.0,15937.0,19575.0,342.0,847.0,809.0,9.0,3.0,5.0,1.0,1.0,1.0,3.0,27460.0,32301.0,557.0,24422.0,31244.0,542.0,3038.0,1057.0,15.0,5.0,11.0,1.0,1.0,1.0,5.0,36688.0,44480.0,785.0,34772.0,44912.0,758.0,1916.0,-432.0,27.0,5.0,11.0,3.0,3.0,5.0,5.0,48412.0,61086.0,961.0,42651.0,54868.0,938.0,5761.0,6218.0,23.0,10.0,25.0,3.0,3.0,5.0,10.0
25057,LOLTMNT01_350498,FST,2026-03-17 19:04:16,5,16.05,2,Blue,jng,Inspired,LYON,1.0,Xin Zhao,Vi,Nautilus,Karma,Trundle,Malphite,NaN,NaN,NaN,NaN,NaN,2032,1,2,0,8,15,5,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.4429,0.5906,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,13665,403.4941,0.153321,1059.4783,962.5394,8527.0,8,0.2362,16,0.4724,5.0,61,1.8012,14695,10274,303.3661,0.208169,12425.0,NaN,NaN,291.0,28.0,263,8.5925,3771.0,4580.0,86.0,3536.0,3999.0,82.0,235.0,581.0,4.0,0.0,1.0,0.0,0.0,0.0,0.0,5814.0,7358.0,130.0,5435.0,6458.0,123.0,379.0,900.0,7.0,1.0,1.0,0.0,0.0,1.0,0.0,7949.0,10331.0,179.0,7070.0,8717.0,159.0,879.0,1614.0,20.0,1.0,1.0,0.0,0.0,1.0,0.0,10722.0,14317.0,233.0,8840.0,11224.0,194.0,1882.0,3093.0,39.0,2.0,3.0,0.0,0.0,1.0,1.0
50695,LOLTMNT04_161380,AL,2026-05-08 20:14:54,5,16.09,8,Red,mid,Improver,BAAM Esports,0.0,Akali,Rell,Lee Sin,Anivia,Lissandra,LeBlanc,NaN,NaN,NaN,NaN,NaN,1528,1,4,4,2,11,4,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.4319,0.5890,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,14331,562.7356,0.227715,794.4503,497.5916,118.0,3,0.1178,2,0.0785,2.0,16,0.6283,9369,5976,234.6597,0.169885,8900.0,NaN,NaN,207.0,207.0,0,8.1283,3693.0,5035.0,89.0,3348.0,4604.0,88.0,345.0,431.0,1.0,1.0,0.0,1.0,0.0,1.0,1.0,4853.0,6755.0,118.0,5214.0,7475.0,132.0,-361.0,-720.0,-14.0,1.0,0.0,3.0,1.0,2.0,1.0,7129.0,9611.0,161.0,6520.0,8997.0,163.0,609.0,614.0,-2.0,3.0,2.0,3.0,1.0,2.0,2.0,8687.0,12509.0,207.0,8201.0,12664.0,210.0,486.0,-155.0,-3.0,3.0,2.0,3.0,1.0,2.0,2.0
101154,LOLTMNT04_189520,EBL,2026-09-09 19:13:32,5,16.17,7,Red,jng,Renewal,Only The Family,0.0,Aatrox,Rumble,Jayce,Syndra,Dr. Mundo,Ornn,NaN,NaN,NaN,NaN,NaN,1667,1,14,2,8,31,16,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.1158,1.6917,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,23248,836.7606,0.246954,1239.4481,1065.9988,5613.0,6,0.2160,3,0.1080,2.0,26,0.9358,14688,11012,396.3527,0.240885,12950.0,NaN,NaN,222.0,4.0,218,7.9904,4495.0,4654.0,85.0,3797.0,3382.0,58.0,698.0,1272.0,27.0,3.0,0.0,1.0,3.0,1.0,2.0,7249.0,8051.0,137.0,5657.0,5612.0,95.0,1592.0,2439.0,42.0,5.0,1.0,1.0,4.0,1.0,3.0,11083.0,12488.0,176.0,7830.0,7244.0,108.0,3253.0,5244.0,68.0,11.0,6.0,1.0,5.0,2.0,6.0,12759.0,15312.0,209.0,9404.0,9790.0,131.0,3355.0,5522.0,78.0,11.0,6.0,2.0,5.0,6.0,6.0
101586,LOLTMNT01_458393,LPLOL,2026-09-10 21:46:43,5,16.17,7,Red,jng,Anechek,Dominion Goblins,0.0,Sejuani,Syndra,Orianna,Skarner,Shen,Hwei,NaN,NaN,NaN,NaN,NaN,1381,0,2,6,1,5,24,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.2172,1.2600,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,12472,541.8682,0.222619,1463.7654,1038.2476,0.0,10,0.4345,3,0.1303,10.0,23,0.9993,7458,4365,189.6452,0.207966,7225.0,NaN,NaN,141.0,13.0,128,6.1260,4047.0,4269.0,67.0,3777.0,3973.0,76.0,270.0,296.0,-9.0,2.0,1.0,0.0,1.0,0.0,0.0,5465.0,6391.0,101.0,5818.0,6248.0,108.0,-353.0,143.0,-7.0,2.0,1.0,1.0,3.0,0.0,0.0,6779.0,8238.0,128.0,10151.0,10561.0,155.0,-3372.0,-2323.0,-27.0,2.0,1.0,4.0,7.0,3.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
108457,LOLTMNT01_468439,CBLOL,2026-09-26 19:53:47,5,16.17,2,Blue,jng,Tatu,FURIA,0.0,Xin Zhao,Jarvan IV,Bard,Lee Sin,Jayce,Kennen,NaN,NaN,NaN,NaN,NaN,2072,1,1,2,10,20,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5792,0.8687,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10231,296.2645,0.128571,1135.9170,900.0869,4100.0,15,0.4344,27,0.7819,13.0,106,3.0695,13727,9225,267.1332,0.196653,11125.0,NaN,NaN,277.0,50.0,227,8.0212,3868.0,4192.0,75.0,3529.0,4188.0,82.0,339.0,4.0,-7.0,1.0,2.0,0.0,0.0,0.0,0.0,5521.0,6223.0,113.0,5126.0,6334.0,117.0,395.0,-111.0,-4.0,1.0,2.0,1.0,0.0,1.0,0.0,7381.0,9046.0,157.0,7314.0,8854.0,162.0,67.0,192.0,-5.0,1.0,4.0,2.0,0.0,2.0,0.0,9032.0,11420.0,195.0,9038.0,11362.0,193.0,-6.0,58.0,2.0,1.0,4.0,2.0,0.0,4.0,0.0
12179,LOLTMNT02_350457,LCKC,2026-02-09 08:38:51,5,16.03,200,Red,team,NaN,Nongshim Esports Academy,0.0,NaN,Neeko,Aphelios,Gwen,Caitlyn,Ashe,Jayce,Zaahen,Kai'Sa,Twisted Fate,Blitzcrank,1721,1,16,6,34,16,6,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.5578,0.7670,0.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,10.0,2.0,1.0,1.0,44.0,13.0,1.0,0.0,69157,2411.0517,NaN,2696.5834,1970.6566,42760.0,110,3.8350,44,1.5340,25.0,281,9.7966,61455,42523,1482.4985,NaN,54888.0,0.208595,2.14,NaN,843.0,180,35.6653,17846.0,19442.0,352.0,17260.0,20461.0,350.0,586.0,-1019.0,2.0,3.0,4.0,3.0,3.0,7.0,3.0,28538.0,32635.0,557.0,26373.0,32728.0,550.0,2165.0,-93.0,7.0,6.0,6.0,4.0,4.0,8.0,6.0,38585.0,45642.0,756.0,36051.0,44512.0,758.0,2534.0,1130.0,-2.0,7.0,9.0,4.0,4.0,8.0,7.0,52220.0,61371.0,936.0,42174.0,52625.0,882.0,10046.0,8746.0,54.0,11.0,18.0,4.0,4.0,8.0,11.0
66684,LOLTMNT05_196638,LEC,2026-06-07 18:59:23,5,16.10,1,Blue,top,BrokenBlade,G2 Esports,0.0,Kled,Orianna,Milio,Kalista,Miss Fortune,Jinx,NaN,NaN,NaN,NaN,NaN,1578,1,4,0,4,17,6,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6464,0.8745,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,18540,704.9430,0.263128,1334.1065,1125.7414,19905.0,13,0.4943,3,0.1141,5.0,36,1.3688,12265,8770,333.4601,0.241963,12125.0,NaN,NaN,243.0,239.0,4,9.2395,3295.0,4917.0,83.0,3488.0,4486.0,86.0,-193.0,431.0,-3.0,0.0,1.0,0.0,0.0,0.0,1.0,4934.0,7853.0,127.0,5273.0,8022.0,137.0,-339.0,-169.0,-10.0,0.0,1.0,0.0,0.0,0.0,1.0,7678.0,11423.0,179.0,7010.0,10312.0,179.0,668.0,1111.0,0.0,0.0,3.0,0.0,0.0,0.0,2.0,11275.0,15826.0,229.0,8188.0,11745.0,186.0,3087.0,4081.0,43.0,3.0,3.0,0.0,0.0,2.0,3.0
60298,LOLTMNT02_411619,LCS,2026-05-24 23:44:08,5,16.10,100,Blue,team,NaN,Team Liquid,1.0,NaN,Lulu,Akali,Vayne,K'Sante,Garen,Annie,Rek'Sai,Jax,Sona,Aphelios,2166,0,4,10,5,4,10,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.1108,0.3878,1.0,2.0,4.0,2.0,4.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,1.0,NaN,0.0,3.0,7.0,1.0,1.0,15.0,15.0,0.0,1.0,54589,1512.1607,NaN,2743.1025,2288.5042,20048.0,120,3.3241,77,2.1330,44.0,387,10.7202,62504,39033,1081.2465,NaN,59918.0,0.016236,0.81,NaN,1057.0,255,36.3435,16682.0,21260.0,394.0,15941.0,20996.0,361.0,741.0,264.0,33.0,0.0,0.0,0.0,0.0,0.0,0.0,26454.0,33395.0,602.0,25051.0,34065.0,575.0,1403.0,-670.0,27.0,1.0,1.0,1.0,1.0,2.0,1.0,35552.0,45714.0,815.0,33859.0,46265.0,780.0,1693.0,-551.0,35.0,1.0,1.0,1.0,1.0,2.0,1.0,43384.0,56555.0,998.0,42049.0,59179.0,971.0,1335.0,-2624.0,27.0,1.0,1.0,2.0,2.0,4.0,1.0
16732,LOLTMNT05_175985,TCL,2026-02-20 18:53:08,5,16.03,5,Blue,sup,Lekcyc,Bushido Wildcats,1.0,Braum,Qiyana,Ambessa,Galio,Yasuo,Pantheon,NaN,NaN,NaN,NaN,NaN,1801,1,0,3,12,19,10,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6330,0.9661,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4795,159.7446,0.058824,531.0383,462.1099,461.0,52,1.7324,9,0.2998,13.0,105,3.4981,8244,4294,143.0539,0.092753,7745.0,NaN,NaN,27.0,27.0,0,0.8995,2457.0,2966.0,13.0,2299.0,2547.0,16.0,158.0,419.0,-3.0,0.0,1.0,0.0,0.0,1.0,1.0,3710.0,4088.0,21.0,3575.0,3064.0,26.0,135.0,1024.0,-5.0,0.0,3.0,1.0,0.0,2.0,2.0,4859.0,5542.0,24.0,4978.0,4703.0,32.0,-119.0,839.0,-8.0,0.0,4.0,1.0,0.0,2.0,2.0,6683.0,7973.0,24.0,6091.0,5883.0,35.0,592.0,2090.0,-11.0,0.0,8.0,3.0,0.0,3.0,4.0
97765,LOLTMNT04_188239,EBL,2026-09-02 19:36:32,5,16.17,2,Blue,jng,BanaBeer,RLX Esports,1.0,Vi,Locke,Olaf,Caitlyn,Rell,Leona,NaN,NaN,NaN,NaN,NaN,2099,0,4,8,11,22,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6289,1.4864,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,18082,516.8747,0.136298,1010.0238,1042.6679,285.0,10,0.2859,7,0.2001,8.0,36,1.0291,12188,7630,218.1039,0.180940,11883.0,NaN,NaN,191.0,41.0,150,5.4597,3346.0,3614.0,69.0,3969.0,4508.0,87.0,-623.0,-894.0,-18.0,0.0,2.0,0.0,1.0,0.0,0.0,5043.0,6053.0,105.0,5998.0,7200.0,130.0,-955.0,-1147.0,-25.0,1.0,2.0,1.0,2.0,0.0,0.0,7005.0,7233.0,115.0,9466.0,10597.0,168.0,-2461.0,-3364.0,-53.0,3.0,3.0,3.0,5.0,3.0,0.0,8886.0,9510.0,132.0,12426.0,14616.0,216.0,-3540.0,-5106.0,-84.0,4.0,5.0,6.0,6.0,7.0,0.0
63447,LOLTMNT02_415476,HM,2026-05-30 14:21:20,5,16.10,4,Blue,bot,Strode,Nightbirds,1.0,Tristana,Nautilus,LeBlanc,Lee Sin,Neeko,Yuumi,NaN,NaN,NaN,NaN,NaN,2045,0,8,3,2,15,24,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.4401,1.1443,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,1.0,28227,828.1760,0.282731,514.6797,308.5672,7168.0,11,0.3227,16,0.4694,3.0,45,1.3203,16994,12547,368.1271,0.306224,16725.0,NaN,NaN,378.0,355.0,23,11.0905,3916.0,3466.0,89.0,4075.0,3662.0,97.0,-159.0,-196.0,-8.0,2.0,0.0,1.0,1.0,0.0,0.0,6690.0,6734.0,149.0,7394.0,5926.0,151.0,-704.0,808.0,-2.0,3.0,0.0,1.0,3.0,0.0,1.0,10067.0,10286.0,225.0,10255.0,8876.0,213.0,-188.0,1410.0,12.0,5.0,0.0,1.0,4.0,1.0,2.0,12334.0,12270.0,273.0,14163.0,12008.0,250.0,-1829.0,262.0,23.0,6.0,2.0,1.0,7.0,6.0,3.0
71466,LOLTMNT01_417281,MSI,2026-07-04 10:12:57,5,16.13,7,Red,jng,Xun,Bilibili Gaming,1.0,Kindred,Nocturne,Lucian,Vayne,Zeri,Blitzcrank,NaN,NaN,NaN,NaN,NaN,1617,1,3,0,6,10,3,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.3711,0.4824,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,18306,679.2579,0.272841,755.6586,561.0019,4137.0,11,0.4082,15,0.5566,7.0,55,2.0408,12414,8840,328.0148,0.235133,10208.0,NaN,NaN,249.0,33.0,216,9.2393,3933.0,4313.0,82.0,3285.0,3701.0,72.0,648.0,612.0,10.0,1.0,0.0,0.0,0.0,0.0,1.0,5854.0,7496.0,136.0,4670.0,5500.0,100.0,1184.0,1996.0,36.0,1.0,0.0,0.0,0.0,0.0,1.0,8032.0,10580.0,199.0,6457.0,8611.0,143.0,1575.0,1969.0,56.0,1.0,0.0,0.0,0.0,0.0,1.0,10611.0,14140.0,237.0,8169.0,10409.0,172.0,2442.0,3731.0,65.0,1.0,5.0,0.0,0.0,0.0,2.0

In [277]:
fst_df = df[df["league"] == 'FST']
fst_df.sample(15)

,gameid,league,date,game,patch,participantid,side,position,playername,teamname,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
25034,LOLTMNT01_350472,FST,2026-03-17 17:21:45,3,16.05,3,Blue,mid,Saint,LYON,0.0,LeBlanc,Orianna,Vi,Ambessa,Rakan,Karma,NaN,NaN,NaN,NaN,NaN,1835,1,3,2,7,12,4,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.3924,0.5232,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,26429,864.1635,0.306661,694.7902,331.5204,8398.0,6,0.1962,17,0.5559,4.0,47,1.5368,12632,8613,281.6240,0.208240,9250.0,NaN,NaN,286.0,286.0,0,9.3515,3635.0,5441.0,105.0,3211.0,4535.0,88.0,424.0,906.0,17.0,0.0,0.0,0.0,0.0,0.0,0.0,5339.0,7647.0,146.0,5069.0,7803.0,132.0,270.0,-156.0,14.0,0.0,1.0,2.0,1.0,0.0,0.0,7200.0,10179.0,192.0,6614.0,10312.0,176.0,586.0,-133.0,16.0,0.0,2.0,2.0,1.0,0.0,1.0,9333.0,13032.0,243.0,8113.0,12771.0,211.0,1220.0,261.0,32.0,0.0,3.0,2.0,1.0,0.0,1.0
24897,LOLTMNT01_350155,FST,2026-03-16 14:00:50,2,16.05,10,Red,sup,Kellin,BNK FEARX,1.0,Karma,Nautilus,Gnar,Xin Zhao,Bard,Leona,NaN,NaN,NaN,NaN,NaN,1570,1,1,1,11,13,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4968,0.9172,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,9229,352.7006,0.121240,526.3185,309.8217,1415.0,46,1.7580,14,0.5350,11.0,99,3.7834,7532,4054,154.9299,0.113175,6695.0,NaN,NaN,32.0,32.0,0,1.2229,2304.0,2935.0,17.0,2397.0,2458.0,6.0,-93.0,477.0,11.0,0.0,0.0,0.0,0.0,1.0,0.0,4089.0,4184.0,25.0,3878.0,3646.0,16.0,211.0,538.0,9.0,1.0,2.0,0.0,0.0,4.0,2.0,5565.0,6059.0,28.0,5150.0,5470.0,19.0,415.0,589.0,9.0,1.0,5.0,0.0,0.0,6.0,2.0,6812.0,7321.0,32.0,6495.0,7738.0,21.0,317.0,-417.0,11.0,1.0,6.0,1.0,0.0,9.0,3.0
25262,LOLTMNT01_351251,FST,2026-03-20 16:45:05,2,16.05,3,Blue,mid,HongQ,JD Gaming,1.0,Annie,Pantheon,Poppy,Jarvan IV,Akali,Aurora,NaN,NaN,NaN,NaN,NaN,2462,0,3,3,11,18,13,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.4387,0.7555,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,34460,839.8050,0.271552,540.7555,595.4671,4093.0,28,0.6824,14,0.3412,15.0,66,1.6084,15125,9827,239.4882,0.189575,14925.0,NaN,NaN,327.0,326.0,1,7.9691,4019.0,4969.0,90.0,3154.0,4692.0,78.0,865.0,277.0,12.0,2.0,0.0,0.0,0.0,0.0,2.0,6002.0,8170.0,156.0,4803.0,7246.0,129.0,1199.0,924.0,27.0,2.0,0.0,0.0,0.0,0.0,2.0,8210.0,11492.0,216.0,6809.0,10289.0,193.0,1401.0,1203.0,23.0,2.0,0.0,0.0,0.0,0.0,2.0,10080.0,14630.0,253.0,9071.0,15322.0,247.0,1009.0,-692.0,6.0,2.0,4.0,0.0,0.0,0.0,2.0
25070,LOLTMNT01_349770,FST,2026-03-18 13:11:19,1,16.05,3,Blue,mid,Knight,Bilibili Gaming,0.0,Galio,Orianna,Rumble,Ryze,Renekton,Jax,NaN,NaN,NaN,NaN,NaN,1973,1,4,2,5,16,8,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.4866,0.7299,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,19142,582.1186,0.179259,721.2468,1037.0907,3465.0,13,0.3953,7,0.2129,7.0,40,1.2164,12605,8304,252.5291,0.178306,11775.0,NaN,NaN,267.0,267.0,0,8.1196,4054.0,5508.0,105.0,3519.0,4972.0,99.0,535.0,536.0,6.0,1.0,0.0,0.0,0.0,0.0,1.0,5717.0,7463.0,140.0,5052.0,7318.0,146.0,665.0,145.0,-6.0,2.0,0.0,0.0,0.0,0.0,2.0,7208.0,9628.0,177.0,6658.0,10067.0,196.0,550.0,-439.0,-19.0,2.0,0.0,0.0,0.0,0.0,2.0,8562.0,11548.0,208.0,8424.0,12697.0,239.0,138.0,-1149.0,-31.0,2.0,1.0,1.0,0.0,2.0,2.0
25553,LOLTMNT01_351479,FST,2026-03-21 16:45:59,2,16.05,6,Red,top,Xiaoxu,JD Gaming,1.0,Renekton,Seraphine,Pantheon,Lulu,Xin Zhao,Annie,NaN,NaN,NaN,NaN,NaN,1787,0,1,5,1,7,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.2350,0.7387,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,14925,501.1192,0.240060,1150.2071,948.6849,1725.0,13,0.4365,2,0.0672,2.0,25,0.8394,9592,5671,190.4085,0.177568,9380.0,NaN,NaN,246.0,236.0,10,8.2597,3602.0,5044.0,99.0,3505.0,5075.0,84.0,97.0,-31.0,15.0,0.0,0.0,0.0,1.0,0.0,0.0,4998.0,7808.0,128.0,5573.0,9025.0,135.0,-575.0,-1217.0,-7.0,0.0,1.0,3.0,2.0,1.0,0.0,6554.0,10508.0,171.0,7339.0,12478.0,188.0,-785.0,-1970.0,-17.0,0.0,1.0,3.0,2.0,2.0,0.0,8515.0,13778.0,224.0,8938.0,15408.0,229.0,-423.0,-1630.0,-5.0,1.0,1.0,3.0,2.0,3.0,0.0
25526,LOLTMNT01_352425,FST,2026-03-21 14:58:22,3,16.05,3,Blue,mid,Caps,G2 Esports,0.0,Akali,Orianna,Ryze,Rumble,Nocturne,Wukong,NaN,NaN,NaN,NaN,NaN,1815,1,5,0,3,16,3,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.5289,0.6281,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,18142,599.7355,0.256762,791.1405,638.3802,7912.0,10,0.3306,6,0.1983,7.0,34,1.1240,13200,9222,304.8595,0.212210,12175.0,NaN,NaN,281.0,281.0,0,9.2893,3681.0,5015.0,85.0,3354.0,5149.0,93.0,327.0,-134.0,-8.0,1.0,0.0,0.0,0.0,0.0,0.0,5633.0,8068.0,141.0,5155.0,8135.0,152.0,478.0,-67.0,-11.0,1.0,1.0,0.0,0.0,1.0,0.0,7872.0,11401.0,201.0,7057.0,11052.0,212.0,815.0,349.0,-11.0,1.0,1.0,0.0,0.0,1.0,1.0,10560.0,14081.0,234.0,9278.0,14027.0,269.0,1282.0,54.0,-35.0,4.0,2.0,0.0,0.0,2.0,2.0
25784,LOLTMNT01_352609,FST,2026-03-22 14:14:31,2,16.05,9,Red,bot,Viper,Bilibili Gaming,1.0,Ezreal,Karma,Ashe,Rumble,Renekton,Jax,NaN,NaN,NaN,NaN,NaN,2373,1,7,4,10,28,12,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.7080,1.0114,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,45564,1152.0607,0.244397,737.5980,448.5967,12762.0,26,0.6574,10,0.2528,14.0,68,1.7193,20787,15670,396.2073,0.288328,17958.0,NaN,NaN,385.0,372.0,13,9.7345,4039.0,4168.0,92.0,3256.0,3383.0,64.0,783.0,785.0,28.0,1.0,2.0,1.0,1.0,1.0,1.0,6313.0,6455.0,145.0,5501.0,5965.0,118.0,812.0,490.0,27.0,1.0,2.0,1.0,1.0,1.0,1.0,8775.0,8952.0,185.0,7142.0,7771.0,158.0,1633.0,1181.0,27.0,2.0,4.0,1.0,1.0,1.0,3.0,11094.0,11342.0,246.0,9239.0,9865.0,210.0,1855.0,1477.0,36.0,2.0,5.0,1.0,1.0,1.0,3.0
25004,LOLTMNT01_349529,FST,2026-03-17 14:43:27,3,16.05,9,Red,bot,GALA,JD Gaming,1.0,Corki,Varus,Neeko,Galio,Nautilus,Renata Glasc,NaN,NaN,NaN,NaN,NaN,1794,0,3,2,3,9,15,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3010,0.8027,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,18522,619.4649,0.241115,498.8629,367.7592,3042.0,12,0.4013,22,0.7358,4.0,59,1.9732,13484,9549,319.3645,0.297946,13133.0,NaN,NaN,341.0,333.0,8,11.4047,4043.0,3628.0,102.0,3325.0,3304.0,86.0,718.0,324.0,16.0,1.0,1.0,0.0,0.0,1.0,1.0,6624.0,6381.0,173.0,5695.0,5546.0,142.0,929.0,835.0,31.0,1.0,1.0,0.0,0.0,1.0,1.0,9493.0,8503.0,233.0,7842.0,8135.0,202.0,1651.0,368.0,31.0,3.0,2.0,0.0,0.0,1.0,1.0,11465.0,10381.0,290.0,10660.0,11597.0,263.0,805.0,-1216.0,27.0,3.0,2.0,1.0,0.0,4.0,1.0
25172,LOLTMNT01_350983,FST,2026-03-19 14:45:26,3,16.05,9,Red,bot,Berserker,LYON,0.0,Lucian,Ryze,Rumble,Bard,Twisted Fate,Viktor,NaN,NaN,NaN,NaN,NaN,1507,0,7,8,0,8,30,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.3185,1.5129,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,18844,750.2588,0.362183,1131.4001,548.9184,0.0,9,0.3583,3,0.1194,1.0,14,0.5574,12977,9627,383.2913,0.363746,12425.0,NaN,NaN,208.0,208.0,0,8.2814,3084.0,3307.0,79.0,4062.0,3713.0,95.0,-978.0,-406.0,-16.0,0.0,0.0,1.0,1.0,0.0,0.0,5899.0,5870.0,121.0,7173.0,6380.0,143.0,-1274.0,-510.0,-22.0,2.0,0.0,4.0,2.0,1.0,1.0,10431.0,8838.0,165.0,10565.0,9153.0,188.0,-134.0,-315.0,-23.0,6.0,0.0,6.0,5.0,3.0,2.0,12965.0,12147.0,208.0,13698.0,12502.0,222.0,-733.0,-355.0,-14.0,7.0,0.0,8.0,8.0,8.0,2.0
24940,LOLTMNT01_349312,FST,2026-03-16 17:26:29,1,16.05,5,Blue,sup,Bie,Team Secret Whales,0.0,Rakan,Orianna,K'Sante,Ryze,Neeko,Nami,NaN,NaN,NaN,NaN,NaN,1762,0,1,4,5,10,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.3405,1.0897,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,6417,218.5131,0.081377,706.5834,682.4745,455.0,61,2.0772,22,0.7491,8.0,146,4.9716,7367,3497,119.0806,0.110726,7255.0,NaN,NaN,34.0,34.0,0,1.1578,2390.0,2443.0,10.0,2474.0,2933.0,9.0,-84.0,-490.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3968.0,3384.0,19.0,3772.0,4159.0,12.0,196.0,-775.0,7.0,1.0,0.0,1.0,0.0,3.0,1.0,5275.0,4906.0,25.0,5693.0,6149.0,18.0,-418.0,-1243.0,7.0,1.0,4.0,2.0,1.0,7.0,2.0,6399.0,7132.0,30.0,7319.0,8364.0,23.0,-920.0,-1232.0,7.0,1.0,4.0,2.0,1.0,10.0,2.0
25768,LOLTMNT01_351652,FST,2026-03-22 13:14:42,1,16.05,5,Blue,sup,Labrov,G2 Esports,0.0,Nami,Orianna,Ryze,Varus,Ahri,LeBlanc,NaN,NaN,NaN,NaN,NaN,2291,1,2,4,16,23,13,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.6024,0.9428,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,10893,285.2815,0.095621,552.7281,273.8891,603.0,69,1.8071,16,0.4190,6.0,147,3.8498,10339,5390,141.1611,0.108862,8805.0,NaN,NaN,30.0,30.0,0,0.7857,2774.0,2338.0,9.0,2962.0,2465.0,14.0,-188.0,-127.0,-5.0,1.0,1.0,1.0,1.0,2.0,1.0,4048.0,3593.0,10.0,4307.0,4188.0,23.0,-259.0,-595.0,-13.0,2.0,1.0,2.0,1.0,4.0,2.0,5710.0,5967.0,18.0,5309.0,5364.0,25.0,401.0,603.0,-7.0,2.0,6.0,2.0,1.0,4.0,4.0,7033.0,7797.0,24.0,6456.0,6741.0,28.0,577.0,1056.0,-4.0,2.0,8.0,2.0,1.0,4.0,4.0
25102,LOLTMNT01_349782,FST,2026-03-18 14:54:58,3,16.05,100,Blue,team,NaN,Bilibili Gaming,1.0,NaN,Karma,Bard,Jarvan IV,Maokai,Twisted Fate,Lulu,Yunara,Renekton,Wukong,Akali,1804,1,27,12,41,27,12,3.0,2.0,0.0,0.0,1.0,NaN,NaN,NaN,0.8980,1.2971,1.0,4.0,1.0,4.0,1.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,1.0,1.0,0.0,2.0,1.0,1.0,1.0,0.0,0.0,1.0,9.0,1.0,1.0,1.0,42.0,7.0,1.0,0.0,108275,3601.1641,NaN,3996.9180,3152.4612,44684.0,97,3.2262,48,1.5965,32.0,286,9.5122,66942,47163,1568.6142,NaN,58263.0,0.107675,5.25,NaN,881.0,219,36.5854,19444.0,21926.0,363.0,15039.0,18532.0,314.0,4405.0,3394.0,49.0,8.0,8.0,0.0,0.0,0.0,8.0,29030.0,35681.0,590.0,23014.0,30340.0,519.0,6016.0,5341.0,71.0,9.0,9.0,0.0,0.0,0.0,9.0,43676.0,50215.0,794.0,34146.0,44198.0,702.0,9530.0,6017.0,92.0,15.0,18.0,4.0,4.0,12.0,15.0,54102.0,61266.0,945.0,45342.0,55631.0,816.0,8760.0,5635.0,129.0,21.0,28.0,9.0,9.0,28.0,21.0
25029,LOLTMNT01_349555,FST,2026-03-17 16:26:02,2,16.05,10,Red,sup,RedBert,LOUD,1.0,Renata Glasc,Varus,Nocturne,Xin Zhao,Zaahen,Trundle,NaN,NaN,NaN,NaN,NaN,2177,1,0,4,13,20,11,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5512,0.8544,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1.0,0.0,8641,238.1534,0.080691,643.6840,540.4410,832.0,57,1.5710,12,0.3307,9.0,133,3.6656,9339,4622,127.3863,0.093260,7935.0,NaN,NaN,39.0,39.0,0,1.0749,2348.0,2616.0,19.0,2465.0,2460.0,12.0,-117.0,156.0,7.0,0.0,2.0,1.0,0.0,0.0,1.0,3649.0,4326.0,27.0,3754.0,4235.0,32.0,-105.0,91.0,-5.0,0.0,4.0,1.0,0.0,0.0,1.0,4863.0,5114.0,32.0,5201.0,5847.0,36.0,-338.0,-733.0,-4.0,0.0,4.0,2.0,1.0,0.0,1.0,5964.0,7719.0,35.0,6434.0,8454.0,41.0,-470.0,-735.0,-6.0,0.0,4.0,2.0,1.0,2.0,1.0
24955,LOLTMNT01_349329,FST,2026-03-16 18:15:35,2,16.05,8,Red,mid,Dire,Team Secret Whales,1.0,Akali,Varus,Pantheon,Neeko,Xin Zhao,Zaahen,NaN,NaN,NaN,NaN,NaN,2004,0,3,6,8,19,22,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.5689,1.1976,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,24869,744.5808,0.199941,969.5509,639.8802,10591.0,9,0.2695,7,0.2096,8.0,41,1.2275,12089,7725,231.2874,0.187993,12150.0,NaN,NaN,271.0,271.0,0,8.1138,3935.0,4607.0,76.0,3157.0,4288.0,70.0,778.0,319.0,6.0,2.0,2.0,3.0,0.0,3.0,2.0,5775.0,7405.0,131.0,5014.0,7226.0,121.0,761.0,179.0,10.0,2.0,2.0,3.0,0.0,7.0,2.0,8040.0,10425.0,178.0,6964.0,10164.0,174.0,1076.0,261.0,4.0,3.0,5.0,3.0,1.0,7.0,3.0,9854.0,12718.0,226.0,8333.0,11592.0,197.0,1521.0,1126.0,29.0,3.0,6.0,3.0,1.0,8.0,4.0
25156,LOLTMNT01_350979,FST,2026-03-19 13:58:41,2,16.05,5,Blue,sup,Duro,Gen.G,1.0,Rakan,Karma,Varus,Neeko,Poppy,Wukong,NaN,NaN,NaN,NaN,NaN,1554,1,0,3,14,18,9,0.0,0.0,0.0,0.0,1.0,0.0,1.0,0.0,0.6950,1.0425,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,0.0,0.0,4701,181.5058,0.071765,502.0463,391.1583,319.0,51,1.9691,20,0.7722,10.0,131,5.0579,7589,4143,159.9614,0.106160,6080.0,NaN,NaN,29.0,29.0,0,1.1197,2729.0,2797.0,9.0,2217.0,2938.0,15.0,512.0,-141.0,-6.0,0.0,2.0,0.0,0.0,0.0,1.0,3934.0,3276.0,14.0,4158.0,4347.0,20.0,-224.0,-1071.0,-6.0,0.0,4.0,2.0,1.0,4.0,3.0,5121.0,4415.0,20.0,5708.0,5468.0,26.0,-587.0,-1053.0,-6.0,0.0,4.0,3.0,2.0,5.0,3.0,7088.0,7062.0,29.0,6682.0,6583.0,29.0,406.0,479.0,0.0,0.0,10.0,3.0,2.0,5.0,5.0

In [278]:
teamdf = df[df["position"] == "team"]
teamdf.sample(15)

,gameid,league,date,game,patch,participantid,side,position,playername,teamname,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
59687,LOLTMNT05_196110,LIT,2026-05-23 18:14:58,2,16.10,200,Red,team,NaN,StoneHenge Esports,0.0,NaN,Nautilus,Seraphine,Sion,Mel,Viktor,Yunara,Lulu,Ahri,Pantheon,Gangplank,2354,1,19,12,52,19,12,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4843,0.7647,1.0,3.0,3.0,3.0,3.0,0.0,2.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,1.0,0.0,1.0,9.0,4.0,0.0,1.0,36.0,25.0,1.0,0.0,113453,2891.7502,NaN,2809.7536,2461.4274,39444.0,117,2.9822,29,0.7392,31.0,280,7.1368,79335,53946,1375.0042,NaN,70735.0,0.070167,1.65,NaN,1052.0,269,33.6703,16860.0,19848.0,328.0,16761.0,21156.0,345.0,99.0,-1308.0,-17.0,3.0,8.0,2.0,2.0,5.0,3.0,27002.0,31937.0,522.0,25722.0,33982.0,542.0,1280.0,-2045.0,-20.0,5.0,15.0,4.0,4.0,7.0,5.0,39574.0,46260.0,732.0,35401.0,46360.0,718.0,4173.0,-100.0,14.0,9.0,22.0,7.0,7.0,16.0,9.0,48237.0,56384.0,901.0,44089.0,57529.0,890.0,4148.0,-1145.0,11.0,9.0,22.0,8.0,8.0,16.0,9.0
51586,13266-13266_game_2,LPL,2026-05-10 12:30:06,2,16.09,100,Blue,team,NaN,Anyone's Legend,0.0,NaN,Nocturne,Jarvan IV,Renekton,Skarner,Kha'Zix,Ashe,Seraphine,Ryze,Xin Zhao,Vayne,1739,1,13,3,31,13,3,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4485,0.5520,1.0,3.0,1.0,3.0,1.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,0.0,NaN,0.0,8.0,3.0,0.0,0.0,15.0,15.0,1.0,0.0,63393,2187.2225,NaN,3124.3818,2256.6072,33170.0,98,3.3813,52,1.7941,36.0,303,10.4543,56586,37470,1292.8120,NaN,50539.0,0.101916,2.72,NaN,NaN,235,NaN,17718.0,20194.0,362.0,15934.0,19612.0,330.0,1784.0,582.0,32.0,4.0,7.0,1.0,1.0,1.0,4.0,26839.0,32182.0,578.0,24173.0,31315.0,524.0,2666.0,867.0,54.0,5.0,10.0,1.0,1.0,1.0,5.0,36721.0,44249.0,777.0,34209.0,43648.0,751.0,2512.0,601.0,26.0,6.0,12.0,1.0,1.0,1.0,6.0,48912.0,59959.0,912.0,42093.0,52738.0,888.0,6819.0,7221.0,24.0,10.0,25.0,2.0,2.0,3.0,10.0
13031,LOLTMNT02_351245,HLL,2026-02-11 19:07:40,2,16.03,200,Red,team,NaN,Howl Esports,0.0,NaN,Cassiopeia,Syndra,Smolder,Lillia,Orianna,Aphelios,Trundle,Lulu,Riven,Anivia,1801,0,9,21,18,9,21,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.2998,0.9994,0.0,1.0,3.0,1.0,3.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,6.0,0.0,0.0,17.0,24.0,0.0,1.0,56165,1871.1272,NaN,4060.4775,3948.8728,18494.0,88,2.9317,40,1.3326,22.0,251,8.3620,50940,31192,1039.1560,NaN,50148.0,-0.022575,-2.26,NaN,779.0,173,31.7157,16068.0,19621.0,324.0,17872.0,20782.0,356.0,-1804.0,-1161.0,-32.0,1.0,1.0,4.0,4.0,4.0,2.0,26869.0,32041.0,482.0,27522.0,32262.0,520.0,-653.0,-221.0,-38.0,7.0,14.0,7.0,7.0,11.0,8.0,35737.0,44177.0,655.0,38770.0,45831.0,704.0,-3033.0,-1654.0,-49.0,8.0,14.0,13.0,13.0,22.0,9.0,43792.0,55098.0,827.0,47535.0,56420.0,873.0,-3743.0,-1322.0,-46.0,9.0,18.0,15.0,15.0,27.0,10.0
71002,LOLTMNT01_416609,HLL,2026-07-02 16:18:13,2,16.13,100,Blue,team,NaN,Valerion,1.0,NaN,Olaf,Nautilus,Viktor,Caitlyn,Shen,Orianna,Jhin,Neeko,Skarner,Gnar,1903,1,25,10,51,25,10,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.7882,1.1035,0.0,3.0,1.0,3.0,1.0,0.0,2.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,9.0,3.0,0.0,0.0,39.0,20.0,1.0,0.0,104929,3308.3237,NaN,3235.0184,3492.0126,42763.0,94,2.9637,32,1.0089,38.0,268,8.4498,66801,46012,1450.7199,NaN,59608.0,0.129561,1.71,NaN,907.0,212,35.2811,16740.0,19588.0,361.0,16175.0,19814.0,322.0,565.0,-226.0,39.0,2.0,4.0,3.0,3.0,2.0,3.0,26146.0,31639.0,560.0,24537.0,31811.0,505.0,1609.0,-172.0,55.0,3.0,6.0,4.0,4.0,3.0,4.0,37786.0,45035.0,743.0,33797.0,43874.0,691.0,3989.0,1161.0,52.0,9.0,18.0,6.0,6.0,6.0,10.0,48952.0,59344.0,916.0,43466.0,58588.0,857.0,5486.0,756.0,59.0,15.0,28.0,8.0,8.0,10.0,16.0
86459,LOLTMNT01_442351,LRN,2026-08-10 23:25:03,1,16.15,200,Red,team,NaN,Zeu5 Esports,1.0,NaN,Nocturne,Akali,Vayne,NaN,NaN,Pantheon,Ezreal,Bard,Twisted Fate,Dr. Mundo,2196,0,29,34,65,29,34,2.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.7923,1.7213,0.0,1.0,4.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,2.0,0.0,0.0,5.0,10.0,0.0,0.0,29.0,41.0,0.0,2.0,156818,4284.6448,NaN,5879.6175,4291.4481,24343.0,89,2.4317,32,0.8743,26.0,264,7.2131,73428,49651,1356.5847,NaN,69913.0,-0.018634,-0.73,NaN,916.0,185,30.0820,16552.0,19659.0,342.0,17266.0,20727.0,359.0,-714.0,-1068.0,-17.0,2.0,3.0,4.0,4.0,2.0,2.0,27298.0,33319.0,518.0,26972.0,33225.0,541.0,326.0,94.0,-23.0,7.0,9.0,8.0,8.0,4.0,7.0,36228.0,45184.0,679.0,38509.0,45834.0,707.0,-2281.0,-650.0,-28.0,9.0,13.0,13.0,13.0,13.0,9.0,48473.0,59252.0,852.0,48133.0,58236.0,859.0,340.0,1016.0,-7.0,15.0,26.0,17.0,17.0,22.0,15.0
32170,LOLTMNT01_360762,LES,2026-04-09 17:00:41,1,16.07,100,Blue,team,NaN,GIANTX iTero,0.0,NaN,K'Sante,Xin Zhao,Akali,Renekton,Sion,Ezreal,Nami,Shen,Ambessa,Aurora,1584,1,18,5,36,18,5,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.6818,0.8333,0.0,3.0,1.0,3.0,1.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,1.0,1.0,0.0,0.0,1.0,9.0,1.0,1.0,1.0,37.0,12.0,2.0,0.0,79782,3022.0455,NaN,2803.1818,2570.5682,38283.0,68,2.5758,33,1.2500,16.0,204,7.7273,57366,39831,1508.7500,NaN,49918.0,0.198837,3.26,NaN,779.0,231,38.2576,17274.0,20873.0,369.0,15464.0,19980.0,351.0,1810.0,893.0,18.0,3.0,5.0,0.0,0.0,0.0,3.0,27629.0,32950.0,552.0,23989.0,31481.0,525.0,3640.0,1469.0,27.0,6.0,10.0,2.0,2.0,2.0,6.0,39578.0,47677.0,770.0,31814.0,41806.0,699.0,7764.0,5871.0,71.0,9.0,17.0,2.0,2.0,2.0,9.0,50992.0,64380.0,980.0,42156.0,55421.0,879.0,8836.0,8959.0,101.0,12.0,20.0,4.0,4.0,4.0,12.0
106954,LOLTMNT05_223033,EM,2026-09-22 20:25:52,3,16.18,100,Blue,team,NaN,Pyramid IV Esports,1.0,NaN,Lee Sin,Orianna,Zeri,Rell,Rakan,Qiyana,Ambessa,Ryze,Braum,Tristana,2334,1,21,24,54,21,24,2.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,0.5398,1.1568,1.0,3.0,3.0,3.0,3.0,0.0,1.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,10.0,9.0,0.0,0.0,44.0,45.0,1.0,1.0,136502,3509.0488,NaN,4183.5990,3953.0591,40772.0,142,3.6504,67,1.7224,48.0,398,10.2314,82727,57542,1479.2288,NaN,73660.0,0.000027,-0.50,NaN,1127.0,233,34.9614,16619.0,19731.0,345.0,17030.0,20181.0,349.0,-411.0,-450.0,-4.0,2.0,3.0,4.0,4.0,2.0,2.0,27021.0,32783.0,548.0,25983.0,32613.0,557.0,1038.0,170.0,-9.0,5.0,9.0,5.0,5.0,3.0,5.0,37662.0,45881.0,763.0,36465.0,44775.0,766.0,1197.0,1106.0,-3.0,7.0,14.0,7.0,7.0,6.0,7.0,46943.0,58827.0,945.0,49207.0,59905.0,936.0,-2264.0,-1078.0,9.0,7.0,14.0,10.0,10.0,14.0,7.0
95974,LOLTMNT01_450816,LCS,2026-08-29 23:58:49,2,16.17,100,Blue,team,NaN,LYON,0.0,NaN,Ezreal,Cassiopeia,Poppy,Ambessa,Gwen,Lee Sin,Lulu,Yunara,Renekton,LeBlanc,2086,1,8,4,22,8,4,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2301,0.3452,0.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,7.0,0.0,1.0,1.0,30.0,7.0,1.0,0.0,82863,2383.4036,NaN,2338.9933,2509.6165,30754.0,136,3.9118,72,2.0709,52.0,389,11.1889,66204,43549,1252.6079,NaN,58725.0,0.116884,2.33,NaN,1070.0,273,38.6290,17759.0,20632.0,389.0,16050.0,20285.0,366.0,1709.0,347.0,23.0,2.0,3.0,1.0,1.0,1.0,2.0,26489.0,31654.0,589.0,24388.0,31950.0,552.0,2101.0,-296.0,37.0,2.0,3.0,3.0,3.0,5.0,2.0,37127.0,45294.0,821.0,33189.0,44539.0,754.0,3938.0,755.0,67.0,3.0,4.0,4.0,4.0,6.0,3.0,46161.0,57448.0,1037.0,41385.0,55952.0,964.0,4776.0,1496.0,73.0,3.0,4.0,4.0,4.0,6.0,3.0
19306,13126-13126_game_2,LPL,2026-02-27 10:10:57,2,16.03,100,Blue,team,NaN,Bilibili Gaming,0.0,NaN,Orianna,Rumble,Neeko,Nami,Miss Fortune,Ashe,Xin Zhao,Gnar,LeBlanc,Shen,1453,1,25,9,37,25,9,3.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,1.0323,1.4040,1.0,3.0,0.0,3.0,0.0,1.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,0.0,1.0,1.0,0.0,NaN,1.0,8.0,1.0,1.0,1.0,15.0,11.0,2.0,0.0,85158,3516.5038,NaN,3862.2161,2819.0502,34664.0,68,2.8080,25,1.0323,17.0,184,7.5981,54688,38489,1589.3599,NaN,45390.0,0.132513,4.22,NaN,NaN,191,NaN,19823.0,21237.0,352.0,15541.0,18623.0,312.0,4282.0,2614.0,40.0,10.0,16.0,1.0,1.0,1.0,10.0,29998.0,34251.0,550.0,26612.0,31740.0,466.0,3386.0,2511.0,84.0,14.0,22.0,6.0,6.0,10.0,14.0,42068.0,48558.0,782.0,34222.0,42492.0,645.0,7846.0,6066.0,137.0,17.0,23.0,6.0,6.0,10.0,17.0,54688.0,64752.0,906.0,42843.0,52093.0,738.0,11845.0,12659.0,168.0,25.0,37.0,9.0,9.0,15.0,25.0
109018,LOLTMNT01_466868,CBLOL,2026-09-27 16:09:43,1,16.17,100,Blue,team,NaN,LOUD,1.0,NaN,Karma,Camille,Nocturne,Syndra,Taliyah,Milio,Lucian,Ryze,Lee Sin,K'Sante,1976,0,7,13,20,7,13,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.2126,0.6073,0.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,1.0,0.0,0.0,3.0,7.0,0.0,0.0,22.0,30.0,0.0,1.0,51628,1567.6518,NaN,2773.6032,3102.9960,20685.0,133,4.0385,52,1.5789,57.0,320,9.7166,58775,37242,1130.8300,NaN,57320.0,-0.027461,-2.53,NaN,1036.0,228,38.3806,16898.0,19157.0,343.0,18863.0,20718.0,385.0,-1965.0,-1561.0,-42.0,3.0,6.0,5.0,5.0,10.0,3.0,25694.0,32320.0,572.0,28608.0,33367.0,610.0,-2914.0,-1047.0,-38.0,3.0,6.0,5.0,5.0,10.0,3.0,35042.0,45516.0,784.0,38788.0,47016.0,834.0,-3746.0,-1500.0,-50.0,4.0,10.0,7.0,7.0,16.0,4.0,43564.0,59246.0,996.0,47533.0,59708.0,1060.0,-3969.0,-462.0,-64.0,4.0,10.0,7.0,7.0,16.0,4.0
18767,LOLTMNT06_169008,TCL,2026-02-26 14:58:58,1,16.04,200,Red,team,NaN,S2G Esports,0.0,NaN,Dr. Mundo,Orianna,Jarvan IV,Ornn,Renekton,Varus,Xin Zhao,Ahri,Zaahen,Rakan,2177,1,22,11,43,22,11,5.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.6063,0.9095,1.0,4.0,2.0,4.0,2.0,0.0,1.0,2.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,1.0,10.0,1.0,1.0,1.0,40.0,12.0,1.0,0.0,125298,3453.3211,NaN,3864.8323,4109.3523,37743.0,119,3.2797,74,2.0395,34.0,404,11.1346,74527,50944,1404.0606,NaN,65913.0,0.053013,2.33,NaN,1004.0,295,35.8016,17725.0,21073.0,376.0,16627.0,19793.0,355.0,1098.0,1280.0,21.0,3.0,2.0,2.0,2.0,4.0,3.0,27810.0,34652.0,602.0,25468.0,31547.0,550.0,2342.0,3105.0,52.0,5.0,5.0,3.0,3.0,6.0,5.0,38911.0,46675.0,775.0,34192.0,41233.0,706.0,4719.0,5442.0,69.0,9.0,13.0,4.0,4.0,7.0,9.0,51213.0,63453.0,978.0,42435.0,50640.0,845.0,8778.0,12813.0,133.0,14.0,23.0,5.0,5.0,9.0,14.0
29303,LOLTMNT02_377156,LCK,2026-04-03 08:10:24,1,16.06,200,Red,team,NaN,Gen.G,1.0,NaN,Nautilus,Pantheon,Azir,Annie,Mel,Aurora,Ashe,Seraphine,K'Sante,Nocturne,1553,0,9,14,15,9,14,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3477,0.8886,1.0,1.0,3.0,1.0,3.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,NaN,0.0,3.0,9.0,0.0,0.0,15.0,14.0,0.0,1.0,54968,2123.6832,NaN,3527.2891,2972.3374,18499.0,86,3.3226,40,1.5454,27.0,238,9.1951,46568,29349,1133.8957,NaN,45620.0,0.029743,-1.91,NaN,740.0,161,34.8100,16614.0,20832.0,354.0,17661.0,20397.0,383.0,-1047.0,435.0,-29.0,1.0,1.0,2.0,2.0,3.0,1.0,26072.0,33317.0,541.0,27393.0,32925.0,581.0,-1321.0,392.0,-40.0,4.0,6.0,4.0,4.0,4.0,4.0,34490.0,45194.0,754.0,38307.0,44937.0,776.0,-3817.0,257.0,-22.0,4.0,6.0,6.0,6.0,9.0,4.0,45484.0,55271.0,896.0,48552.0,59704.0,914.0,-3068.0,-4433.0,-18.0,8.0,15.0,10.0,10.0,19.0,8.0
75334,LOLTMNT02_433542,CD,2026-07-20 23:21:59,1,16.14,100,Blue,team,NaN,Estral Esports,0.0,NaN,Nocturne,Lee Sin,Ziggs,Leona,Nautilus,Jarvan IV,Yorick,Ryze,Bard,Ezreal,1559,1,14,5,22,14,5,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.5388,0.7312,0.0,2.0,2.0,2.0,2.0,0.0,2.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,2.0,1.0,1.0,0.0,0.0,1.0,11.0,1.0,1.0,1.0,45.0,11.0,3.0,0.0,58795,2262.7967,NaN,2946.0038,2710.7377,41254.0,80,3.0789,29,1.1161,27.0,198,7.6203,55463,38183,1469.5189,NaN,50946.0,0.207103,2.62,NaN,804.0,187,38.1398,17832.0,19868.0,347.0,16534.0,19307.0,339.0,1298.0,561.0,8.0,3.0,5.0,2.0,2.0,3.0,3.0,28738.0,34421.0,573.0,24541.0,31133.0,546.0,4197.0,3288.0,27.0,6.0,8.0,2.0,2.0,3.0,6.0,37955.0,46895.0,782.0,33575.0,43599.0,755.0,4380.0,3296.0,27.0,6.0,8.0,3.0,3.0,6.0,6.0,52256.0,66160.0,964.0,42243.0,55479.0,938.0,10013.0,10681.0,26.0,12.0,19.0,4.0,4.0,7.0,12.0
63947,LOLTMNT02_415819,RL,2026-05-31 18:25:15,4,16.10,200,Red,team,NaN,Forsaken,0.0,NaN,Orianna,Akali,Vayne,Sivir,Ziggs,Trundle,Jhin,Malphite,Rakan,LeBlanc,1857,1,23,6,44,23,6,3.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.7431,0.9370,1.0,3.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,2.0,0.0,0.0,1.0,12.0,0.0,1.0,1.0,45.0,10.0,5.0,0.0,91527,2957.2536,NaN,3342.5525,4488.8207,41852.0,83,2.6817,39,1.2601,16.0,251,8.1099,65807,45488,1469.7254,NaN,58948.0,0.135352,4.67,NaN,917.0,223,36.8336,17853.0,19919.0,349.0,15024.0,19162.0,321.0,2829.0,757.0,28.0,5.0,10.0,0.0,0.0,0.0,5.0,28132.0,33415.0,547.0,23482.0,30512.0,503.0,4650.0,2903.0,44.0,11.0,18.0,1.0,1.0,1.0,11.0,39858.0,48562.0,769.0,31399.0,42141.0,698.0,8459.0,6421.0,71.0,16.0,29.0,1.0,1.0,1.0,16.0,53062.0,64629.0,965.0,38957.0,54319.0,876.0,14105.0,10310.0,89.0,19.0,37.0,1.0,1.0,1.0,19.0
57611,LOLTMNT02_406775,CD,2026-05-20 21:52:57,3,16.10,200,Red,team,NaN,KaBuM! Ilha das Lendas,1.0,NaN,Annie,Nautilus,Wukong,Vayne,Jax,Nocturne,Zeri,Yuumi,Mel,K'Sante,1937,1,27,5,69,27,5,4.0,1.0,0.0,0.0,1.0,NaN,NaN,NaN,0.8363,0.9912,0.0,4.0,1.0,4.0,1.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,1.0,1.0,0.0,0.0,9.0,4.0,0.0,1.0,40.0,23.0,1.0,0.0,119258,3694.1043,NaN,3656.9644,3895.5395,37958.0,118,3.6551,54,1.6727,43.0,316,9.7883,69048,47913,1484.1404,NaN,63320.0,0.187540,1.24,NaN,842.0,214,32.7104,16245.0,20370.0,356.0,16100.0,20118.0,370.0,145.0,252.0,-14.0,1.0,1.0,0.0,0.0,0.0,1.0,26650.0,33571.0,551.0,24370.0,30966.0,558.0,2280.0,2605.0,-7.0,5.0,9.0,1.0,1.0,3.0,5.0,34461.0,43841.0,722.0,34834.0,43301.0,751.0,-373.0,540.0,-29.0,5.0,9.0,3.0,3.0,7.0,5.0,45845.0,55261.0,834.0,42552.0,53185.0,858.0,3293.0,2076.0,-24.0,13.0,31.0,5.0,5.0,13.0,13.0

In [279]:
df["patch"].unique()

array([16.01, 16.02, 16.03, 16.04, 16.05, 16.06, 16.07, 16.08, 16.09,
       16.1 , 16.11, 16.12, 16.13, 16.14, 16.15, 16.16, 16.17, 16.18])

In [280]:
df["patch"].dtype

dtype('float64')

In [283]:
patch1616 = teamdf[teamdf["patch"] == 16.16]
patch1616.sample(15)

,gameid,league,date,game,patch,participantid,side,position,playername,teamname,firstPick,champion,ban1,ban2,ban3,ban4,ban5,pick1,pick2,pick3,pick4,pick5,gamelength,result,kills,deaths,assists,teamkills,teamdeaths,doublekills,triplekills,quadrakills,pentakills,firstblood,firstbloodkill,firstbloodassist,firstbloodvictim,team kpm,ckpm,firstdragon,dragons,opp_dragons,elementaldrakes,opp_elementaldrakes,infernals,mountains,clouds,oceans,chemtechs,hextechs,elders,opp_elders,firstherald,heralds,opp_heralds,void_grubs,opp_void_grubs,firstbaron,barons,opp_barons,opp_atakhans,firsttower,towers,opp_towers,firstmidtower,firsttothreetowers,turretplates,opp_turretplates,inhibitors,opp_inhibitors,damagetochampions,dpm,damageshare,damagetakenperminute,damagemitigatedperminute,damagetotowers,wardsplaced,wpm,wardskilled,wcpm,controlwardsbought,visionscore,vspm,totalgold,earnedgold,earned gpm,earnedgoldshare,goldspent,gspd,gpr,total cs,minionkills,monsterkills,cspm,goldat10,xpat10,csat10,opp_goldat10,opp_xpat10,opp_csat10,golddiffat10,xpdiffat10,csdiffat10,killsat10,assistsat10,deathsat10,opp_killsat10,opp_assistsat10,opp_deathsat10,goldat15,xpat15,csat15,opp_goldat15,opp_xpat15,opp_csat15,golddiffat15,xpdiffat15,csdiffat15,killsat15,assistsat15,deathsat15,opp_killsat15,opp_assistsat15,opp_deathsat15,goldat20,xpat20,csat20,opp_goldat20,opp_xpat20,opp_csat20,golddiffat20,xpdiffat20,csdiffat20,killsat20,assistsat20,deathsat20,opp_killsat20,opp_assistsat20,opp_deathsat20,goldat25,xpat25,csat25,opp_goldat25,opp_xpat25,opp_csat25,golddiffat25,xpdiffat25,csdiffat25,killsat25,assistsat25,deathsat25,opp_killsat25,opp_assistsat25,opp_deathsat25
90514,LOLTMNT02_452520,CD,2026-08-18 22:45:52,2,16.16,100,Blue,team,NaN,Vivo Keyd Stars Academy,0.0,NaN,Ezreal,Cassiopeia,Nocturne,Bard,Karma,Skarner,Ziggs,Alistar,Camille,Orianna,2270,0,11,22,28,11,22,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2907,0.8722,0.0,1.0,4.0,1.0,4.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,2.0,0.0,0.0,2.0,0.0,1.0,4.0,9.0,0.0,1.0,20.0,39.0,0.0,1.0,90041,2379.9383,NaN,3830.7225,4816.1762,22121.0,167,4.4141,57,1.5066,68.0,401,10.5991,67525,42993,1136.3789,NaN,65533.0,-0.084293,-0.46,NaN,1058.0,218,33.7269,16132.0,21103.0,364.0,16202.0,20734.0,379.0,-70.0,369.0,-15.0,0.0,0.0,0.0,0.0,0.0,0.0,25576.0,32805.0,580.0,24933.0,32047.0,569.0,643.0,758.0,11.0,1.0,1.0,1.0,1.0,3.0,1.0,37280.0,45232.0,724.0,34631.0,43249.0,735.0,2649.0,1983.0,-11.0,7.0,20.0,4.0,4.0,11.0,7.0,45118.0,55079.0,887.0,45219.0,55355.0,909.0,-101.0,-276.0,-22.0,8.0,21.0,7.0,7.0,20.0,8.0
92278,LOLTMNT02_456141,LCK,2026-08-21 09:09:34,2,16.16,100,Blue,team,NaN,BNK FEARX,0.0,NaN,Cassiopeia,Vi,Nocturne,Caitlyn,Kalista,Naafiri,Galio,Camille,Rakan,Ezreal,2169,0,9,16,15,9,16,1.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2490,0.6916,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,1.0,6.0,9.0,1.0,1.0,31.0,36.0,0.0,1.0,77724,2150.0415,NaN,3244.1770,3809.0180,31344.0,145,4.0111,66,1.8257,66.0,409,11.3140,65206,41704,1153.6376,NaN,63881.0,-0.032706,0.95,NaN,1052.0,253,36.0996,16869.0,19762.0,353.0,15938.0,20201.0,359.0,931.0,-439.0,-6.0,2.0,2.0,1.0,1.0,0.0,2.0,26667.0,32393.0,556.0,23686.0,30971.0,536.0,2981.0,1422.0,20.0,5.0,7.0,1.0,1.0,0.0,5.0,37748.0,44999.0,767.0,35297.0,44128.0,713.0,2451.0,871.0,54.0,7.0,13.0,5.0,5.0,15.0,7.0,47376.0,56365.0,945.0,45862.0,57238.0,899.0,1514.0,-873.0,46.0,9.0,15.0,9.0,9.0,23.0,9.0
93047,LOLTMNT05_220135,LEC,2026-08-23 15:08:05,1,16.16,200,Red,team,NaN,Team Heretics,0.0,NaN,Cassiopeia,Vi,Orianna,Seraphine,Karma,Ryze,Xin Zhao,Jayce,Bard,Caitlyn,2468,0,8,17,24,8,17,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.1945,0.6078,1.0,3.0,4.0,3.0,4.0,0.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,1.0,2.0,0.0,0.0,2.0,0.0,1.0,4.0,11.0,1.0,1.0,27.0,45.0,0.0,3.0,111269,2705.0810,NaN,3840.5105,3132.6904,17077.0,161,3.9141,82,1.9935,57.0,477,11.5964,72868,46316,1125.9968,NaN,68800.0,-0.081829,0.08,NaN,1269.0,284,37.7553,16618.0,20452.0,386.0,16681.0,20603.0,388.0,-63.0,-151.0,-2.0,0.0,0.0,1.0,1.0,3.0,0.0,26803.0,34263.0,609.0,25075.0,32410.0,600.0,1728.0,1853.0,9.0,3.0,10.0,1.0,1.0,3.0,3.0,36658.0,45698.0,837.0,33384.0,44360.0,809.0,3274.0,1338.0,28.0,3.0,10.0,1.0,1.0,3.0,3.0,46498.0,61016.0,1079.0,41517.0,57230.0,1013.0,4981.0,3786.0,66.0,4.0,13.0,1.0,1.0,3.0,4.0
88810,LOLTMNT05_218053,LEC,2026-08-14 17:48:14,2,16.16,100,Blue,team,NaN,GiantX,0.0,NaN,Akali,Jayce,Cassiopeia,Aatrox,Nautilus,Orianna,Nocturne,Varus,Alistar,Ornn,2128,1,17,13,46,17,13,3.0,2.0,1.0,0.0,0.0,NaN,NaN,NaN,0.4793,0.8459,0.0,2.0,3.0,2.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,2.0,1.0,0.0,1.0,1.0,0.0,0.0,7.0,6.0,0.0,0.0,31.0,34.0,1.0,0.0,97530,2749.9060,NaN,3496.6917,3083.1203,29633.0,144,4.0602,46,1.2970,48.0,334,9.4173,71779,48695,1372.9793,NaN,64700.0,-0.043588,-2.81,NaN,928.0,205,31.9455,15162.0,18870.0,330.0,18164.0,20913.0,394.0,-3002.0,-2043.0,-64.0,0.0,0.0,2.0,2.0,3.0,0.0,23422.0,29134.0,496.0,29587.0,33474.0,600.0,-6165.0,-4340.0,-104.0,2.0,5.0,5.0,5.0,6.0,2.0,35575.0,43108.0,659.0,40223.0,44930.0,769.0,-4648.0,-1822.0,-110.0,6.0,12.0,9.0,9.0,12.0,6.0,45938.0,54346.0,837.0,51313.0,60289.0,955.0,-5375.0,-5943.0,-118.0,8.0,17.0,12.0,12.0,17.0,8.0
93203,LOLTMNT02_456992,LCKC,2026-08-24 05:14:01,1,16.16,200,Red,team,NaN,Kiwoom DRX Challengers,0.0,NaN,Cassiopeia,Lucian,Lee Sin,Kai'Sa,Bard,Olaf,Orianna,Vi,Jhin,Alistar,2547,0,14,20,26,14,20,1.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3298,0.8009,1.0,2.0,4.0,2.0,4.0,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,1.0,1.0,2.0,0.0,0.0,5.0,11.0,0.0,0.0,27.0,45.0,0.0,3.0,111056,2616.1602,NaN,3577.7856,4388.8104,20340.0,173,4.0754,53,1.2485,74.0,403,9.4935,76235,48878,1151.4252,NaN,73750.0,-0.076396,-1.06,NaN,1154.0,257,33.2391,15864.0,19799.0,326.0,17035.0,20046.0,372.0,-1171.0,-247.0,-46.0,2.0,3.0,2.0,2.0,4.0,2.0,25096.0,32652.0,548.0,25155.0,31166.0,562.0,-59.0,1486.0,-14.0,3.0,6.0,3.0,3.0,7.0,3.0,34689.0,45874.0,760.0,34331.0,42943.0,762.0,358.0,2931.0,-2.0,5.0,9.0,4.0,4.0,7.0,5.0,42123.0,55709.0,907.0,44973.0,56603.0,962.0,-2850.0,-894.0,-55.0,6.0,10.0,7.0,7.0,14.0,6.0
93166,LOLTMNT02_457969,LCS,2026-08-23 20:56:15,2,16.16,100,Blue,team,NaN,Sentinels,0.0,NaN,Nocturne,Cassiopeia,Vi,Yone,Ivern,Yunara,Lulu,Kled,Trundle,Galio,1693,1,16,5,37,16,5,3.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.5670,0.7442,0.0,1.0,2.0,1.0,2.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,3.0,0.0,1.0,1.0,0.0,0.0,1.0,8.0,3.0,1.0,1.0,33.0,16.0,1.0,0.0,67465,2390.9628,NaN,3749.6633,3606.9108,36579.0,100,3.5440,32,1.1341,44.0,264,9.3562,57065,38418,1361.5357,NaN,50368.0,0.069606,1.02,NaN,789.0,206,35.2628,15778.0,19487.0,327.0,16780.0,19854.0,353.0,-1002.0,-367.0,-26.0,2.0,1.0,2.0,2.0,3.0,2.0,26456.0,32223.0,518.0,26481.0,32532.0,564.0,-25.0,-309.0,-46.0,5.0,8.0,4.0,4.0,5.0,5.0,37997.0,44239.0,685.0,33823.0,41677.0,723.0,4174.0,2562.0,-38.0,9.0,21.0,4.0,4.0,5.0,9.0,46519.0,56406.0,896.0,44016.0,55805.0,947.0,2503.0,601.0,-51.0,9.0,21.0,5.0,5.0,7.0,9.0
94546,LOLTMNT02_459728,CD,2026-08-26 20:12:25,1,16.16,100,Blue,team,NaN,7REX,0.0,NaN,Nocturne,Cassiopeia,Ryze,K'Sante,Olaf,Ezreal,Vi,Bard,Rumble,Yone,1907,0,11,22,31,11,22,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3461,1.0383,0.0,0.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,1.0,0.0,3.0,0.0,0.0,0.0,1.0,0.0,1.0,2.0,8.0,0.0,0.0,14.0,35.0,0.0,1.0,92304,2904.1636,NaN,4104.5412,4289.2606,18273.0,116,3.6497,55,1.7305,54.0,326,10.2569,54067,33238,1045.7682,NaN,52713.0,-0.083913,-1.62,NaN,767.0,204,30.5506,16246.0,20419.0,354.0,17898.0,21246.0,386.0,-1652.0,-827.0,-32.0,1.0,2.0,3.0,3.0,4.0,1.0,25012.0,33301.0,561.0,26401.0,33847.0,606.0,-1389.0,-546.0,-45.0,2.0,4.0,3.0,3.0,4.0,2.0,36349.0,45501.0,742.0,36177.0,45095.0,765.0,172.0,406.0,-23.0,6.0,17.0,6.0,6.0,14.0,6.0,44332.0,54873.0,878.0,45400.0,59487.0,925.0,-1068.0,-4614.0,-47.0,8.0,22.0,8.0,8.0,20.0,8.0
94654,LOLTMNT02_458808,LCK,2026-08-27 09:50:00,3,16.16,100,Blue,team,NaN,BNK FEARX,0.0,NaN,Cassiopeia,Ryze,Lucian,Zeri,Kalista,Olaf,Seraphine,Ashe,Azir,K'Sante,2210,1,18,10,51,18,10,2.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.4887,0.7602,1.0,4.0,2.0,4.0,2.0,0.0,0.0,0.0,0.0,3.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,1.0,2.0,0.0,0.0,0.0,9.0,5.0,1.0,1.0,38.0,28.0,1.0,0.0,98754,2681.1041,NaN,2973.0136,4540.4525,30705.0,157,4.2624,82,2.2262,64.0,444,12.0543,72860,48940,1328.6878,NaN,63480.0,-0.048165,0.94,NaN,1046.0,228,34.5882,16742.0,19330.0,348.0,15292.0,19015.0,340.0,1450.0,315.0,8.0,2.0,8.0,0.0,0.0,0.0,2.0,26135.0,31639.0,560.0,24900.0,31298.0,533.0,1235.0,341.0,27.0,4.0,12.0,3.0,3.0,8.0,4.0,35995.0,42271.0,728.0,36430.0,44257.0,708.0,-435.0,-1986.0,20.0,7.0,18.0,8.0,8.0,22.0,7.0,47009.0,57995.0,896.0,45283.0,54146.0,880.0,1726.0,3849.0,16.0,10.0,28.0,8.0,8.0,22.0,10.0
92422,LOLTMNT02_457213,LCK,2026-08-21 13:16:04,3,16.16,100,Blue,team,NaN,T1,0.0,NaN,Cassiopeia,Orianna,Jayce,Akali,Locke,Caitlyn,Lux,Skarner,Anivia,Gwen,2061,1,14,7,35,14,7,2.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4076,0.6114,1.0,3.0,2.0,3.0,2.0,0.0,0.0,2.0,1.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,0.0,10.0,3.0,1.0,1.0,43.0,18.0,2.0,0.0,90521,2635.2547,NaN,3320.7569,3347.1033,41529.0,130,3.7846,65,1.8923,60.0,371,10.8006,68885,46485,1353.2751,NaN,58935.0,0.017113,-0.01,NaN,1040.0,250,37.5546,16790.0,19453.0,347.0,17391.0,20535.0,374.0,-601.0,-1082.0,-27.0,3.0,5.0,3.0,3.0,2.0,3.0,25954.0,32275.0,546.0,26233.0,32327.0,579.0,-279.0,-52.0,-33.0,4.0,6.0,3.0,3.0,2.0,4.0,34752.0,43453.0,758.0,35769.0,44961.0,799.0,-1017.0,-1508.0,-41.0,4.0,6.0,4.0,4.0,6.0,4.0,44308.0,58123.0,974.0,43804.0,56985.0,1000.0,504.0,1138.0,-26.0,5.0,9.0,4.0,4.0,6.0,5.0
92255,LOLTMNT02_457093,LCK,2026-08-21 08:07:26,1,16.16,200,Red,team,NaN,HANJIN BRION,1.0,NaN,Lucian,Nocturne,Ezreal,Kalista,Yunara,Ryze,Pantheon,Olaf,Corki,Karma,2314,0,17,18,37,17,18,2.0,1.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4408,0.9075,1.0,3.0,3.0,3.0,3.0,1.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,1.0,3.0,9.0,0.0,0.0,19.0,38.0,0.0,2.0,100313,2601.0285,NaN,4107.3552,3885.0908,16917.0,139,3.6041,76,1.9706,67.0,407,10.5532,74503,49522,1284.0622,NaN,71978.0,0.022664,-0.48,NaN,1126.0,269,36.1711,16218.0,20387.0,353.0,17523.0,21026.0,380.0,-1305.0,-639.0,-27.0,1.0,1.0,2.0,2.0,2.0,1.0,25249.0,32050.0,547.0,25707.0,31675.0,579.0,-458.0,375.0,-32.0,3.0,3.0,2.0,2.0,2.0,3.0,38392.0,47006.0,736.0,35384.0,44017.0,758.0,3008.0,2989.0,-22.0,11.0,20.0,5.0,5.0,10.0,11.0,46541.0,57941.0,920.0,47682.0,58900.0,957.0,-1141.0,-959.0,-37.0,11.0,20.0,10.0,10.0,28.0,11.0
90910,LOLTMNT02_452801,RL,2026-08-19 16:14:57,2,16.16,100,Blue,team,NaN,UP2UMEDIA Cebulaki,1.0,NaN,Lee Sin,Jayce,Orianna,Caitlyn,Lulu,Nocturne,Vladimir,Rumble,Varus,Rell,1657,0,6,24,18,6,24,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.2173,1.0863,0.0,0.0,4.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,11.0,0.0,0.0,4.0,45.0,0.0,3.0,66044,2391.4544,NaN,3933.6753,3006.1195,3274.0,77,2.7882,23,0.8328,21.0,176,6.3730,44220,25941,939.3241,NaN,42970.0,-0.199455,-4.35,NaN,736.0,144,31.8648,15703.0,19868.0,336.0,18600.0,20981.0,364.0,-2897.0,-1113.0,-28.0,1.0,2.0,5.0,5.0,6.0,1.0,24423.0,32218.0,533.0,28297.0,33997.0,582.0,-3874.0,-1779.0,-49.0,2.0,5.0,6.0,6.0,8.0,2.0,32675.0,42670.0,678.0,42447.0,49404.0,781.0,-9772.0,-6734.0,-103.0,4.0,11.0,13.0,13.0,21.0,4.0,40794.0,53975.0,833.0,54974.0,64878.0,989.0,-14180.0,-10903.0,-156.0,5.0,14.0,17.0,17.0,28.0,5.0
93694,LOLTMNT05_219216,AL,2026-08-25 16:16:36,1,16.16,100,Blue,team,NaN,GnG Amazigh,1.0,NaN,Zoe,Orianna,Wukong,K'Sante,Olaf,Nocturne,LeBlanc,Kai'Sa,Rell,Gnar,2286,0,19,36,35,19,36,0.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.4987,1.4436,0.0,0.0,5.0,0.0,4.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,1.0,3.0,0.0,0.0,0.0,2.0,0.0,0.0,4.0,11.0,0.0,0.0,25.0,41.0,0.0,2.0,113274,2973.0709,NaN,4450.8399,4256.1680,20390.0,108,2.8346,51,1.3386,31.0,311,8.1627,74483,49788,1306.7717,NaN,73268.0,-0.043787,-1.65,NaN,975.0,219,31.3386,16736.0,20062.0,350.0,17278.0,19738.0,334.0,-542.0,324.0,16.0,2.0,1.0,5.0,5.0,4.0,2.0,26200.0,31306.0,537.0,27713.0,33882.0,550.0,-1513.0,-2576.0,-13.0,4.0,5.0,8.0,8.0,8.0,4.0,36403.0,42214.0,677.0,39916.0,47068.0,706.0,-3513.0,-4854.0,-29.0,8.0,12.0,16.0,16.0,26.0,8.0,48130.0,55255.0,840.0,51752.0,62104.0,880.0,-3622.0,-6849.0,-40.0,12.0,20.0,24.0,24.0,47.0,12.0
91331,LOLTMNT02_452972,LCKC,2026-08-20 05:07:00,1,16.16,200,Red,team,NaN,HANJIN BRION Challengers,1.0,NaN,Akali,Lucian,Vayne,Karma,Bard,Orianna,Olaf,Shen,Corki,Xin Zhao,1493,0,4,18,9,4,18,0.0,0.0,0.0,0.0,1.0,NaN,NaN,NaN,0.1608,0.8841,0.0,0.0,3.0,0.0,3.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,3.0,0.0,0.0,1.0,0.0,0.0,0.0,9.0,0.0,0.0,5.0,42.0,0.0,1.0,54249,2180.1340,NaN,3416.6242,2542.7863,1692.0,74,2.9739,28,1.1253,30.0,185,7.4347,40108,23501,944.4474,NaN,39138.0,-0.212081,-2.82,NaN,724.0,144,34.8828,15943.0,19972.0,360.0,17203.0,20605.0,386.0,-1260.0,-633.0,-26.0,1.0,0.0,2.0,2.0,2.0,1.0,24135.0,32246.0,575.0,26714.0,33849.0,604.0,-2579.0,-1603.0,-29.0,1.0,0.0,4.0,4.0,8.0,1.0,32749.0,43421.0,733.0,38457.0,47023.0,774.0,-5708.0,-3602.0,-41.0,3.0,6.0,10.0,10.0,24.0,3.0,40108.0,53268.0,868.0,54495.0,65203.0,948.0,-14387.0,-11935.0,-80.0,4.0,9.0,18.0,18.0,51.0,4.0
91811,LOLTMNT05_217512,TCL,2026-08-20 17:14:15,3,16.16,200,Red,team,NaN,DIA Ozarox Esports,0.0,NaN,Locke,Bard,Camille,Varus,Azir,K'Sante,Jarvan IV,Orianna,Lucian,Milio,2470,0,14,24,43,14,24,3.0,0.0,0.0,0.0,0.0,NaN,NaN,NaN,0.3401,0.9231,1.0,2.0,3.0,2.0,3.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,1.0,2.0,1.0,0.0,1.0,5.0,9.0,1.0,1.0,27.0,35.0,0.0,1.0,137722,3345.4737,NaN,4228.4696,6468.9717,27475.0,85,2.0648,45,1.0931,42.0,288,6.9960,73569,46997,1141.6275,NaN,70880.0,-0.033023,-0.57,NaN,1040.0,246,31.2389,17159.0,20735.0,353.0,17274.0,21048.0,363.0,-115.0,-313.0,-10.0,3.0,5.0,3.0,3.0,3.0,3.0,25560.0,33240.0,571.0,26204.0,33710.0,543.0,-644.0,-470.0,28.0,3.0,5.0,5.0,5.0,7.0,3.0,37685.0,46032.0,753.0,34968.0,45427.0,724.0,2717.0,605.0,29.0,7.0,19.0,6.0,6.0,11.0,7.0,46548.0,58726.0,877.0,46284.0,58220.0,881.0,264.0,506.0,-4.0,10.0,28.0,10.0,10.0,23.0,10.0
93334,LOLTMNT05_219177,LEC,2026-08-24 17:12:18,1,16.16,100,Blue,team,NaN,G2 Esports,1.0,NaN,Nocturne,Jayce,Nautilus,Vayne,Olaf,Jarvan IV,Ashe,Seraphine,Ambessa,Akali,1535,1,20,6,30,20,6,1.0,1.0,1.0,0.0,0.0,NaN,NaN,NaN,0.7818,1.0163,1.0,4.0,0.0,4.0,0.0,0.0,1.0,2.0,0.0,0.0,1.0,0.0,0.0,1.0,1.0,0.0,0.0,3.0,1.0,1.0,0.0,0.0,1.0,9.0,2.0,1.0,1.0,38.0,16.0,1.0,0.0,73346,2866.9446,NaN,3439.3094,3816.0391,35992.0,88,3.4397,37,1.4463,36.0,259,10.1238,56327,39292,1535.8436,NaN,50495.0,0.136495,3.43,NaN,768.0,207,38.1107,18022.0,21582.0,390.0,15628.0,19750.0,337.0,2394.0,1832.0,53.0,3.0,4.0,1.0,1.0,0.0,3.0,29611.0,35312.0,607.0,23456.0,30300.0,514.0,6155.0,5012.0,93.0,6.0,9.0,1.0,1.0,0.0,6.0,41631.0,49887.0,811.0,33392.0,41516.0,711.0,8239.0,8371.0,100.0,11.0,16.0,2.0,2.0,2.0,11.0,54799.0,66960.0,960.0,45333.0,55666.0,874.0,9466.0,11294.0,86.0,19.0,27.0,6.0,6.0,10.0,19.0